/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -g3 -O0 -gdwarf-3  -IC:\Bin\nim-0.18.0\lib -o C:\Users\Dustin.Neumann\Documents\Nim\VectorGuy\src\nimcache\sdl2_nim_sdl_image.o C:\Users\Dustin.Neumann\Documents\Nim\VectorGuy\src\nimcache\sdl2_nim_sdl_image.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TGenericSeq TGenericSeq;typedef struct NimStringDesc NimStringDesc;struct TGenericSeq {NI len;NI reserved;};
struct NimStringDesc {  TGenericSeq Sup;NIM_CHAR data[SEQ_DECL_SIZE];};
typedef N_CDECL_PTR(void**, tyProc_1LIoIPgxf1fnU6YXXXDfCA) (void* renderer, NCSTRING file);
#line 115 "C:\\Bin\\nim-0.18.0\\lib\\system\\dyncalls.nim"
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
#line 27 "C:\\Bin\\nim-0.18.0\\lib\\system\\dyncalls.nim"
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
#line 118 "C:\\Bin\\nim-0.18.0\\lib\\system\\dyncalls.nim"
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
#line 417 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s);
#line 412 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
#line 70 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void);static void* TM_KBqytsBOSVgv4K9bnF5oGYQ_2;tyProc_1LIoIPgxf1fnU6YXXXDfCA Dl_199060_;extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;STRING_LITERAL(TM_KBqytsBOSVgv4K9bnF5oGYQ_4, "SDL2_image.dll", 14);STRING_LITERAL(TM_KBqytsBOSVgv4K9bnF5oGYQ_5, "SDL2_image.dll", 14);

#line 417 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
#line 418 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
	T1_ = (NI)0;
#line 418 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
	{
#line 418 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;		T1_ = ((NI) 0);	}	goto LA2_;	LA4_: ;	{
#line 418 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));	}	LA2_: ;	(*s).calldepth = ((NI16) (T1_));
#line 419 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 420 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 421 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
	{
#line 421 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
#line 421 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();	}	LA9_: ;}


#line 70 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void) {

#line 71 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}
NIM_EXTERNC N_NOINLINE(void, sdl2_nim_sdl_imageInit000)(void) {
	nimfr_("sdl_image", "sdl_image.nim");	popFrame();}

NIM_EXTERNC N_NOINLINE(void, sdl2_nim_sdl_imageDatInit000)(void) {
if (!((TM_KBqytsBOSVgv4K9bnF5oGYQ_2 = nimLoadLibrary((NimStringDesc*) &TM_KBqytsBOSVgv4K9bnF5oGYQ_4)))) nimLoadLibraryError((NimStringDesc*) &TM_KBqytsBOSVgv4K9bnF5oGYQ_5);	Dl_199060_ = (tyProc_1LIoIPgxf1fnU6YXXXDfCA) nimGetProcAddr(TM_KBqytsBOSVgv4K9bnF5oGYQ_2, "IMG_LoadTexture");}

