/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -g3 -O0 -gdwarf-3  -IC:\Bin\nim-0.18.0\lib -o C:\Users\Dustin.Neumann\Documents\Nim\VectorGuy\src\nimcache\stdlib_hashes.o C:\Users\Dustin.Neumann\Documents\Nim\VectorGuy\src\nimcache\stdlib_hashes.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;typedef struct TGenericSeq TGenericSeq;struct TGenericSeq {NI len;NI reserved;};
struct NimStringDesc {  TGenericSeq Sup;NIM_CHAR data[SEQ_DECL_SIZE];};

#line 50 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
static N_INLINE(NI, emarkamp__6dtCP6C39bxOkT4wrIPJwKghashes)(NI h, NI val);
#line 417 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s);
#line 412 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
#line 70 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void);
#line 57 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
static N_INLINE(NI, emarkdollar__zs9byUtT9cNi2e9clB27b2cUAhashes)(NI h);
#line 64 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
N_LIB_PRIVATE N_NIMCALL(NI, hashData_yovoXItSw1cVwd06rHjO3Q)(void* data, NI size);
#line 319 "C:\\Bin\\nim-0.18.0\\lib\\system\\arithm.nim"
static N_INLINE(NI, addInt)(NI a, NI b);
#line 13 "C:\\Bin\\nim-0.18.0\\lib\\system\\arithm.nim"
N_NOINLINE(void, raiseOverflow)(void);
#line 326 "C:\\Bin\\nim-0.18.0\\lib\\system\\arithm.nim"
static N_INLINE(NI, subInt)(NI a, NI b);
#line 83 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
static N_INLINE(NI, hash_ik2gygLR0dil3Sp9aYFpg9cQhashes)(void* x);
#line 107 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
static N_INLINE(NI, hash_M6zZEYz39abIOUmj0QsNREghashes)(NI x);
#line 111 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
static N_INLINE(NI, hash_wXLApNp4hVfHIRffgEB6jwhashes)(NI64 x);
#line 115 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
static N_INLINE(NI, hash_dhRs9ctgdvantAislvio9b8ghashes)(NU x);
#line 119 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
static N_INLINE(NI, hash_NG8iNI45ueAs5Mn0BFI3Iwhashes)(NU64 x);
#line 123 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
static N_INLINE(NI, hash_pHd9bQtK7hxXdD9blc45ElOQhashes)(NIM_CHAR x);
#line 131 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
N_LIB_PRIVATE N_NIMCALL(NI, hash_uBstFm5SYVQeOL3j9c9bc58A)(NimStringDesc* x);
#line 18 "C:\\Bin\\nim-0.18.0\\lib\\system\\chcks.nim"
N_NOINLINE(void, raiseIndexError)(void);
#line 138 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
N_LIB_PRIVATE N_NIMCALL(NI, hash_jI32kLEzL20xGDPOKccuRg)(NCSTRING x);
#line 152 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
N_LIB_PRIVATE N_NIMCALL(NI, hash_cEF5Tk3m50EURxpIqAvuYg)(NimStringDesc* sBuf, NI sPos, NI ePos);
#line 162 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
N_LIB_PRIVATE N_NIMCALL(NI, hashIgnoreStyle_uBstFm5SYVQeOL3j9c9bc58A_2)(NimStringDesc* x);
#line 30 "C:\\Bin\\nim-0.18.0\\lib\\system\\chcks.nim"
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
#line 12 "C:\\Bin\\nim-0.18.0\\lib\\system\\chcks.nim"
N_NOINLINE(void, raiseRangeError)(NI64 val);
#line 179 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
N_LIB_PRIVATE N_NIMCALL(NI, hashIgnoreStyle_cEF5Tk3m50EURxpIqAvuYg_2)(NimStringDesc* sBuf, NI sPos, NI ePos);
#line 198 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
N_LIB_PRIVATE N_NIMCALL(NI, hashIgnoreCase_uBstFm5SYVQeOL3j9c9bc58A_3)(NimStringDesc* x);
#line 208 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
N_LIB_PRIVATE N_NIMCALL(NI, hashIgnoreCase_cEF5Tk3m50EURxpIqAvuYg_3)(NimStringDesc* sBuf, NI sPos, NI ePos);
#line 222 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
static N_INLINE(NI, hash_6GPBATuIA6xplfOnZj9bPQghashes)(NF x);extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;

#line 417 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
#line 418 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
	T1_ = (NI)0;
#line 418 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
	{
#line 418 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;		T1_ = ((NI) 0);	}	goto LA2_;	LA4_: ;	{
#line 418 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));	}	LA2_: ;	(*s).calldepth = ((NI16) (T1_));
#line 419 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 420 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 421 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
	{
#line 421 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
#line 421 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();	}	LA9_: ;}


#line 70 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void) {

#line 71 "C:\\Bin\\nim-0.18.0\\lib\\system\\excpt.nim"
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}


#line 50 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
static N_INLINE(NI, emarkamp__6dtCP6C39bxOkT4wrIPJwKghashes)(NI h, NI val) {
	NI result;	nimfr_("!&", "hashes.nim");	result = (NI)0;
#line 53 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(53, "hashes.nim");
#line 53 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	result = (NI)((NU64)(h) + (NU64)(val));
#line 54 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(54, "hashes.nim");
#line 54 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"

#line 54 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	result = (NI)((NU64)(result) + (NU64)((NI)((NU64)(result) << (NU64)(((NI) 10)))));
#line 55 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(55, "hashes.nim");
#line 55 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"

#line 55 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	result = (NI)(result ^ (NI)((NU64)(result) >> (NU64)(((NI) 6))));	popFrame();	return result;}


#line 57 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
static N_INLINE(NI, emarkdollar__zs9byUtT9cNi2e9clB27b2cUAhashes)(NI h) {
	NI result;	nimfr_("!$", "hashes.nim");	result = (NI)0;
#line 60 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(60, "hashes.nim");
#line 60 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"

#line 60 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	result = (NI)((NU64)(h) + (NU64)((NI)((NU64)(h) << (NU64)(((NI) 3)))));
#line 61 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(61, "hashes.nim");
#line 61 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"

#line 61 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	result = (NI)(result ^ (NI)((NU64)(result) >> (NU64)(((NI) 11))));
#line 62 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(62, "hashes.nim");
#line 62 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"

#line 62 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	result = (NI)((NU64)(result) + (NU64)((NI)((NU64)(result) << (NU64)(((NI) 15)))));	popFrame();	return result;}


#line 319 "C:\\Bin\\nim-0.18.0\\lib\\system\\arithm.nim"
static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;{	result = (NI)0;
#line 320 "C:\\Bin\\nim-0.18.0\\lib\\system\\arithm.nim"

#line 320 "C:\\Bin\\nim-0.18.0\\lib\\system\\arithm.nim"
	result = (NI)((NU64)(a) + (NU64)(b));
#line 321 "C:\\Bin\\nim-0.18.0\\lib\\system\\arithm.nim"
	{		NIM_BOOL T3_;
#line 321 "C:\\Bin\\nim-0.18.0\\lib\\system\\arithm.nim"
		T3_ = (NIM_BOOL)0;
#line 321 "C:\\Bin\\nim-0.18.0\\lib\\system\\arithm.nim"

#line 321 "C:\\Bin\\nim-0.18.0\\lib\\system\\arithm.nim"
		T3_ = (((NI) 0) <= (NI)(result ^ a));		if (T3_) goto LA4_;
#line 321 "C:\\Bin\\nim-0.18.0\\lib\\system\\arithm.nim"

#line 321 "C:\\Bin\\nim-0.18.0\\lib\\system\\arithm.nim"
		T3_ = (((NI) 0) <= (NI)(result ^ b));		LA4_: ;		if (!T3_) goto LA5_;
#line 322 "C:\\Bin\\nim-0.18.0\\lib\\system\\arithm.nim"
		goto BeforeRet_;	}	LA5_: ;
#line 323 "C:\\Bin\\nim-0.18.0\\lib\\system\\arithm.nim"
	raiseOverflow();	}BeforeRet_: ;	return result;}


#line 326 "C:\\Bin\\nim-0.18.0\\lib\\system\\arithm.nim"
static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;{	result = (NI)0;
#line 327 "C:\\Bin\\nim-0.18.0\\lib\\system\\arithm.nim"

#line 327 "C:\\Bin\\nim-0.18.0\\lib\\system\\arithm.nim"
	result = (NI)((NU64)(a) - (NU64)(b));
#line 328 "C:\\Bin\\nim-0.18.0\\lib\\system\\arithm.nim"
	{		NIM_BOOL T3_;
#line 328 "C:\\Bin\\nim-0.18.0\\lib\\system\\arithm.nim"
		T3_ = (NIM_BOOL)0;
#line 328 "C:\\Bin\\nim-0.18.0\\lib\\system\\arithm.nim"

#line 328 "C:\\Bin\\nim-0.18.0\\lib\\system\\arithm.nim"
		T3_ = (((NI) 0) <= (NI)(result ^ a));		if (T3_) goto LA4_;
#line 328 "C:\\Bin\\nim-0.18.0\\lib\\system\\arithm.nim"

#line 328 "C:\\Bin\\nim-0.18.0\\lib\\system\\arithm.nim"

#line 328 "C:\\Bin\\nim-0.18.0\\lib\\system\\arithm.nim"
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));		LA4_: ;		if (!T3_) goto LA5_;
#line 329 "C:\\Bin\\nim-0.18.0\\lib\\system\\arithm.nim"
		goto BeforeRet_;	}	LA5_: ;
#line 330 "C:\\Bin\\nim-0.18.0\\lib\\system\\arithm.nim"
	raiseOverflow();	}BeforeRet_: ;	return result;}


#line 64 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
N_LIB_PRIVATE N_NIMCALL(NI, hashData_yovoXItSw1cVwd06rHjO3Q)(void* data, NI size) {
	NI result;	NI h;	NCSTRING p;	NI i;	NI s;	nimfr_("hashData", "hashes.nim");	result = (NI)0;
#line 66 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(66, "hashes.nim");	h = ((NI) 0);
#line 71 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(71, "hashes.nim");	p = ((NCSTRING) (data));
#line 72 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(72, "hashes.nim");	i = ((NI) 0);
#line 73 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(73, "hashes.nim");	s = size;	{
#line 74 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
		nimln_(74, "hashes.nim");		while (1) {			NI TM_7tkD9cFJSchVDwHuwaY9bP9bA_2;			NI TM_7tkD9cFJSchVDwHuwaY9bP9bA_3;
#line 74 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
			if (!(((NI) 0) < s)) goto LA2;
#line 75 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
			nimln_(75, "hashes.nim");
#line 75 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
			h = emarkamp__6dtCP6C39bxOkT4wrIPJwKghashes(h, ((NU8)(p[i])));
#line 76 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
			nimln_(76, "hashes.nim");			TM_7tkD9cFJSchVDwHuwaY9bP9bA_2 = addInt(i, ((NI) 1));			i = (NI)(TM_7tkD9cFJSchVDwHuwaY9bP9bA_2);
#line 77 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
			nimln_(77, "hashes.nim");			TM_7tkD9cFJSchVDwHuwaY9bP9bA_3 = subInt(s, ((NI) 1));			s = (NI)(TM_7tkD9cFJSchVDwHuwaY9bP9bA_3);		} LA2: ;	}
#line 78 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(78, "hashes.nim");	result = emarkdollar__zs9byUtT9cNi2e9clB27b2cUAhashes(h);	popFrame();	return result;}


#line 83 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
static N_INLINE(NI, hash_ik2gygLR0dil3Sp9aYFpg9cQhashes)(void* x) {
	NI result;	nimfr_("hash", "hashes.nim");	result = (NI)0;
#line 97 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(97, "hashes.nim");
#line 97 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	result = (NI)((NU64)(((NI) (ptrdiff_t) (x))) >> (NU64)(((NI) 3)));	popFrame();	return result;}


#line 107 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
static N_INLINE(NI, hash_M6zZEYz39abIOUmj0QsNREghashes)(NI x) {
	NI result;	nimfr_("hash", "hashes.nim");	result = (NI)0;
#line 109 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(109, "hashes.nim");	result = x;	popFrame();	return result;}


#line 111 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
static N_INLINE(NI, hash_wXLApNp4hVfHIRffgEB6jwhashes)(NI64 x) {
	NI result;	nimfr_("hash", "hashes.nim");	result = (NI)0;
#line 113 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(113, "hashes.nim");
#line 113 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	result = ((NI) (((NI32)(NU32)(NU64)(x))));	popFrame();	return result;}


#line 115 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
static N_INLINE(NI, hash_dhRs9ctgdvantAislvio9b8ghashes)(NU x) {
	NI result;	nimfr_("hash", "hashes.nim");	result = (NI)0;
#line 117 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(117, "hashes.nim");	result = ((NI) (x));	popFrame();	return result;}


#line 119 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
static N_INLINE(NI, hash_NG8iNI45ueAs5Mn0BFI3Iwhashes)(NU64 x) {
	NI result;	nimfr_("hash", "hashes.nim");	result = (NI)0;
#line 121 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(121, "hashes.nim");
#line 121 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	result = ((NI) (((NI32)(NU32)(NU64)(((NI64) (((NI) (x))))))));	popFrame();	return result;}


#line 123 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
static N_INLINE(NI, hash_pHd9bQtK7hxXdD9blc45ElOQhashes)(NIM_CHAR x) {
	NI result;	nimfr_("hash", "hashes.nim");	result = (NI)0;
#line 125 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(125, "hashes.nim");
#line 125 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	result = ((NU8)(x));	popFrame();	return result;}


#line 131 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
N_LIB_PRIVATE N_NIMCALL(NI, hash_uBstFm5SYVQeOL3j9c9bc58A)(NimStringDesc* x) {
	NI result;	NI h;	nimfr_("hash", "hashes.nim");	result = (NI)0;
#line 133 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(133, "hashes.nim");	h = ((NI) 0);	{		NI i;		NI colontmp_;		NI TM_7tkD9cFJSchVDwHuwaY9bP9bA_4;		NI res;		i = (NI)0;		colontmp_ = (NI)0;
#line 134 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
		nimln_(134, "hashes.nim");
#line 134 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"

#line 134 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
		TM_7tkD9cFJSchVDwHuwaY9bP9bA_4 = subInt((x ? x->Sup.len : 0), ((NI) 1));		colontmp_ = (NI)(TM_7tkD9cFJSchVDwHuwaY9bP9bA_4);
#line 2045 "C:\\Bin\\nim-0.18.0\\lib\\system.nim"
		nimln_(2045, "system.nim");		res = ((NI) 0);		{
#line 2046 "C:\\Bin\\nim-0.18.0\\lib\\system.nim"
			nimln_(2046, "system.nim");			while (1) {				NI TM_7tkD9cFJSchVDwHuwaY9bP9bA_5;
#line 2046 "C:\\Bin\\nim-0.18.0\\lib\\system.nim"
				if (!(res <= colontmp_)) goto LA3;
#line 2047 "C:\\Bin\\nim-0.18.0\\lib\\system.nim"
				nimln_(2047, "system.nim");				i = res;
#line 135 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
				nimln_(135, "hashes.nim");
#line 135 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
				if ((NU)(i) > (NU)(x->Sup.len)) raiseIndexError();				h = emarkamp__6dtCP6C39bxOkT4wrIPJwKghashes(h, ((NU8)(x->data[i])));
#line 2048 "C:\\Bin\\nim-0.18.0\\lib\\system.nim"
				nimln_(2048, "system.nim");				TM_7tkD9cFJSchVDwHuwaY9bP9bA_5 = addInt(res, ((NI) 1));				res = (NI)(TM_7tkD9cFJSchVDwHuwaY9bP9bA_5);			} LA3: ;		}	}
#line 136 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(136, "hashes.nim");	result = emarkdollar__zs9byUtT9cNi2e9clB27b2cUAhashes(h);	popFrame();	return result;}


#line 138 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
N_LIB_PRIVATE N_NIMCALL(NI, hash_jI32kLEzL20xGDPOKccuRg)(NCSTRING x) {
	NI result;	NI h;	NI i;	nimfr_("hash", "hashes.nim");	result = (NI)0;
#line 140 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(140, "hashes.nim");	h = ((NI) 0);
#line 141 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(141, "hashes.nim");	i = ((NI) 0);	{
#line 147 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
		nimln_(147, "hashes.nim");		while (1) {			NI TM_7tkD9cFJSchVDwHuwaY9bP9bA_6;
#line 398 "C:\\Bin\\nim-0.18.0\\lib\\system.nim"
			nimln_(398, "system.nim");
#line 147 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
			nimln_(147, "hashes.nim");			if (!!(((NU8)(x[i]) == (NU8)(0)))) goto LA2;
#line 148 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
			nimln_(148, "hashes.nim");
#line 148 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
			h = emarkamp__6dtCP6C39bxOkT4wrIPJwKghashes(h, ((NU8)(x[i])));
#line 149 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
			nimln_(149, "hashes.nim");			TM_7tkD9cFJSchVDwHuwaY9bP9bA_6 = addInt(i, ((NI) 1));			i = (NI)(TM_7tkD9cFJSchVDwHuwaY9bP9bA_6);		} LA2: ;	}
#line 150 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(150, "hashes.nim");	result = emarkdollar__zs9byUtT9cNi2e9clB27b2cUAhashes(h);	popFrame();	return result;}


#line 152 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
N_LIB_PRIVATE N_NIMCALL(NI, hash_cEF5Tk3m50EURxpIqAvuYg)(NimStringDesc* sBuf, NI sPos, NI ePos) {
	NI result;	NI h;	nimfr_("hash", "hashes.nim");	result = (NI)0;
#line 157 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(157, "hashes.nim");	h = ((NI) 0);	{		NI i;		NI res;		i = (NI)0;
#line 2045 "C:\\Bin\\nim-0.18.0\\lib\\system.nim"
		nimln_(2045, "system.nim");		res = sPos;		{
#line 2046 "C:\\Bin\\nim-0.18.0\\lib\\system.nim"
			nimln_(2046, "system.nim");			while (1) {				NI TM_7tkD9cFJSchVDwHuwaY9bP9bA_7;
#line 2046 "C:\\Bin\\nim-0.18.0\\lib\\system.nim"
				if (!(res <= ePos)) goto LA3;
#line 2047 "C:\\Bin\\nim-0.18.0\\lib\\system.nim"
				nimln_(2047, "system.nim");				i = res;
#line 159 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
				nimln_(159, "hashes.nim");
#line 159 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
				if ((NU)(i) > (NU)(sBuf->Sup.len)) raiseIndexError();				h = emarkamp__6dtCP6C39bxOkT4wrIPJwKghashes(h, ((NU8)(sBuf->data[i])));
#line 2048 "C:\\Bin\\nim-0.18.0\\lib\\system.nim"
				nimln_(2048, "system.nim");				TM_7tkD9cFJSchVDwHuwaY9bP9bA_7 = addInt(res, ((NI) 1));				res = (NI)(TM_7tkD9cFJSchVDwHuwaY9bP9bA_7);			} LA3: ;		}	}
#line 160 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(160, "hashes.nim");	result = emarkdollar__zs9byUtT9cNi2e9clB27b2cUAhashes(h);	popFrame();	return result;}


#line 30 "C:\\Bin\\nim-0.18.0\\lib\\system\\chcks.nim"
static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;{	result = (NI)0;
#line 31 "C:\\Bin\\nim-0.18.0\\lib\\system\\chcks.nim"
	{		NIM_BOOL T3_;
#line 31 "C:\\Bin\\nim-0.18.0\\lib\\system\\chcks.nim"
		T3_ = (NIM_BOOL)0;
#line 31 "C:\\Bin\\nim-0.18.0\\lib\\system\\chcks.nim"
		T3_ = (a <= i);		if (!(T3_)) goto LA4_;
#line 31 "C:\\Bin\\nim-0.18.0\\lib\\system\\chcks.nim"
		T3_ = (i <= b);		LA4_: ;		if (!T3_) goto LA5_;
#line 32 "C:\\Bin\\nim-0.18.0\\lib\\system\\chcks.nim"

#line 32 "C:\\Bin\\nim-0.18.0\\lib\\system\\chcks.nim"
		result = i;		goto BeforeRet_;	}	goto LA1_;	LA5_: ;	{
#line 34 "C:\\Bin\\nim-0.18.0\\lib\\system\\chcks.nim"
		raiseRangeError(((NI64) (i)));	}	LA1_: ;	}BeforeRet_: ;	return result;}


#line 162 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
N_LIB_PRIVATE N_NIMCALL(NI, hashIgnoreStyle_uBstFm5SYVQeOL3j9c9bc58A_2)(NimStringDesc* x) {
	NI result;	NI h;	NI i;	NI xLen;	nimfr_("hashIgnoreStyle", "hashes.nim");	result = (NI)0;
#line 164 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(164, "hashes.nim");	h = ((NI) 0);
#line 165 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(165, "hashes.nim");	i = ((NI) 0);
#line 166 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(166, "hashes.nim");
#line 166 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	xLen = (x ? x->Sup.len : 0);	{
#line 167 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
		nimln_(167, "hashes.nim");		while (1) {			NIM_CHAR c;
#line 167 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
			if (!(i < xLen)) goto LA2;
#line 168 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
			nimln_(168, "hashes.nim");			if ((NU)(i) > (NU)(x->Sup.len)) raiseIndexError();			c = x->data[i];
#line 169 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
			nimln_(169, "hashes.nim");			{				NI TM_7tkD9cFJSchVDwHuwaY9bP9bA_8;
#line 169 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
				if (!((NU8)(c) == (NU8)(95))) goto LA5_;
#line 170 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
				nimln_(170, "hashes.nim");				TM_7tkD9cFJSchVDwHuwaY9bP9bA_8 = addInt(i, ((NI) 1));				i = (NI)(TM_7tkD9cFJSchVDwHuwaY9bP9bA_8);			}			goto LA3_;			LA5_: ;			{				NI TM_7tkD9cFJSchVDwHuwaY9bP9bA_10;
#line 172 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
				nimln_(172, "hashes.nim");				{					NI TM_7tkD9cFJSchVDwHuwaY9bP9bA_9;
#line 172 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
					if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA10_;
#line 173 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
					nimln_(173, "hashes.nim");
#line 173 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"

#line 173 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"

#line 173 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
					TM_7tkD9cFJSchVDwHuwaY9bP9bA_9 = addInt(((NU8)(c)), ((NI) 32));					c = ((NIM_CHAR) (((NI)chckRange((NI)(TM_7tkD9cFJSchVDwHuwaY9bP9bA_9), ((NI) 0), ((NI) 255)))));				}				LA10_: ;
#line 174 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
				nimln_(174, "hashes.nim");
#line 174 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
				h = emarkamp__6dtCP6C39bxOkT4wrIPJwKghashes(h, ((NU8)(c)));
#line 175 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
				nimln_(175, "hashes.nim");				TM_7tkD9cFJSchVDwHuwaY9bP9bA_10 = addInt(i, ((NI) 1));				i = (NI)(TM_7tkD9cFJSchVDwHuwaY9bP9bA_10);			}			LA3_: ;		} LA2: ;	}
#line 177 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(177, "hashes.nim");	result = emarkdollar__zs9byUtT9cNi2e9clB27b2cUAhashes(h);	popFrame();	return result;}


#line 179 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
N_LIB_PRIVATE N_NIMCALL(NI, hashIgnoreStyle_cEF5Tk3m50EURxpIqAvuYg_2)(NimStringDesc* sBuf, NI sPos, NI ePos) {
	NI result;	NI h;	NI i;	nimfr_("hashIgnoreStyle", "hashes.nim");	result = (NI)0;
#line 185 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(185, "hashes.nim");	h = ((NI) 0);
#line 186 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(186, "hashes.nim");	i = sPos;	{
#line 187 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
		nimln_(187, "hashes.nim");		while (1) {			NIM_CHAR c;
#line 187 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
			if (!(i <= ePos)) goto LA2;
#line 188 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
			nimln_(188, "hashes.nim");			if ((NU)(i) > (NU)(sBuf->Sup.len)) raiseIndexError();			c = sBuf->data[i];
#line 189 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
			nimln_(189, "hashes.nim");			{				NI TM_7tkD9cFJSchVDwHuwaY9bP9bA_11;
#line 189 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
				if (!((NU8)(c) == (NU8)(95))) goto LA5_;
#line 190 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
				nimln_(190, "hashes.nim");				TM_7tkD9cFJSchVDwHuwaY9bP9bA_11 = addInt(i, ((NI) 1));				i = (NI)(TM_7tkD9cFJSchVDwHuwaY9bP9bA_11);			}			goto LA3_;			LA5_: ;			{				NI TM_7tkD9cFJSchVDwHuwaY9bP9bA_13;
#line 192 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
				nimln_(192, "hashes.nim");				{					NI TM_7tkD9cFJSchVDwHuwaY9bP9bA_12;
#line 192 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
					if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA10_;
#line 193 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
					nimln_(193, "hashes.nim");
#line 193 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"

#line 193 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"

#line 193 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
					TM_7tkD9cFJSchVDwHuwaY9bP9bA_12 = addInt(((NU8)(c)), ((NI) 32));					c = ((NIM_CHAR) (((NI)chckRange((NI)(TM_7tkD9cFJSchVDwHuwaY9bP9bA_12), ((NI) 0), ((NI) 255)))));				}				LA10_: ;
#line 194 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
				nimln_(194, "hashes.nim");
#line 194 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
				h = emarkamp__6dtCP6C39bxOkT4wrIPJwKghashes(h, ((NU8)(c)));
#line 195 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
				nimln_(195, "hashes.nim");				TM_7tkD9cFJSchVDwHuwaY9bP9bA_13 = addInt(i, ((NI) 1));				i = (NI)(TM_7tkD9cFJSchVDwHuwaY9bP9bA_13);			}			LA3_: ;		} LA2: ;	}
#line 196 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(196, "hashes.nim");	result = emarkdollar__zs9byUtT9cNi2e9clB27b2cUAhashes(h);	popFrame();	return result;}


#line 198 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
N_LIB_PRIVATE N_NIMCALL(NI, hashIgnoreCase_uBstFm5SYVQeOL3j9c9bc58A_3)(NimStringDesc* x) {
	NI result;	NI h;	nimfr_("hashIgnoreCase", "hashes.nim");	result = (NI)0;
#line 200 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(200, "hashes.nim");	h = ((NI) 0);	{		NI i;		NI colontmp_;		NI TM_7tkD9cFJSchVDwHuwaY9bP9bA_14;		NI res;		i = (NI)0;		colontmp_ = (NI)0;
#line 201 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
		nimln_(201, "hashes.nim");
#line 201 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"

#line 201 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
		TM_7tkD9cFJSchVDwHuwaY9bP9bA_14 = subInt((x ? x->Sup.len : 0), ((NI) 1));		colontmp_ = (NI)(TM_7tkD9cFJSchVDwHuwaY9bP9bA_14);
#line 2045 "C:\\Bin\\nim-0.18.0\\lib\\system.nim"
		nimln_(2045, "system.nim");		res = ((NI) 0);		{
#line 2046 "C:\\Bin\\nim-0.18.0\\lib\\system.nim"
			nimln_(2046, "system.nim");			while (1) {				NIM_CHAR c;				NI TM_7tkD9cFJSchVDwHuwaY9bP9bA_16;
#line 2046 "C:\\Bin\\nim-0.18.0\\lib\\system.nim"
				if (!(res <= colontmp_)) goto LA3;
#line 2047 "C:\\Bin\\nim-0.18.0\\lib\\system.nim"
				nimln_(2047, "system.nim");				i = res;
#line 202 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
				nimln_(202, "hashes.nim");				if ((NU)(i) > (NU)(x->Sup.len)) raiseIndexError();				c = x->data[i];
#line 203 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
				nimln_(203, "hashes.nim");				{					NI TM_7tkD9cFJSchVDwHuwaY9bP9bA_15;
#line 203 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
					if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA6_;
#line 204 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
					nimln_(204, "hashes.nim");
#line 204 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"

#line 204 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"

#line 204 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
					TM_7tkD9cFJSchVDwHuwaY9bP9bA_15 = addInt(((NU8)(c)), ((NI) 32));					c = ((NIM_CHAR) (((NI)chckRange((NI)(TM_7tkD9cFJSchVDwHuwaY9bP9bA_15), ((NI) 0), ((NI) 255)))));				}				LA6_: ;
#line 205 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
				nimln_(205, "hashes.nim");
#line 205 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
				h = emarkamp__6dtCP6C39bxOkT4wrIPJwKghashes(h, ((NU8)(c)));
#line 2048 "C:\\Bin\\nim-0.18.0\\lib\\system.nim"
				nimln_(2048, "system.nim");				TM_7tkD9cFJSchVDwHuwaY9bP9bA_16 = addInt(res, ((NI) 1));				res = (NI)(TM_7tkD9cFJSchVDwHuwaY9bP9bA_16);			} LA3: ;		}	}
#line 206 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(206, "hashes.nim");	result = emarkdollar__zs9byUtT9cNi2e9clB27b2cUAhashes(h);	popFrame();	return result;}


#line 208 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
N_LIB_PRIVATE N_NIMCALL(NI, hashIgnoreCase_cEF5Tk3m50EURxpIqAvuYg_3)(NimStringDesc* sBuf, NI sPos, NI ePos) {
	NI result;	NI h;	nimfr_("hashIgnoreCase", "hashes.nim");	result = (NI)0;
#line 214 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(214, "hashes.nim");	h = ((NI) 0);	{		NI i;		NI res;		i = (NI)0;
#line 2045 "C:\\Bin\\nim-0.18.0\\lib\\system.nim"
		nimln_(2045, "system.nim");		res = sPos;		{
#line 2046 "C:\\Bin\\nim-0.18.0\\lib\\system.nim"
			nimln_(2046, "system.nim");			while (1) {				NIM_CHAR c;				NI TM_7tkD9cFJSchVDwHuwaY9bP9bA_18;
#line 2046 "C:\\Bin\\nim-0.18.0\\lib\\system.nim"
				if (!(res <= ePos)) goto LA3;
#line 2047 "C:\\Bin\\nim-0.18.0\\lib\\system.nim"
				nimln_(2047, "system.nim");				i = res;
#line 216 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
				nimln_(216, "hashes.nim");				if ((NU)(i) > (NU)(sBuf->Sup.len)) raiseIndexError();				c = sBuf->data[i];
#line 217 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
				nimln_(217, "hashes.nim");				{					NI TM_7tkD9cFJSchVDwHuwaY9bP9bA_17;
#line 217 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
					if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA6_;
#line 218 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
					nimln_(218, "hashes.nim");
#line 218 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"

#line 218 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"

#line 218 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
					TM_7tkD9cFJSchVDwHuwaY9bP9bA_17 = addInt(((NU8)(c)), ((NI) 32));					c = ((NIM_CHAR) (((NI)chckRange((NI)(TM_7tkD9cFJSchVDwHuwaY9bP9bA_17), ((NI) 0), ((NI) 255)))));				}				LA6_: ;
#line 219 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
				nimln_(219, "hashes.nim");
#line 219 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
				h = emarkamp__6dtCP6C39bxOkT4wrIPJwKghashes(h, ((NU8)(c)));
#line 2048 "C:\\Bin\\nim-0.18.0\\lib\\system.nim"
				nimln_(2048, "system.nim");				TM_7tkD9cFJSchVDwHuwaY9bP9bA_18 = addInt(res, ((NI) 1));				res = (NI)(TM_7tkD9cFJSchVDwHuwaY9bP9bA_18);			} LA3: ;		}	}
#line 220 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(220, "hashes.nim");	result = emarkdollar__zs9byUtT9cNi2e9clB27b2cUAhashes(h);	popFrame();	return result;}


#line 222 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
static N_INLINE(NI, hash_6GPBATuIA6xplfOnZj9bPQghashes)(NF x) {
	NI result;	NF y;	nimfr_("hash", "hashes.nim");	result = (NI)0;
#line 224 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(224, "hashes.nim");
#line 224 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	y = ((NF)(x) + (NF)(1.0000000000000000e+000));
#line 225 "C:\\Bin\\nim-0.18.0\\lib\\pure\\hashes.nim"
	nimln_(225, "hashes.nim");	result = (*((NI*) ((&y))));	popFrame();	return result;}
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void) {
	nimfr_("hashes", "hashes.nim");	popFrame();}

NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void) {
}

