/* Generated by Nim Compiler v0.18.1 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/dustin/Documents/Nim/lib -o /home/dustin/Documents/Nim_Projects/VectorGuy/src/nimcache/VectorGuy_art.o /home/dustin/Documents/Nim_Projects/VectorGuy/src/nimcache/VectorGuy_art.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_0vYzovSm9aKYybyF8MRuBJQ tyTuple_0vYzovSm9aKYybyF8MRuBJQ;
typedef struct tyObject_CameracolonObjectType__uk8C2BjPELBcegmVYWmD5Q tyObject_CameracolonObjectType__uk8C2BjPELBcegmVYWmD5Q;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ;
typedef struct tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ;
typedef struct RootObj RootObj;
typedef struct tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ;
typedef struct tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ;
typedef struct tyObject_Rect_qiXweduDJk1iLE5aHysNdQ tyObject_Rect_qiXweduDJk1iLE5aHysNdQ;
typedef struct tyObject_Point_O882QUBegNwSZhlvLsYQRw tyObject_Point_O882QUBegNwSZhlvLsYQRw;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct tyTuple_0vYzovSm9aKYybyF8MRuBJQ {
NF Field0;
NF Field1;
NF Field2;
NF Field3;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ {
  RootObj Sup;
};
struct tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ {
  tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ Sup;
tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ* position;
tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ* size;
};
struct tyObject_CameracolonObjectType__uk8C2BjPELBcegmVYWmD5Q {
  tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ Sup;
NF zoom;
NF rotation;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ {
  RootObj Sup;
void* texture;
NI w;
NI h;
};
struct tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ {
NF x;
NF y;
};
typedef N_CDECL_PTR(int, tyProc_XKGgUlQDoYOavZdP09bvlvg) (void* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NU8 r, NU8 g, NU8 b, NU8 a);
struct tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ {
  RootObj Sup;
tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ* pos;
tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ* size;
};
struct tyObject_Rect_qiXweduDJk1iLE5aHysNdQ {
int x;
int y;
int w;
int h;
};
struct tyObject_Point_O882QUBegNwSZhlvLsYQRw {
int x;
int y;
};
typedef NI32 tyEnum_RendererFlip_v7zeNYRvzJgcDDS9cEco6wg;
typedef N_CDECL_PTR(int, tyProc_oVfcvGczxlST8hWjhSa9aHA) (void* renderer, void* texture, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ* srcrect, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ* dstrect, double angle, tyObject_Point_O882QUBegNwSZhlvLsYQRw* center, tyEnum_RendererFlip_v7zeNYRvzJgcDDS9cEco6wg flip);
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(void**, tyProc_1LIoIPgxf1fnU6YXXXDfCA) (void* renderer, NCSTRING file);
typedef NI32 tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw;
typedef N_CDECL_PTR(void, tyProc_DusjKySyJW30WdV9bsteVxw) (tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw category, NCSTRING fmt, ...);
typedef N_CDECL_PTR(NCSTRING, tyProc_09bvyvHFtWbkzL5AHgf0bKw) (void);
typedef NI32 tyEnum_TextureAccess_poCqMuWAVlQ9auy0EWhBQuA;
typedef N_CDECL_PTR(int, tyProc_Z3C0z9blaIY9abfEJhIF9b1WQ) (void* texture, NU32* format, tyEnum_TextureAccess_poCqMuWAVlQ9auy0EWhBQuA* access, int* w, int* h);
typedef N_CDECL_PTR(void, tyProc_32w2ZypAyMWuajvi2Jt79cg) (void* texture);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_gp9a09azZ9aBufqmUN9aOefMOw)(void* p, NI op);
static N_NIMCALL(void, TM_w2y8raIq9a7dDr5q9chSxV1w_4)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ*, Vec2_FI9b5IBktnCnUUYt6xN1b2g)(NF x, NF y);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_NIMCALL(void, Marker_tyRef_0kDVS9b1UyEqr8DfAGXwn9cQ)(void* p, NI op);
N_NOINLINE(void, chckNil)(void* p);
N_LIB_PRIVATE N_NIMCALL(int, toCint_yAPwf7d9aO5za0vgIa7yl8g)(NI x);
N_LIB_PRIVATE N_NIMCALL(tyObject_Rect_qiXweduDJk1iLE5aHysNdQ, sdlRect_ZAq9cYc7ulNNn21yQGBT79cg)(tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ* r);
N_LIB_PRIVATE N_NIMCALL(tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ*, newImage_tWxVwZ28d3tVcmFKmMn6ag)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, load_HwT5E7mbKGCJy0HINVoqrA)(tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ* obj, void* renderer, NimStringDesc* file);
static N_NIMCALL(void, Marker_tyRef_u6eWcr48DqP0Ue9cUPPUypg)(void* p, NI op);
tyTuple_0vYzovSm9aKYybyF8MRuBJQ current_color_ZVKdD8C4l7QMQR2o7qII2A;
tyObject_CameracolonObjectType__uk8C2BjPELBcegmVYWmD5Q* camera_gC9bhqCy0IQgaCB9bxtui42g;
extern TNimType NTI_gcAPnvgqasHnAwLl6W9cWFQ_;
TNimType NTI_uk8C2BjPELBcegmVYWmD5Q_;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
TNimType NTI_gp9a09azZ9aBufqmUN9aOefMOw_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_CILs0aI9a15OLIJJawRpwrQ_;
extern TNimType NTI_vr5DoT1jILTGdRlYv1OYpw_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_0kDVS9b1UyEqr8DfAGXwn9cQ_;
extern tyProc_XKGgUlQDoYOavZdP09bvlvg Dl_203103_;
extern tyProc_oVfcvGczxlST8hWjhSa9aHA Dl_120390_;
extern tyProc_XKGgUlQDoYOavZdP09bvlvg Dl_203063_;
extern tyProc_1LIoIPgxf1fnU6YXXXDfCA Dl_202060_;
extern tyProc_DusjKySyJW30WdV9bsteVxw Dl_119881_;
extern tyProc_09bvyvHFtWbkzL5AHgf0bKw Dl_112926_;
extern tyProc_Z3C0z9blaIY9abfEJhIF9b1WQ Dl_120149_;
extern tyProc_32w2ZypAyMWuajvi2Jt79cg Dl_120413_;
TNimType NTI_3GkqZw84cOmRRUHsNmUZKQ_;
extern TNimType NTI_VNjfwc2TWWaPlgYb1NJvkA_;
TNimType NTI_u6eWcr48DqP0Ue9cUPPUypg_;
NIM_CONST tyTuple_0vYzovSm9aKYybyF8MRuBJQ TM_w2y8raIq9a7dDr5q9chSxV1w_2 = {1.0000000000000000e+00,
1.0000000000000000e+00,
1.0000000000000000e+00,
1.0000000000000000e+00}
;
static N_NIMCALL(void, Marker_tyRef_gp9a09azZ9aBufqmUN9aOefMOw)(void* p, NI op) {
	tyObject_CameracolonObjectType__uk8C2BjPELBcegmVYWmD5Q* a;
	a = (tyObject_CameracolonObjectType__uk8C2BjPELBcegmVYWmD5Q*)p;
	nimGCvisit((void*)(*a).Sup.position, op);
	nimGCvisit((void*)(*a).Sup.size, op);
}
static N_NIMCALL(void, TM_w2y8raIq9a7dDr5q9chSxV1w_4)(void) {
	nimGCvisit((void*)camera_gC9bhqCy0IQgaCB9bxtui42g, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(400, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(400, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(400, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(400, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}
static N_NIMCALL(void, Marker_tyRef_0kDVS9b1UyEqr8DfAGXwn9cQ)(void* p, NI op) {
	tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ* a;
	a = (tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ*)p;
}

N_LIB_PRIVATE N_NIMCALL(void, rect_KBJ7sNgV4lSRrRq4ulkq6w)(void* renderer, NF x, NF y, NF w, NF h, NF rot) {
	NF xx;
	NF yy;
	int T1_;
	nimfr_("rect", "art.nim");
	nimln_(141, "art.nim");
	xx = ((NF)(((NF)(x) - (NF)((*(*camera_gC9bhqCy0IQgaCB9bxtui42g).Sup.position).x))) * (NF)((*camera_gC9bhqCy0IQgaCB9bxtui42g).zoom));
	nimln_(142, "art.nim");
	yy = ((NF)(((NF)(y) - (NF)((*(*camera_gC9bhqCy0IQgaCB9bxtui42g).Sup.position).y))) * (NF)((*camera_gC9bhqCy0IQgaCB9bxtui42g).zoom));
	nimln_(143, "art.nim");
	nimln_(145, "art.nim");
	nimln_(146, "art.nim");
	nimln_(147, "art.nim");
	nimln_(148, "art.nim");
	nimln_(149, "art.nim");
	nimln_(150, "art.nim");
	T1_ = (int)0;
	T1_ = Dl_203103_(renderer, ((NI16) (xx)), ((NI16) (yy)), ((NI16) (((NF)(xx) + (NF)(((NF)(w) * (NF)((*camera_gC9bhqCy0IQgaCB9bxtui42g).zoom)))))), ((NI16) (((NF)(yy) + (NF)(((NF)(h) * (NF)((*camera_gC9bhqCy0IQgaCB9bxtui42g).zoom)))))), ((NU8) (((NF)(current_color_ZVKdD8C4l7QMQR2o7qII2A.Field0) * (NF)(2.5500000000000000e+02)))), ((NU8) (((NF)(current_color_ZVKdD8C4l7QMQR2o7qII2A.Field1) * (NF)(2.5500000000000000e+02)))), ((NU8) (((NF)(current_color_ZVKdD8C4l7QMQR2o7qII2A.Field2) * (NF)(2.5500000000000000e+02)))), ((NU8) (((NF)(current_color_ZVKdD8C4l7QMQR2o7qII2A.Field3) * (NF)(2.5500000000000000e+02)))));
	T1_;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Rect_qiXweduDJk1iLE5aHysNdQ, sdlRect_ZAq9cYc7ulNNn21yQGBT79cg)(tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ* r) {
	tyObject_Rect_qiXweduDJk1iLE5aHysNdQ result;
	nimfr_("sdlRect", "art.nim");
{	memset((void*)(&result), 0, sizeof(tyObject_Rect_qiXweduDJk1iLE5aHysNdQ));
	nimln_(38, "art.nim");
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(tyObject_Rect_qiXweduDJk1iLE5aHysNdQ));
	nimln_(39, "art.nim");
	result.x = toCint_yAPwf7d9aO5za0vgIa7yl8g(((NI) ((*(*r).pos).x)));
	nimln_(40, "art.nim");
	result.y = toCint_yAPwf7d9aO5za0vgIa7yl8g(((NI) ((*(*r).pos).y)));
	nimln_(41, "art.nim");
	result.w = toCint_yAPwf7d9aO5za0vgIa7yl8g(((NI) ((*(*r).size).x)));
	nimln_(42, "art.nim");
	result.h = toCint_yAPwf7d9aO5za0vgIa7yl8g(((NI) ((*(*r).size).y)));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, draw_FIJoyt7S8QvQbuv4xQGSGQ)(void* renderer, tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ* obj, tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ* reg, NF x, NF y, NF rot, NIM_BOOL flip, NI ox, NI oy) {
	NIM_BOOL result;
	NF dx;
	NF dy;
	NF dw;
	NF dh;
	tyObject_Rect_qiXweduDJk1iLE5aHysNdQ rect;
	tyObject_Rect_qiXweduDJk1iLE5aHysNdQ sreg;
	tyObject_Point_O882QUBegNwSZhlvLsYQRw pnt;
	nimfr_("draw", "art.nim");
{	result = (NIM_BOOL)0;
	nimln_(121, "art.nim");
	dx = ((NF)(((NF)(x) - (NF)((*(*camera_gC9bhqCy0IQgaCB9bxtui42g).Sup.position).x))) * (NF)((*camera_gC9bhqCy0IQgaCB9bxtui42g).zoom));
	nimln_(122, "art.nim");
	dy = ((NF)(((NF)(y) - (NF)((*(*camera_gC9bhqCy0IQgaCB9bxtui42g).Sup.position).y))) * (NF)((*camera_gC9bhqCy0IQgaCB9bxtui42g).zoom));
	nimln_(123, "art.nim");
	dw = ((NF)((*(*reg).size).x) * (NF)((*camera_gC9bhqCy0IQgaCB9bxtui42g).zoom));
	nimln_(124, "art.nim");
	dh = ((NF)((*(*reg).size).y) * (NF)((*camera_gC9bhqCy0IQgaCB9bxtui42g).zoom));
	nimln_(125, "art.nim");
	chckNil((void*)(&rect));
	memset((void*)(&rect), 0, sizeof(tyObject_Rect_qiXweduDJk1iLE5aHysNdQ));
	rect.x = toCint_yAPwf7d9aO5za0vgIa7yl8g(((NI) (dx)));
	rect.y = toCint_yAPwf7d9aO5za0vgIa7yl8g(((NI) (dy)));
	rect.w = toCint_yAPwf7d9aO5za0vgIa7yl8g(((NI) (dw)));
	rect.h = toCint_yAPwf7d9aO5za0vgIa7yl8g(((NI) (dh)));
	nimln_(126, "art.nim");
	sreg = sdlRect_ZAq9cYc7ulNNn21yQGBT79cg(reg);
	nimln_(127, "art.nim");
	chckNil((void*)(&pnt));
	memset((void*)(&pnt), 0, sizeof(tyObject_Point_O882QUBegNwSZhlvLsYQRw));
	pnt.x = toCint_yAPwf7d9aO5za0vgIa7yl8g(ox);
	pnt.y = toCint_yAPwf7d9aO5za0vgIa7yl8g(oy);
	nimln_(129, "art.nim");
	{
		tyObject_Point_O882QUBegNwSZhlvLsYQRw* T3_;
		tyEnum_RendererFlip_v7zeNYRvzJgcDDS9cEco6wg T11_;
		int T17_;
		T3_ = (tyObject_Point_O882QUBegNwSZhlvLsYQRw*)0;
		nimln_(134, "art.nim");
		{
			NIM_BOOL T6_;
			T6_ = (NIM_BOOL)0;
			T6_ = (ox < ((NI) 0));
			if (T6_) goto LA7_;
			T6_ = (oy < ((NI) 0));
			LA7_: ;
			if (!T6_) goto LA8_;
			T3_ = NIM_NIL;
		}
		goto LA4_;
		LA8_: ;
		{
			T3_ = (&pnt);
		}
		LA4_: ;
		T11_ = (tyEnum_RendererFlip_v7zeNYRvzJgcDDS9cEco6wg)0;
		nimln_(135, "art.nim");
		{
			if (!flip) goto LA14_;
			T11_ = ((tyEnum_RendererFlip_v7zeNYRvzJgcDDS9cEco6wg) 1);
		}
		goto LA12_;
		LA14_: ;
		{
			T11_ = ((tyEnum_RendererFlip_v7zeNYRvzJgcDDS9cEco6wg) 0);
		}
		LA12_: ;
		T17_ = (int)0;
		T17_ = Dl_120390_(renderer, (*obj).texture, (&sreg), (&rect), rot, T3_, T11_);
		if (!(T17_ == ((NI32) 0))) goto LA18_;
		nimln_(136, "art.nim");
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	goto LA1_;
	LA18_: ;
	{
		nimln_(138, "art.nim");
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, setColor_7k69cwHLgkJ9bCcjBZQtbbsg)(void* renderer, tyTuple_0vYzovSm9aKYybyF8MRuBJQ* c) {
	nimfr_("setColor", "art.nim");
	nimln_(100, "art.nim");
	current_color_ZVKdD8C4l7QMQR2o7qII2A = (*c);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, lineRect_KBJ7sNgV4lSRrRq4ulkq6w_2)(void* renderer, NF x, NF y, NF w, NF h, NF rot) {
	NF xx;
	NF yy;
	int T1_;
	nimfr_("lineRect", "art.nim");
	nimln_(154, "art.nim");
	xx = ((NF)(((NF)(x) - (NF)((*(*camera_gC9bhqCy0IQgaCB9bxtui42g).Sup.position).x))) * (NF)((*camera_gC9bhqCy0IQgaCB9bxtui42g).zoom));
	nimln_(155, "art.nim");
	yy = ((NF)(((NF)(y) - (NF)((*(*camera_gC9bhqCy0IQgaCB9bxtui42g).Sup.position).y))) * (NF)((*camera_gC9bhqCy0IQgaCB9bxtui42g).zoom));
	nimln_(156, "art.nim");
	nimln_(158, "art.nim");
	nimln_(159, "art.nim");
	nimln_(160, "art.nim");
	nimln_(161, "art.nim");
	nimln_(162, "art.nim");
	nimln_(163, "art.nim");
	T1_ = (int)0;
	T1_ = Dl_203063_(renderer, ((NI16) (xx)), ((NI16) (yy)), ((NI16) (((NF)(xx) + (NF)(((NF)(w) * (NF)((*camera_gC9bhqCy0IQgaCB9bxtui42g).zoom)))))), ((NI16) (((NF)(yy) + (NF)(((NF)(h) * (NF)((*camera_gC9bhqCy0IQgaCB9bxtui42g).zoom)))))), ((NU8) (((NF)(current_color_ZVKdD8C4l7QMQR2o7qII2A.Field0) * (NF)(2.5500000000000000e+02)))), ((NU8) (((NF)(current_color_ZVKdD8C4l7QMQR2o7qII2A.Field1) * (NF)(2.5500000000000000e+02)))), ((NU8) (((NF)(current_color_ZVKdD8C4l7QMQR2o7qII2A.Field2) * (NF)(2.5500000000000000e+02)))), ((NU8) (((NF)(current_color_ZVKdD8C4l7QMQR2o7qII2A.Field3) * (NF)(2.5500000000000000e+02)))));
	T1_;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ*, newImage_tWxVwZ28d3tVcmFKmMn6ag)(void) {
	tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ* result;
	tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ* T1_;
	nimfr_("newImage", "art.nim");
	result = (tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ*)0;
	nimln_(46, "art.nim");
	T1_ = (tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ*)0;
	T1_ = (tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ*) newObj((&NTI_0kDVS9b1UyEqr8DfAGXwn9cQ_), sizeof(tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ));
	(*T1_).Sup.m_type = (&NTI_CILs0aI9a15OLIJJawRpwrQ_);
	(*T1_).texture = NIM_NIL;
	(*T1_).w = ((NI) 0);
	(*T1_).h = ((NI) 0);
	result = T1_;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, load_HwT5E7mbKGCJy0HINVoqrA)(tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ* obj, void* renderer, NimStringDesc* file) {
	NIM_BOOL result;
	void** T1_;
	int w;
	int h;
	nimfr_("load", "art.nim");
{	result = (NIM_BOOL)0;
	nimln_(54, "art.nim");
	result = NIM_TRUE;
	nimln_(56, "art.nim");
	T1_ = (void**)0;
	T1_ = Dl_202060_(renderer, (file ? file->data : (NCSTRING)""));
	(*obj).texture = ((void*) (T1_));
	nimln_(57, "art.nim");
	{
		NCSTRING T6_;
		if (!((*obj).texture == NIM_NIL)) goto LA4_;
		nimln_(58, "art.nim");
		nimln_(60, "art.nim");
		T6_ = (NCSTRING)0;
		T6_ = Dl_112926_();
		Dl_119881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Can\'t load image %s: %s", (file ? file->data : (NCSTRING)""), T6_);
		nimln_(61, "art.nim");
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA4_: ;
	w = (int)0;
	h = (int)0;
	nimln_(64, "art.nim");
	{
		int T9_;
		NCSTRING T12_;
		nimln_(400, "system.nim");
		nimln_(64, "art.nim");
		T9_ = (int)0;
		T9_ = Dl_120149_((*obj).texture, NIM_NIL, NIM_NIL, (&w), (&h));
		if (!!((T9_ == ((NI32) 0)))) goto LA10_;
		nimln_(65, "art.nim");
		nimln_(67, "art.nim");
		T12_ = (NCSTRING)0;
		T12_ = Dl_112926_();
		Dl_119881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Can\'t get texture attributes: %s", T12_);
		nimln_(68, "art.nim");
		Dl_120413_((*obj).texture);
		nimln_(69, "art.nim");
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA10_: ;
	nimln_(70, "art.nim");
	(*obj).w = ((NI) (w));
	nimln_(71, "art.nim");
	(*obj).h = ((NI) (h));
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ*, loadImage_9cSn2Oei09cy2uR1CShK9ccUg)(void* renderer, NimStringDesc* path) {
	tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ* result;
	NIM_BOOL T1_;
	nimfr_("loadImage", "art.nim");
	result = (tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ*)0;
	nimln_(74, "art.nim");
	result = newImage_tWxVwZ28d3tVcmFKmMn6ag();
	nimln_(75, "art.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = load_HwT5E7mbKGCJy0HINVoqrA(result, renderer, path);
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_u6eWcr48DqP0Ue9cUPPUypg)(void* p, NI op) {
	tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ* a;
	a = (tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ*)p;
	nimGCvisit((void*)(*a).pos, op);
	nimGCvisit((void*)(*a).size, op);
}

N_LIB_PRIVATE N_NIMCALL(tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ*, newRegion_cDYOp69b9cgybAh72RRtrTXw)(NF x, NF y, NF w, NF h) {
	tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ* result;
	tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ* T1_;
	nimfr_("newRegion", "art.nim");
	result = (tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ*)0;
	nimln_(24, "art.nim");
	T1_ = (tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ*)0;
	T1_ = (tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ*) newObj((&NTI_u6eWcr48DqP0Ue9cUPPUypg_), sizeof(tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ));
	(*T1_).Sup.m_type = (&NTI_3GkqZw84cOmRRUHsNmUZKQ_);
	nimln_(25, "art.nim");
	asgnRefNoCycle((void**) (&(*T1_).pos), Vec2_FI9b5IBktnCnUUYt6xN1b2g(x, y));
	nimln_(26, "art.nim");
	asgnRefNoCycle((void**) (&(*T1_).size), Vec2_FI9b5IBktnCnUUYt6xN1b2g(w, h));
	result = T1_;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, VectorGuy_artInit000)(void) {
	tyObject_CameracolonObjectType__uk8C2BjPELBcegmVYWmD5Q* T1_;
	nimfr_("art", "art.nim");
nimRegisterGlobalMarker(TM_w2y8raIq9a7dDr5q9chSxV1w_4);
	nimln_(21, "art.nim");
	current_color_ZVKdD8C4l7QMQR2o7qII2A = TM_w2y8raIq9a7dDr5q9chSxV1w_2;
	nimln_(30, "art.nim");
	T1_ = (tyObject_CameracolonObjectType__uk8C2BjPELBcegmVYWmD5Q*)0;
	T1_ = (tyObject_CameracolonObjectType__uk8C2BjPELBcegmVYWmD5Q*) newObj((&NTI_gp9a09azZ9aBufqmUN9aOefMOw_), sizeof(tyObject_CameracolonObjectType__uk8C2BjPELBcegmVYWmD5Q));
	(*T1_).Sup.Sup.Sup.m_type = (&NTI_uk8C2BjPELBcegmVYWmD5Q_);
	nimln_(5, "maths.nim");
	asgnRefNoCycle((void**) (&(*T1_).Sup.position), Vec2_FI9b5IBktnCnUUYt6xN1b2g(0.0, 0.0));
	asgnRefNoCycle((void**) (&(*T1_).Sup.size), Vec2_FI9b5IBktnCnUUYt6xN1b2g(0.0, 0.0));
	(*T1_).zoom = 1.0000000000000000e+00;
	(*T1_).rotation = 0.0;
	asgnRef((void**) (&camera_gC9bhqCy0IQgaCB9bxtui42g), T1_);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, VectorGuy_artDatInit000)(void) {
static TNimNode* TM_w2y8raIq9a7dDr5q9chSxV1w_3[2];
static TNimNode* TM_w2y8raIq9a7dDr5q9chSxV1w_5[3];
static TNimNode* TM_w2y8raIq9a7dDr5q9chSxV1w_6[2];
static TNimNode TM_w2y8raIq9a7dDr5q9chSxV1w_0[10];
NTI_uk8C2BjPELBcegmVYWmD5Q_.size = sizeof(tyObject_CameracolonObjectType__uk8C2BjPELBcegmVYWmD5Q);
NTI_uk8C2BjPELBcegmVYWmD5Q_.kind = 17;
NTI_uk8C2BjPELBcegmVYWmD5Q_.base = (&NTI_gcAPnvgqasHnAwLl6W9cWFQ_);
TM_w2y8raIq9a7dDr5q9chSxV1w_3[0] = &TM_w2y8raIq9a7dDr5q9chSxV1w_0[1];
TM_w2y8raIq9a7dDr5q9chSxV1w_0[1].kind = 1;
TM_w2y8raIq9a7dDr5q9chSxV1w_0[1].offset = offsetof(tyObject_CameracolonObjectType__uk8C2BjPELBcegmVYWmD5Q, zoom);
TM_w2y8raIq9a7dDr5q9chSxV1w_0[1].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_w2y8raIq9a7dDr5q9chSxV1w_0[1].name = "zoom";
TM_w2y8raIq9a7dDr5q9chSxV1w_3[1] = &TM_w2y8raIq9a7dDr5q9chSxV1w_0[2];
TM_w2y8raIq9a7dDr5q9chSxV1w_0[2].kind = 1;
TM_w2y8raIq9a7dDr5q9chSxV1w_0[2].offset = offsetof(tyObject_CameracolonObjectType__uk8C2BjPELBcegmVYWmD5Q, rotation);
TM_w2y8raIq9a7dDr5q9chSxV1w_0[2].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_w2y8raIq9a7dDr5q9chSxV1w_0[2].name = "rotation";
TM_w2y8raIq9a7dDr5q9chSxV1w_0[0].len = 2; TM_w2y8raIq9a7dDr5q9chSxV1w_0[0].kind = 2; TM_w2y8raIq9a7dDr5q9chSxV1w_0[0].sons = &TM_w2y8raIq9a7dDr5q9chSxV1w_3[0];
NTI_uk8C2BjPELBcegmVYWmD5Q_.node = &TM_w2y8raIq9a7dDr5q9chSxV1w_0[0];
NTI_gp9a09azZ9aBufqmUN9aOefMOw_.size = sizeof(tyObject_CameracolonObjectType__uk8C2BjPELBcegmVYWmD5Q*);
NTI_gp9a09azZ9aBufqmUN9aOefMOw_.kind = 22;
NTI_gp9a09azZ9aBufqmUN9aOefMOw_.base = (&NTI_uk8C2BjPELBcegmVYWmD5Q_);
NTI_gp9a09azZ9aBufqmUN9aOefMOw_.marker = Marker_tyRef_gp9a09azZ9aBufqmUN9aOefMOw;
NTI_CILs0aI9a15OLIJJawRpwrQ_.size = sizeof(tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ);
NTI_CILs0aI9a15OLIJJawRpwrQ_.kind = 17;
NTI_CILs0aI9a15OLIJJawRpwrQ_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_CILs0aI9a15OLIJJawRpwrQ_.flags = 1;
TM_w2y8raIq9a7dDr5q9chSxV1w_5[0] = &TM_w2y8raIq9a7dDr5q9chSxV1w_0[4];
TM_w2y8raIq9a7dDr5q9chSxV1w_0[4].kind = 1;
TM_w2y8raIq9a7dDr5q9chSxV1w_0[4].offset = offsetof(tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ, texture);
TM_w2y8raIq9a7dDr5q9chSxV1w_0[4].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_w2y8raIq9a7dDr5q9chSxV1w_0[4].name = "texture";
TM_w2y8raIq9a7dDr5q9chSxV1w_5[1] = &TM_w2y8raIq9a7dDr5q9chSxV1w_0[5];
TM_w2y8raIq9a7dDr5q9chSxV1w_0[5].kind = 1;
TM_w2y8raIq9a7dDr5q9chSxV1w_0[5].offset = offsetof(tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ, w);
TM_w2y8raIq9a7dDr5q9chSxV1w_0[5].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_w2y8raIq9a7dDr5q9chSxV1w_0[5].name = "w";
TM_w2y8raIq9a7dDr5q9chSxV1w_5[2] = &TM_w2y8raIq9a7dDr5q9chSxV1w_0[6];
TM_w2y8raIq9a7dDr5q9chSxV1w_0[6].kind = 1;
TM_w2y8raIq9a7dDr5q9chSxV1w_0[6].offset = offsetof(tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ, h);
TM_w2y8raIq9a7dDr5q9chSxV1w_0[6].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_w2y8raIq9a7dDr5q9chSxV1w_0[6].name = "h";
TM_w2y8raIq9a7dDr5q9chSxV1w_0[3].len = 3; TM_w2y8raIq9a7dDr5q9chSxV1w_0[3].kind = 2; TM_w2y8raIq9a7dDr5q9chSxV1w_0[3].sons = &TM_w2y8raIq9a7dDr5q9chSxV1w_5[0];
NTI_CILs0aI9a15OLIJJawRpwrQ_.node = &TM_w2y8raIq9a7dDr5q9chSxV1w_0[3];
NTI_0kDVS9b1UyEqr8DfAGXwn9cQ_.size = sizeof(tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ*);
NTI_0kDVS9b1UyEqr8DfAGXwn9cQ_.kind = 22;
NTI_0kDVS9b1UyEqr8DfAGXwn9cQ_.base = (&NTI_CILs0aI9a15OLIJJawRpwrQ_);
NTI_0kDVS9b1UyEqr8DfAGXwn9cQ_.marker = Marker_tyRef_0kDVS9b1UyEqr8DfAGXwn9cQ;
NTI_3GkqZw84cOmRRUHsNmUZKQ_.size = sizeof(tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ);
NTI_3GkqZw84cOmRRUHsNmUZKQ_.kind = 17;
NTI_3GkqZw84cOmRRUHsNmUZKQ_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_w2y8raIq9a7dDr5q9chSxV1w_6[0] = &TM_w2y8raIq9a7dDr5q9chSxV1w_0[8];
TM_w2y8raIq9a7dDr5q9chSxV1w_0[8].kind = 1;
TM_w2y8raIq9a7dDr5q9chSxV1w_0[8].offset = offsetof(tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ, pos);
TM_w2y8raIq9a7dDr5q9chSxV1w_0[8].typ = (&NTI_VNjfwc2TWWaPlgYb1NJvkA_);
TM_w2y8raIq9a7dDr5q9chSxV1w_0[8].name = "pos";
TM_w2y8raIq9a7dDr5q9chSxV1w_6[1] = &TM_w2y8raIq9a7dDr5q9chSxV1w_0[9];
TM_w2y8raIq9a7dDr5q9chSxV1w_0[9].kind = 1;
TM_w2y8raIq9a7dDr5q9chSxV1w_0[9].offset = offsetof(tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ, size);
TM_w2y8raIq9a7dDr5q9chSxV1w_0[9].typ = (&NTI_VNjfwc2TWWaPlgYb1NJvkA_);
TM_w2y8raIq9a7dDr5q9chSxV1w_0[9].name = "size";
TM_w2y8raIq9a7dDr5q9chSxV1w_0[7].len = 2; TM_w2y8raIq9a7dDr5q9chSxV1w_0[7].kind = 2; TM_w2y8raIq9a7dDr5q9chSxV1w_0[7].sons = &TM_w2y8raIq9a7dDr5q9chSxV1w_6[0];
NTI_3GkqZw84cOmRRUHsNmUZKQ_.node = &TM_w2y8raIq9a7dDr5q9chSxV1w_0[7];
NTI_u6eWcr48DqP0Ue9cUPPUypg_.size = sizeof(tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ*);
NTI_u6eWcr48DqP0Ue9cUPPUypg_.kind = 22;
NTI_u6eWcr48DqP0Ue9cUPPUypg_.base = (&NTI_3GkqZw84cOmRRUHsNmUZKQ_);
NTI_u6eWcr48DqP0Ue9cUPPUypg_.marker = Marker_tyRef_u6eWcr48DqP0Ue9cUPPUypg;
}

