/* Generated by Nim Compiler v0.18.1 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/dustin/Documents/Nim/lib -o /home/dustin/Documents/Nim_Projects/VectorGuy/src/nimcache/VectorGuy_body.o /home/dustin/Documents/Nim_Projects/VectorGuy/src/nimcache/VectorGuy_body.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ;
typedef struct tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ;
typedef struct RootObj RootObj;
typedef struct tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ {
  RootObj Sup;
};
struct tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ {
  tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ Sup;
tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ* position;
tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ* size;
};
struct tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ {
NF x;
NF y;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_GCYPzEuORgT0uFEDMK3Fjg)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ*, Vec2_FI9b5IBktnCnUUYt6xN1b2g)(NF x, NF y);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(NF, x_GjB2bcom6jNDdYSzGflP3w)(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* b);
N_LIB_PRIVATE N_NIMCALL(NF, width_GjB2bcom6jNDdYSzGflP3w_3)(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* b);
N_LIB_PRIVATE N_NIMCALL(NF, y_GjB2bcom6jNDdYSzGflP3w_2)(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* b);
N_LIB_PRIVATE N_NIMCALL(NF, height_GjB2bcom6jNDdYSzGflP3w_4)(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* b);
extern TNimType NTI_X8aacFQVnMMG3eJMkbZvPQ_;
TNimType NTI_gcAPnvgqasHnAwLl6W9cWFQ_;
extern TNimType NTI_VNjfwc2TWWaPlgYb1NJvkA_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_GCYPzEuORgT0uFEDMK3Fjg_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NF, x_GjB2bcom6jNDdYSzGflP3w)(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* b) {
	NF result;
	nimfr_("x", "body.nim");
	result = (NF)0;
	nimln_(15, "body.nim");
	result = (*(*b).position).x;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NF, y_GjB2bcom6jNDdYSzGflP3w_2)(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* b) {
	NF result;
	nimfr_("y", "body.nim");
	result = (NF)0;
	nimln_(18, "body.nim");
	result = (*(*b).position).y;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NF, width_GjB2bcom6jNDdYSzGflP3w_3)(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* b) {
	NF result;
	nimfr_("width", "body.nim");
	result = (NF)0;
	nimln_(21, "body.nim");
	result = (*(*b).size).x;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NF, height_GjB2bcom6jNDdYSzGflP3w_4)(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* b) {
	NF result;
	nimfr_("height", "body.nim");
	result = (NF)0;
	nimln_(24, "body.nim");
	result = (*(*b).size).y;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_GCYPzEuORgT0uFEDMK3Fjg)(void* p, NI op) {
	tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* a;
	a = (tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ*)p;
	nimGCvisit((void*)(*a).position, op);
	nimGCvisit((void*)(*a).size, op);
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(400, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(400, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ*, newBody_YdK5PiZ0UtDMK9bV5MRaKMw)(NF x, NF y, NF w, NF h) {
	tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* result;
	tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* T1_;
	nimfr_("newBody", "body.nim");
	result = (tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ*)0;
	nimln_(10, "body.nim");
	T1_ = (tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ*)0;
	T1_ = (tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ*) newObj((&NTI_GCYPzEuORgT0uFEDMK3Fjg_), sizeof(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ));
	(*T1_).Sup.Sup.m_type = (&NTI_gcAPnvgqasHnAwLl6W9cWFQ_);
	nimln_(11, "body.nim");
	asgnRefNoCycle((void**) (&(*T1_).position), Vec2_FI9b5IBktnCnUUYt6xN1b2g(x, y));
	nimln_(12, "body.nim");
	asgnRefNoCycle((void**) (&(*T1_).size), Vec2_FI9b5IBktnCnUUYt6xN1b2g(w, h));
	result = T1_;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_Ao31NV5U6r2d7xZ2tFJkvQ)(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* body, tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* other) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NIM_BOOL T2_;
	NIM_BOOL T3_;
	NF T4_;
	NF T5_;
	NF T6_;
	NF T8_;
	NF T9_;
	NF T10_;
	NF T12_;
	NF T13_;
	NF T14_;
	NF T16_;
	NF T17_;
	NF T18_;
	nimfr_("contains", "body.nim");
{	result = (NIM_BOOL)0;
	nimln_(33, "body.nim");
	nimln_(34, "body.nim");
	T1_ = (NIM_BOOL)0;
	nimln_(33, "body.nim");
	T2_ = (NIM_BOOL)0;
	T3_ = (NIM_BOOL)0;
	T4_ = (NF)0;
	T4_ = x_GjB2bcom6jNDdYSzGflP3w(other);
	T5_ = (NF)0;
	T5_ = x_GjB2bcom6jNDdYSzGflP3w(body);
	T6_ = (NF)0;
	T6_ = width_GjB2bcom6jNDdYSzGflP3w_3(body);
	T3_ = (T4_ < ((NF)(T5_) + (NF)(T6_)));
	if (!(T3_)) goto LA7_;
	nimln_(34, "body.nim");
	T8_ = (NF)0;
	T8_ = x_GjB2bcom6jNDdYSzGflP3w(body);
	T9_ = (NF)0;
	T9_ = x_GjB2bcom6jNDdYSzGflP3w(other);
	T10_ = (NF)0;
	T10_ = width_GjB2bcom6jNDdYSzGflP3w_3(other);
	T3_ = (T8_ < ((NF)(T9_) + (NF)(T10_)));
	LA7_: ;
	T2_ = T3_;
	if (!(T2_)) goto LA11_;
	nimln_(35, "body.nim");
	T12_ = (NF)0;
	T12_ = y_GjB2bcom6jNDdYSzGflP3w_2(other);
	T13_ = (NF)0;
	T13_ = y_GjB2bcom6jNDdYSzGflP3w_2(body);
	T14_ = (NF)0;
	T14_ = height_GjB2bcom6jNDdYSzGflP3w_4(body);
	T2_ = (T12_ < ((NF)(T13_) + (NF)(T14_)));
	LA11_: ;
	T1_ = T2_;
	if (!(T1_)) goto LA15_;
	nimln_(36, "body.nim");
	T16_ = (NF)0;
	T16_ = y_GjB2bcom6jNDdYSzGflP3w_2(body);
	T17_ = (NF)0;
	T17_ = y_GjB2bcom6jNDdYSzGflP3w_2(other);
	T18_ = (NF)0;
	T18_ = height_GjB2bcom6jNDdYSzGflP3w_4(other);
	T1_ = (T16_ < ((NF)(T17_) + (NF)(T18_)));
	LA15_: ;
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, yeq__DN6TRc8PZDWh9aCsDxc7MoQ)(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* b, NF v) {
	nimfr_("y=", "body.nim");
	nimln_(19, "body.nim");
	(*(*b).position).y = v;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_C6FI9aMdOHjeL7OzSk2HFGg)(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* body, tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ* other) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NIM_BOOL T2_;
	NIM_BOOL T3_;
	NF T4_;
	NF T6_;
	NF T7_;
	NF T9_;
	NF T11_;
	NF T12_;
	nimfr_("contains", "body.nim");
{	result = (NIM_BOOL)0;
	nimln_(39, "body.nim");
	T1_ = (NIM_BOOL)0;
	T2_ = (NIM_BOOL)0;
	T3_ = (NIM_BOOL)0;
	T4_ = (NF)0;
	T4_ = x_GjB2bcom6jNDdYSzGflP3w(body);
	T3_ = (T4_ < (*other).x);
	if (!(T3_)) goto LA5_;
	T6_ = (NF)0;
	T6_ = x_GjB2bcom6jNDdYSzGflP3w(body);
	T7_ = (NF)0;
	T7_ = width_GjB2bcom6jNDdYSzGflP3w_3(body);
	T3_ = ((*other).x < ((NF)(T6_) + (NF)(T7_)));
	LA5_: ;
	T2_ = T3_;
	if (!(T2_)) goto LA8_;
	nimln_(40, "body.nim");
	T9_ = (NF)0;
	T9_ = y_GjB2bcom6jNDdYSzGflP3w_2(body);
	T2_ = (T9_ < (*other).y);
	LA8_: ;
	T1_ = T2_;
	if (!(T1_)) goto LA10_;
	T11_ = (NF)0;
	T11_ = y_GjB2bcom6jNDdYSzGflP3w_2(body);
	T12_ = (NF)0;
	T12_ = height_GjB2bcom6jNDdYSzGflP3w_4(body);
	T1_ = ((*other).y < ((NF)(T11_) + (NF)(T12_)));
	LA10_: ;
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, VectorGuy_bodyInit000)(void) {
	nimfr_("body", "body.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, VectorGuy_bodyDatInit000)(void) {
static TNimNode* TM_ZrCYDN9cZTt9a4wix9aR80mag_2[2];
static TNimNode TM_ZrCYDN9cZTt9a4wix9aR80mag_0[3];
NTI_gcAPnvgqasHnAwLl6W9cWFQ_.size = sizeof(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ);
NTI_gcAPnvgqasHnAwLl6W9cWFQ_.kind = 17;
NTI_gcAPnvgqasHnAwLl6W9cWFQ_.base = (&NTI_X8aacFQVnMMG3eJMkbZvPQ_);
TM_ZrCYDN9cZTt9a4wix9aR80mag_2[0] = &TM_ZrCYDN9cZTt9a4wix9aR80mag_0[1];
TM_ZrCYDN9cZTt9a4wix9aR80mag_0[1].kind = 1;
TM_ZrCYDN9cZTt9a4wix9aR80mag_0[1].offset = offsetof(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ, position);
TM_ZrCYDN9cZTt9a4wix9aR80mag_0[1].typ = (&NTI_VNjfwc2TWWaPlgYb1NJvkA_);
TM_ZrCYDN9cZTt9a4wix9aR80mag_0[1].name = "position";
TM_ZrCYDN9cZTt9a4wix9aR80mag_2[1] = &TM_ZrCYDN9cZTt9a4wix9aR80mag_0[2];
TM_ZrCYDN9cZTt9a4wix9aR80mag_0[2].kind = 1;
TM_ZrCYDN9cZTt9a4wix9aR80mag_0[2].offset = offsetof(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ, size);
TM_ZrCYDN9cZTt9a4wix9aR80mag_0[2].typ = (&NTI_VNjfwc2TWWaPlgYb1NJvkA_);
TM_ZrCYDN9cZTt9a4wix9aR80mag_0[2].name = "size";
TM_ZrCYDN9cZTt9a4wix9aR80mag_0[0].len = 2; TM_ZrCYDN9cZTt9a4wix9aR80mag_0[0].kind = 2; TM_ZrCYDN9cZTt9a4wix9aR80mag_0[0].sons = &TM_ZrCYDN9cZTt9a4wix9aR80mag_2[0];
NTI_gcAPnvgqasHnAwLl6W9cWFQ_.node = &TM_ZrCYDN9cZTt9a4wix9aR80mag_0[0];
NTI_GCYPzEuORgT0uFEDMK3Fjg_.size = sizeof(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ*);
NTI_GCYPzEuORgT0uFEDMK3Fjg_.kind = 22;
NTI_GCYPzEuORgT0uFEDMK3Fjg_.base = (&NTI_gcAPnvgqasHnAwLl6W9cWFQ_);
NTI_GCYPzEuORgT0uFEDMK3Fjg_.marker = Marker_tyRef_GCYPzEuORgT0uFEDMK3Fjg;
}

