/* Generated by Nim Compiler v0.18.1 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/dustin/Documents/Nim/lib -o /home/dustin/Documents/Nim_Projects/VectorGuy/src/nimcache/VectorGuy_ecs.o /home/dustin/Documents/Nim_Projects/VectorGuy/src/nimcache/VectorGuy_ecs.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg;
typedef struct tySequence_sxV7BWZ9cww0pVdm9bqsswoA tySequence_sxV7BWZ9cww0pVdm9bqsswoA;
typedef struct tySequence_siX5xEDqFuO4i5rOs7ZBlg tySequence_siX5xEDqFuO4i5rOs7ZBlg;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g;
typedef struct tyObject_Table_9ab5RwcLehRlj0xrxSya29cQ tyObject_Table_9ab5RwcLehRlj0xrxSya29cQ;
typedef struct tySequence_Z6EPM1KZna9bOdQQSPicLog tySequence_Z6EPM1KZna9bOdQQSPicLog;
typedef struct tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ;
typedef struct RootObj RootObj;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyTuple_2uzTbg8jwom7zHhmM2RgHg tyTuple_2uzTbg8jwom7zHhmM2RgHg;
typedef struct tyObject_Env_ecsdotnim__sO5O0Qy9bzKs0atwA6HUBAw tyObject_Env_ecsdotnim__sO5O0Qy9bzKs0atwA6HUBAw;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ;
typedef struct tyObject_RectangleComponentcolonObjectType__Td9aXtPuWzNdKHrUL9cPq5lQ tyObject_RectangleComponentcolonObjectType__Td9aXtPuWzNdKHrUL9cPq5lQ;
typedef struct tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A;
typedef struct tyObject_PhysicsBodycolonObjectType__qOCpO56KLJz1SFjXu8FuZw tyObject_PhysicsBodycolonObjectType__qOCpO56KLJz1SFjXu8FuZw;
typedef struct tyObject_EnemycolonObjectType__6wQJK6c5zRekZO1fQWX9cZw tyObject_EnemycolonObjectType__6wQJK6c5zRekZO1fQWX9cZw;
typedef struct tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ;
typedef struct tyObject_PhysicsObjectcolonObjectType__pT1SYs16c4VQPrPWuA2cJA tyObject_PhysicsObjectcolonObjectType__pT1SYs16c4VQPrPWuA2cJA;
typedef struct tyObject_DrawablecolonObjectType__2ltTHdgBChx9cgtqnSkskXA tyObject_DrawablecolonObjectType__2ltTHdgBChx9cgtqnSkskXA;
typedef struct tyTuple_0vYzovSm9aKYybyF8MRuBJQ tyTuple_0vYzovSm9aKYybyF8MRuBJQ;
typedef struct tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ;
typedef struct tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ;
typedef struct tyObject_PlayercolonObjectType__XT8bNNou1LsCIl1jlU5CFQ tyObject_PlayercolonObjectType__XT8bNNou1LsCIl1jlU5CFQ;
typedef struct tyObject_ItemcolonObjectType__WUdDRZlHK9bEhTn4Z7eJDew tyObject_ItemcolonObjectType__WUdDRZlHK9bEhTn4Z7eJDew;
typedef struct tyTuple_uV7uOjoBWpdM9aITa7Msz0A tyTuple_uV7uOjoBWpdM9aITa7Msz0A;
struct tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg {
tySequence_sxV7BWZ9cww0pVdm9bqsswoA* entities;
tySequence_siX5xEDqFuO4i5rOs7ZBlg* systems;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct tyObject_Table_9ab5RwcLehRlj0xrxSya29cQ {
tySequence_Z6EPM1KZna9bOdQQSPicLog* data;
NI counter;
};
struct tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g {
NIM_BOOL loaded;
NIM_BOOL remove;
tyObject_Table_9ab5RwcLehRlj0xrxSya29cQ components;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ {
  RootObj Sup;
};
struct TGenericSeq {
NI len;
NI reserved;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, void* ClE_0);
void* ClE_0;
} tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e, void* ClE_0);
void* ClE_0;
} tyProc_LTibXkW8wgZIS6uZJDSRwg;
struct tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw {
tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg* worldRef;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* matchList;
tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ preUpdate;
tyProc_LTibXkW8wgZIS6uZJDSRwg load;
tyProc_LTibXkW8wgZIS6uZJDSRwg update;
tyProc_LTibXkW8wgZIS6uZJDSRwg draw;
tyProc_LTibXkW8wgZIS6uZJDSRwg destroy;
tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ preDraw;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyTuple_2uzTbg8jwom7zHhmM2RgHg {
void* Field0;
tyObject_Env_ecsdotnim__sO5O0Qy9bzKs0atwA6HUBAw* Field1;
};
struct tyObject_Env_ecsdotnim__sO5O0Qy9bzKs0atwA6HUBAw {
  RootObj Sup;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NimStringDesc* tyArray_9c1pQHm5qJ9cE1a5EAUkfPIQ[1];
struct tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ {
  tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ Sup;
tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ* position;
tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ* size;
};
typedef NU8 tyEnum_PhysicsType_JOO6TjZ3B9bNSHGgTMd9cP9aQ;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_PhysicsObjectcolonObjectType__pT1SYs16c4VQPrPWuA2cJA* solid, void* ClE_0);
void* ClE_0;
} tyProc_yA6KJnbz0A2EaGKKnqdODw;
struct tyObject_PhysicsBodycolonObjectType__qOCpO56KLJz1SFjXu8FuZw {
  tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ Sup;
tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ* velocity;
NF friction;
NIM_BOOL isOnGround;
NIM_BOOL isOnLadder;
NF gravity_scale;
tyEnum_PhysicsType_JOO6TjZ3B9bNSHGgTMd9cP9aQ physicsType;
tySequence_sxV7BWZ9cww0pVdm9bqsswoA* collisions;
tyProc_yA6KJnbz0A2EaGKKnqdODw solidsCollisionCallback;
};
struct tyTuple_0vYzovSm9aKYybyF8MRuBJQ {
NF Field0;
NF Field1;
NF Field2;
NF Field3;
};
struct tyObject_DrawablecolonObjectType__2ltTHdgBChx9cgtqnSkskXA {
  tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ Sup;
tyTuple_0vYzovSm9aKYybyF8MRuBJQ color;
tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ* offset;
NF rotation;
};
struct tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A {
  tyObject_DrawablecolonObjectType__2ltTHdgBChx9cgtqnSkskXA Sup;
tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ* image;
tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ* region;
NIM_BOOL flip;
};
struct tyObject_PlayercolonObjectType__XT8bNNou1LsCIl1jlU5CFQ {
  tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ Sup;
};
typedef NU8 tyEnum_EnemyType_jYCTX9b0JJHEzvUfb9byI9ayw;
struct tyObject_EnemycolonObjectType__6wQJK6c5zRekZO1fQWX9cZw {
  tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ Sup;
tyEnum_EnemyType_jYCTX9b0JJHEzvUfb9byI9ayw enemyType;
};
struct tyObject_ItemcolonObjectType__WUdDRZlHK9bEhTn4Z7eJDew {
  tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ Sup;
};
typedef N_CLOSURE_PTR(void, TM_rwLMXCJFajv59bjeX5ComAQ_25) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s);
typedef N_CLOSURE_PTR(void, TM_rwLMXCJFajv59bjeX5ComAQ_29) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e);
typedef N_CLOSURE_PTR(void, TM_rwLMXCJFajv59bjeX5ComAQ_30) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e);
typedef N_CLOSURE_PTR(void, TM_rwLMXCJFajv59bjeX5ComAQ_32) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e);
typedef N_CLOSURE_PTR(void, TM_rwLMXCJFajv59bjeX5ComAQ_35) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s);
typedef N_CLOSURE_PTR(void, TM_rwLMXCJFajv59bjeX5ComAQ_37) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e);
struct tyTuple_uV7uOjoBWpdM9aITa7Msz0A {
NI Field0;
NimStringDesc* Field1;
tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ* Field2;
};
struct tySequence_sxV7BWZ9cww0pVdm9bqsswoA {
  TGenericSeq Sup;
  tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* data[SEQ_DECL_SIZE];
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_siX5xEDqFuO4i5rOs7ZBlg {
  TGenericSeq Sup;
  tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* data[SEQ_DECL_SIZE];
};
struct tySequence_Z6EPM1KZna9bOdQQSPicLog {
  TGenericSeq Sup;
  tyTuple_uV7uOjoBWpdM9aITa7Msz0A data[SEQ_DECL_SIZE];
};
static N_NIMCALL(void, Marker_tyRef_uy40IH3avHBB9chAP6wAq9bg)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_R9b3hfapA2py1I4YfWk0zBA)(void* p, NI op);
static N_NIMCALL(void, Marker_tySequence_sxV7BWZ9cww0pVdm9bqsswoA)(void* p, NI op);
static N_NIMCALL(void, Marker_tySequence_sM4lkSb7zS6F7OVMvW9cffQ)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_58EFneeS9at7cA541QCoGAw)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_kqRkyKwWUGhRwkJfLvzABw)(void* p, NI op);
static N_NIMCALL(void, Marker_tySequence_siX5xEDqFuO4i5rOs7ZBlg)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_kFs8aoCoWWyGs19aEbPaOUg)(void* p, NI op);
static N_NIMCALL(void, TM_rwLMXCJFajv59bjeX5ComAQ_7)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_LIB_PRIVATE N_NIMCALL(tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg*, newWorld_c0qJWgzks2BMeljz9c19cp3Q)(void);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(tySequence_sxV7BWZ9cww0pVdm9bqsswoA*, newSeq_oxiRYhNxT0khYhz289cF43Q)(NI len);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(tySequence_siX5xEDqFuO4i5rOs7ZBlg*, newSeq_b9cg9ctxOkFyhBOF9aSfw9aqnw)(NI len);
N_LIB_PRIVATE N_NIMCALL(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw*, newSystem_Uc7bDIMmotBaH0EAPWZ86g)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* matchlist, tyProc_LTibXkW8wgZIS6uZJDSRwg load, tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ preUpdate, tyProc_LTibXkW8wgZIS6uZJDSRwg update, tyProc_LTibXkW8wgZIS6uZJDSRwg draw, tyProc_LTibXkW8wgZIS6uZJDSRwg destroy, tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ preDraw);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, newSeq_9cL6dIz2UWtIh3FeS5x4hxA)(NI len);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(TGenericSeq*, incrSeqV3)(TGenericSeq* s, TNimType* typ);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ**, X5BX5D__NohJMZFSevRB8muffr3fJQ)(tyObject_Table_9ab5RwcLehRlj0xrxSya29cQ* t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, has_MH6jbGt8vn0ZkYXOzl88sQ)(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self, NimStringDesc* t);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey_x4AAljyHwDG0HHs5iImnbw)(tyObject_Table_9ab5RwcLehRlj0xrxSya29cQ t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(void, initTable_wHvVsg9bgNFiVHppwhhDUzw)(NI initialSize, tyObject_Table_9ab5RwcLehRlj0xrxSya29cQ* Result);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, add_1KIoUGUuMSRz6fx6TrmwFQ)(tyObject_Table_9ab5RwcLehRlj0xrxSya29cQ* t, NimStringDesc* key, tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ* val);
static N_INLINE(NI, subInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, matches_ER9a2KSlFoSqFO9beQDIzLww)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e);
N_LIB_PRIVATE N_NIMCALL(void, delete_D0PxZV2t1EUFTG9aHc25IfQ)(tySequence_sxV7BWZ9cww0pVdm9bqsswoA** x, NI i);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg* world_M14QSo1egm66WmikxMh52g;
TNimType NTI_KccFVpsYw1e2AJ3Xnk9cAfg_;
TNimType NTI_9bwdc6iyZGiId8gvyONht0g_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_X8aacFQVnMMG3eJMkbZvPQ_;
TNimType NTI_uy40IH3avHBB9chAP6wAq9bg_;
extern TNimType NTI_9ab5RwcLehRlj0xrxSya29cQ_;
TNimType NTI_R9b3hfapA2py1I4YfWk0zBA_;
TNimType NTI_sxV7BWZ9cww0pVdm9bqsswoA_;
TNimType NTI_bUxkNAwYdPyt85kuMYOTKw_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
TNimType NTI_Ulk9cd4UOHLw9aKiI8pa0uaQ_;
extern TNimType NTI_vr5DoT1jILTGdRlYv1OYpw_;
TNimType NTI_sO5O0Qy9bzKs0atwA6HUBAw_;
TNimType NTI_58EFneeS9at7cA541QCoGAw_;
TNimType NTI_LTibXkW8wgZIS6uZJDSRwg_;
TNimType NTI_kqRkyKwWUGhRwkJfLvzABw_;
TNimType NTI_siX5xEDqFuO4i5rOs7ZBlg_;
TNimType NTI_kFs8aoCoWWyGs19aEbPaOUg_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
STRING_LITERAL(TM_rwLMXCJFajv59bjeX5ComAQ_9, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(TM_rwLMXCJFajv59bjeX5ComAQ_10, "Body", 4);
STRING_LITERAL(TM_rwLMXCJFajv59bjeX5ComAQ_11, "RectangleComponent", 18);
STRING_LITERAL(TM_rwLMXCJFajv59bjeX5ComAQ_12, "Sprite", 6);
STRING_LITERAL(TM_rwLMXCJFajv59bjeX5ComAQ_15, "PhysicsBody", 11);
STRING_LITERAL(TM_rwLMXCJFajv59bjeX5ComAQ_16, "Enemy", 5);
STRING_LITERAL(TM_rwLMXCJFajv59bjeX5ComAQ_17, "Item", 4);
NIM_CONST tyArray_9c1pQHm5qJ9cE1a5EAUkfPIQ TM_rwLMXCJFajv59bjeX5ComAQ_18 = {((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_10)}
;
NIM_CONST tyArray_9c1pQHm5qJ9cE1a5EAUkfPIQ TM_rwLMXCJFajv59bjeX5ComAQ_19 = {((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_15)}
;
NIM_CONST tyArray_9c1pQHm5qJ9cE1a5EAUkfPIQ TM_rwLMXCJFajv59bjeX5ComAQ_20 = {((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_12)}
;
STRING_LITERAL(TM_rwLMXCJFajv59bjeX5ComAQ_22, "Player", 6);
NIM_CONST tyArray_9c1pQHm5qJ9cE1a5EAUkfPIQ TM_rwLMXCJFajv59bjeX5ComAQ_21 = {((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_22)}
;
NIM_CONST tyArray_9c1pQHm5qJ9cE1a5EAUkfPIQ TM_rwLMXCJFajv59bjeX5ComAQ_23 = {((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_16)}
;
NIM_CONST tyArray_9c1pQHm5qJ9cE1a5EAUkfPIQ TM_rwLMXCJFajv59bjeX5ComAQ_24 = {((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_17)}
;
static N_NIMCALL(void, Marker_tyRef_uy40IH3avHBB9chAP6wAq9bg)(void* p, NI op) {
	tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ* a;
	a = (tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ*)p;
}
static N_NIMCALL(void, Marker_tyRef_R9b3hfapA2py1I4YfWk0zBA)(void* p, NI op) {
	tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* a;
	a = (tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g*)p;
	nimGCvisit((void*)(*a).components.data, op);
}
static N_NIMCALL(void, Marker_tySequence_sxV7BWZ9cww0pVdm9bqsswoA)(void* p, NI op) {
	tySequence_sxV7BWZ9cww0pVdm9bqsswoA* a;
	NI T1_;
	a = (tySequence_sxV7BWZ9cww0pVdm9bqsswoA*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}
static N_NIMCALL(void, Marker_tySequence_sM4lkSb7zS6F7OVMvW9cffQ)(void* p, NI op) {
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* a;
	NI T1_;
	a = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}
static N_NIMCALL(void, Marker_tyRef_58EFneeS9at7cA541QCoGAw)(void* p, NI op) {
	tyObject_Env_ecsdotnim__sO5O0Qy9bzKs0atwA6HUBAw* a;
	a = (tyObject_Env_ecsdotnim__sO5O0Qy9bzKs0atwA6HUBAw*)p;
}
static N_NIMCALL(void, Marker_tyRef_kqRkyKwWUGhRwkJfLvzABw)(void* p, NI op) {
	tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* a;
	a = (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw*)p;
	nimGCvisit((void*)(*a).worldRef, op);
	nimGCvisit((void*)(*a).matchList, op);
	nimGCvisit((void*)(*a).preUpdate.ClE_0, op);
	nimGCvisit((void*)(*a).load.ClE_0, op);
	nimGCvisit((void*)(*a).update.ClE_0, op);
	nimGCvisit((void*)(*a).draw.ClE_0, op);
	nimGCvisit((void*)(*a).destroy.ClE_0, op);
	nimGCvisit((void*)(*a).preDraw.ClE_0, op);
}
static N_NIMCALL(void, Marker_tySequence_siX5xEDqFuO4i5rOs7ZBlg)(void* p, NI op) {
	tySequence_siX5xEDqFuO4i5rOs7ZBlg* a;
	NI T1_;
	a = (tySequence_siX5xEDqFuO4i5rOs7ZBlg*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}
static N_NIMCALL(void, Marker_tyRef_kFs8aoCoWWyGs19aEbPaOUg)(void* p, NI op) {
	tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg* a;
	a = (tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg*)p;
	nimGCvisit((void*)(*a).entities, op);
	nimGCvisit((void*)(*a).systems, op);
}
static N_NIMCALL(void, TM_rwLMXCJFajv59bjeX5ComAQ_7)(void) {
	nimGCvisit((void*)world_M14QSo1egm66WmikxMh52g, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(400, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(400, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg*, newWorld_c0qJWgzks2BMeljz9c19cp3Q)(void) {
	tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg* result;
	tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg* T1_;
	nimfr_("newWorld", "ecs.nim");
	result = (tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg*)0;
	nimln_(80, "ecs.nim");
	T1_ = (tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg*)0;
	T1_ = (tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg*) newObj((&NTI_kFs8aoCoWWyGs19aEbPaOUg_), sizeof(tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg));
	nimln_(741, "system.nim");
	asgnRef((void**) (&(*T1_).entities), newSeq_oxiRYhNxT0khYhz289cF43Q(((NI) 0)));
	asgnRef((void**) (&(*T1_).systems), newSeq_b9cg9ctxOkFyhBOF9aSfw9aqnw(((NI) 0)));
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw*, newSystem_Uc7bDIMmotBaH0EAPWZ86g)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* matchlist, tyProc_LTibXkW8wgZIS6uZJDSRwg load, tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ preUpdate, tyProc_LTibXkW8wgZIS6uZJDSRwg update, tyProc_LTibXkW8wgZIS6uZJDSRwg draw, tyProc_LTibXkW8wgZIS6uZJDSRwg destroy, tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ preDraw) {
	tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* result;
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* match;
	tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* T12_;
	nimfr_("newSystem", "ecs.nim");
{	result = (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw*)0;
	nimln_(60, "ecs.nim");
	match = newSeq_9cL6dIz2UWtIh3FeS5x4hxA(((NI) 0));
	{
		NimStringDesc* m;
		NI i;
		NI L;
		NI T2_;
		m = (NimStringDesc*)0;
		nimln_(3815, "system.nim");
		i = ((NI) 0);
		nimln_(3816, "system.nim");
		T2_ = (matchlist ? matchlist->Sup.len : 0);
		L = T2_;
		{
			nimln_(3817, "system.nim");
			while (1) {
				NI T5_;
				NimStringDesc* T6_;
				NI TM_rwLMXCJFajv59bjeX5ComAQ_8;
				if (!(i < L)) goto LA4;
				nimln_(3818, "system.nim");
				if (!matchlist || (NU)(i) >= (NU)(matchlist->Sup.len)) raiseIndexError();
				m = matchlist->data[i];
				nimln_(62, "ecs.nim");
				match = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV3(&(match)->Sup, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
				T5_ = match->Sup.len++;
				T6_ = (NimStringDesc*)0;
				T6_ = match->data[T5_]; match->data[T5_] = copyStringRC1(m);
				if (T6_) nimGCunrefNoCycle(T6_);
				nimln_(3819, "system.nim");
				TM_rwLMXCJFajv59bjeX5ComAQ_8 = addInt(i, ((NI) 1));
				i = (NI)(TM_rwLMXCJFajv59bjeX5ComAQ_8);
				nimln_(3820, "system.nim");
				{
					NI T9_;
					T9_ = (matchlist ? matchlist->Sup.len : 0);
					if (!!((T9_ == L))) goto LA10_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_9));
				}
				LA10_: ;
			} LA4: ;
		}
	}
	nimln_(64, "ecs.nim");
	T12_ = (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw*)0;
	T12_ = (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw*) newObj((&NTI_kqRkyKwWUGhRwkJfLvzABw_), sizeof(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw));
	genericSeqAssign((&(*T12_).matchList), match, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
	asgnRef((void**) (&(*T12_).load.ClE_0), load.ClE_0);
	(*T12_).load.ClP_0 = load.ClP_0;
	asgnRef((void**) (&(*T12_).preUpdate.ClE_0), preUpdate.ClE_0);
	(*T12_).preUpdate.ClP_0 = preUpdate.ClP_0;
	asgnRef((void**) (&(*T12_).update.ClE_0), update.ClE_0);
	(*T12_).update.ClP_0 = update.ClP_0;
	asgnRef((void**) (&(*T12_).draw.ClE_0), draw.ClE_0);
	(*T12_).draw.ClP_0 = draw.ClP_0;
	asgnRef((void**) (&(*T12_).destroy.ClE_0), destroy.ClE_0);
	(*T12_).destroy.ClP_0 = destroy.ClP_0;
	asgnRef((void**) (&(*T12_).preDraw.ClE_0), preDraw.ClE_0);
	(*T12_).preDraw.ClP_0 = preDraw.ClP_0;
	result = T12_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw*, createSystem_ZIEE3eqxo9anA1Qzcbrx5Vg)(tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg* world, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* matchlist, tyProc_LTibXkW8wgZIS6uZJDSRwg load, tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ preUpdate, tyProc_LTibXkW8wgZIS6uZJDSRwg update, tyProc_LTibXkW8wgZIS6uZJDSRwg draw, tyProc_LTibXkW8wgZIS6uZJDSRwg destroy, tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ preDraw) {
	tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* result;
	NI T1_;
	nimfr_("createSystem", "ecs.nim");
	result = (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw*)0;
	nimln_(149, "ecs.nim");
	result = newSystem_Uc7bDIMmotBaH0EAPWZ86g(matchlist, load, preUpdate, update, draw, destroy, preDraw);
	nimln_(158, "ecs.nim");
	asgnRef((void**) (&(*result).worldRef), world);
	nimln_(159, "ecs.nim");
	(*world).systems = (tySequence_siX5xEDqFuO4i5rOs7ZBlg*) incrSeqV3(&((*world).systems)->Sup, (&NTI_siX5xEDqFuO4i5rOs7ZBlg_));
	T1_ = (*world).systems->Sup.len++;
	asgnRef((void**) (&(*world).systems->data[T1_]), result);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, default_preUpdate_bubQNMeUwRg1mVj2B77VVg)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s) {
	nimfr_("default_preUpdate", "ecs.nim");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, default_update_yWuOcLIgmhG0YcAceats8w)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e) {
	nimfr_("default_update", "ecs.nim");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ*, get_UpICIghUTrvN3fZF3drLBQ)(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self) {
	tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* result;
	tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ** T1_;
	nimfr_("get", "ecs.nim");
{	result = (tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ*)0;
	nimln_(42, "ecs.nim");
	T1_ = (tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ**)0;
	T1_ = X5BX5D__NohJMZFSevRB8muffr3fJQ((&(*self).components), ((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_10));
	result = ((tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ*) ((*T1_)));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_RectangleComponentcolonObjectType__Td9aXtPuWzNdKHrUL9cPq5lQ*, get_2dD9bkJZHXCId7ayQ4FqPRQ)(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self) {
	tyObject_RectangleComponentcolonObjectType__Td9aXtPuWzNdKHrUL9cPq5lQ* result;
	tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ** T1_;
	nimfr_("get", "ecs.nim");
{	result = (tyObject_RectangleComponentcolonObjectType__Td9aXtPuWzNdKHrUL9cPq5lQ*)0;
	nimln_(42, "ecs.nim");
	T1_ = (tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ**)0;
	T1_ = X5BX5D__NohJMZFSevRB8muffr3fJQ((&(*self).components), ((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_11));
	result = ((tyObject_RectangleComponentcolonObjectType__Td9aXtPuWzNdKHrUL9cPq5lQ*) ((*T1_)));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, default_destroy_yWuOcLIgmhG0YcAceats8w_2)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e) {
	nimfr_("default_destroy", "ecs.nim");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, default_preDraw_bubQNMeUwRg1mVj2B77VVg_2)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s) {
	nimfr_("default_preDraw", "ecs.nim");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A*, get_RSEbINeSUjOPFVLfePsoHQ)(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self) {
	tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A* result;
	tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ** T1_;
	nimfr_("get", "ecs.nim");
{	result = (tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A*)0;
	nimln_(42, "ecs.nim");
	T1_ = (tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ**)0;
	T1_ = X5BX5D__NohJMZFSevRB8muffr3fJQ((&(*self).components), ((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_12));
	result = ((tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A*) ((*T1_)));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, default_load_yWuOcLIgmhG0YcAceats8w_3)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e) {
	nimfr_("default_load", "ecs.nim");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, has_MH6jbGt8vn0ZkYXOzl88sQ)(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self, NimStringDesc* t) {
	NIM_BOOL result;
	nimfr_("has", "ecs.nim");
{	result = (NIM_BOOL)0;
	nimln_(48, "ecs.nim");
	result = hasKey_x4AAljyHwDG0HHs5iImnbw((*self).components, t);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tySequence_sxV7BWZ9cww0pVdm9bqsswoA*, getAllThatMatch_cyy1TBofffQvht5kB2juEQ)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* matchlist) {
	tySequence_sxV7BWZ9cww0pVdm9bqsswoA* result;
	nimfr_("getAllThatMatch", "ecs.nim");
	result = (tySequence_sxV7BWZ9cww0pVdm9bqsswoA*)0;
	nimln_(741, "system.nim");
	result = newSeq_oxiRYhNxT0khYhz289cF43Q(((NI) 0));
	{
		tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e;
		tySequence_sxV7BWZ9cww0pVdm9bqsswoA* colontmp_;
		NI i;
		NI L;
		NI T2_;
		e = (tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g*)0;
		colontmp_ = (tySequence_sxV7BWZ9cww0pVdm9bqsswoA*)0;
		nimln_(90, "ecs.nim");
		colontmp_ = (*world_M14QSo1egm66WmikxMh52g).entities;
		nimln_(3815, "system.nim");
		i = ((NI) 0);
		nimln_(3816, "system.nim");
		T2_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T2_;
		{
			nimln_(3817, "system.nim");
			while (1) {
				NIM_BOOL good;
				NI TM_rwLMXCJFajv59bjeX5ComAQ_14;
				if (!(i < L)) goto LA4;
				nimln_(3818, "system.nim");
				if (!colontmp_ || (NU)(i) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
				e = colontmp_->data[i];
				nimln_(91, "ecs.nim");
				good = NIM_TRUE;
				{
					NimStringDesc* m;
					NI i_2;
					NI L_2;
					NI T6_;
					m = (NimStringDesc*)0;
					nimln_(3815, "system.nim");
					i_2 = ((NI) 0);
					nimln_(3816, "system.nim");
					T6_ = (matchlist ? matchlist->Sup.len : 0);
					L_2 = T6_;
					{
						nimln_(3817, "system.nim");
						while (1) {
							NI TM_rwLMXCJFajv59bjeX5ComAQ_13;
							if (!(i_2 < L_2)) goto LA8;
							nimln_(3818, "system.nim");
							if (!matchlist || (NU)(i_2) >= (NU)(matchlist->Sup.len)) raiseIndexError();
							m = matchlist->data[i_2];
							nimln_(93, "ecs.nim");
							{
								NIM_BOOL T11_;
								T11_ = (NIM_BOOL)0;
								T11_ = has_MH6jbGt8vn0ZkYXOzl88sQ(e, m);
								if (!!(T11_)) goto LA12_;
								nimln_(94, "ecs.nim");
								good = NIM_FALSE;
							}
							LA12_: ;
							nimln_(3819, "system.nim");
							TM_rwLMXCJFajv59bjeX5ComAQ_13 = addInt(i_2, ((NI) 1));
							i_2 = (NI)(TM_rwLMXCJFajv59bjeX5ComAQ_13);
							nimln_(3820, "system.nim");
							{
								NI T16_;
								T16_ = (matchlist ? matchlist->Sup.len : 0);
								if (!!((T16_ == L_2))) goto LA17_;
								failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_9));
							}
							LA17_: ;
						} LA8: ;
					}
				}
				nimln_(95, "ecs.nim");
				{
					NI T23_;
					if (!good) goto LA21_;
					result = (tySequence_sxV7BWZ9cww0pVdm9bqsswoA*) incrSeqV3(&(result)->Sup, (&NTI_sxV7BWZ9cww0pVdm9bqsswoA_));
					T23_ = result->Sup.len++;
					asgnRef((void**) (&result->data[T23_]), e);
				}
				LA21_: ;
				nimln_(3819, "system.nim");
				TM_rwLMXCJFajv59bjeX5ComAQ_14 = addInt(i, ((NI) 1));
				i = (NI)(TM_rwLMXCJFajv59bjeX5ComAQ_14);
				nimln_(3820, "system.nim");
				{
					NI T26_;
					T26_ = (colontmp_ ? colontmp_->Sup.len : 0);
					if (!!((T26_ == L))) goto LA27_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_9));
				}
				LA27_: ;
			} LA4: ;
		}
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_PhysicsBodycolonObjectType__qOCpO56KLJz1SFjXu8FuZw*, get_bz2WrLTHQuyavdukYjN8Cw)(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self) {
	tyObject_PhysicsBodycolonObjectType__qOCpO56KLJz1SFjXu8FuZw* result;
	tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ** T1_;
	nimfr_("get", "ecs.nim");
{	result = (tyObject_PhysicsBodycolonObjectType__qOCpO56KLJz1SFjXu8FuZw*)0;
	nimln_(42, "ecs.nim");
	T1_ = (tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ**)0;
	T1_ = X5BX5D__NohJMZFSevRB8muffr3fJQ((&(*self).components), ((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_15));
	result = ((tyObject_PhysicsBodycolonObjectType__qOCpO56KLJz1SFjXu8FuZw*) ((*T1_)));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_EnemycolonObjectType__6wQJK6c5zRekZO1fQWX9cZw*, get_5TvzHDxUABTxaj10H5TFsA)(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self) {
	tyObject_EnemycolonObjectType__6wQJK6c5zRekZO1fQWX9cZw* result;
	tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ** T1_;
	nimfr_("get", "ecs.nim");
{	result = (tyObject_EnemycolonObjectType__6wQJK6c5zRekZO1fQWX9cZw*)0;
	nimln_(42, "ecs.nim");
	T1_ = (tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ**)0;
	T1_ = X5BX5D__NohJMZFSevRB8muffr3fJQ((&(*self).components), ((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_16));
	result = ((tyObject_EnemycolonObjectType__6wQJK6c5zRekZO1fQWX9cZw*) ((*T1_)));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, default_render_yWuOcLIgmhG0YcAceats8w_4)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e) {
	nimfr_("default_render", "ecs.nim");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, has_FpBorqVgH9cRtK6hvltPKqw)(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self) {
	NIM_BOOL result;
	nimfr_("has", "ecs.nim");
{	result = (NIM_BOOL)0;
	nimln_(45, "ecs.nim");
	result = hasKey_x4AAljyHwDG0HHs5iImnbw((*self).components, ((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_17));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g*, createEntity_wmjgS3UJpzyzC4iY2hAzOg)(tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg* world) {
	tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* result;
	tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* T1_;
	NI T2_;
	nimfr_("createEntity", "ecs.nim");
	result = (tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g*)0;
	nimln_(129, "ecs.nim");
	T1_ = (tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g*)0;
	T1_ = (tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g*) newObj((&NTI_R9b3hfapA2py1I4YfWk0zBA_), sizeof(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g));
	nimln_(332, "tables.nim");
	initTable_wHvVsg9bgNFiVHppwhhDUzw(((NI) 64), (&(*T1_).components));
	(*T1_).loaded = NIM_FALSE;
	(*T1_).remove = NIM_FALSE;
	result = T1_;
	nimln_(135, "ecs.nim");
	(*world).entities = (tySequence_sxV7BWZ9cww0pVdm9bqsswoA*) incrSeqV3(&((*world).entities)->Sup, (&NTI_sxV7BWZ9cww0pVdm9bqsswoA_));
	T2_ = (*world).entities->Sup.len++;
	asgnRef((void**) (&(*world).entities->data[T2_]), result);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ*, add_5Cb4UFFJROnyavYIstFf0g)(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self, tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* component) {
	tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* result;
	tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ* T1_;
	nimfr_("add", "ecs.nim");
{	result = (tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ*)0;
	nimln_(37, "ecs.nim");
	echoBinSafe(TM_rwLMXCJFajv59bjeX5ComAQ_18, 1);
	nimln_(38, "ecs.nim");
	T1_ = (tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ*)0;
	T1_ = &component->Sup;
	add_1KIoUGUuMSRz6fx6TrmwFQ((&(*self).components), ((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_10), T1_);
	nimln_(39, "ecs.nim");
	result = component;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_PhysicsBodycolonObjectType__qOCpO56KLJz1SFjXu8FuZw*, add_PkhpM9bixhUHHXQfHQLmgnA)(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self, tyObject_PhysicsBodycolonObjectType__qOCpO56KLJz1SFjXu8FuZw* component) {
	tyObject_PhysicsBodycolonObjectType__qOCpO56KLJz1SFjXu8FuZw* result;
	tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ* T1_;
	nimfr_("add", "ecs.nim");
{	result = (tyObject_PhysicsBodycolonObjectType__qOCpO56KLJz1SFjXu8FuZw*)0;
	nimln_(37, "ecs.nim");
	echoBinSafe(TM_rwLMXCJFajv59bjeX5ComAQ_19, 1);
	nimln_(38, "ecs.nim");
	T1_ = (tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ*)0;
	T1_ = &component->Sup;
	add_1KIoUGUuMSRz6fx6TrmwFQ((&(*self).components), ((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_15), T1_);
	nimln_(39, "ecs.nim");
	result = component;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A*, add_o9byJV9cirH3xuwiYVLsIdew)(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self, tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A* component) {
	tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A* result;
	tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ* T1_;
	nimfr_("add", "ecs.nim");
{	result = (tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A*)0;
	nimln_(37, "ecs.nim");
	echoBinSafe(TM_rwLMXCJFajv59bjeX5ComAQ_20, 1);
	nimln_(38, "ecs.nim");
	T1_ = (tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ*)0;
	T1_ = &component->Sup.Sup;
	add_1KIoUGUuMSRz6fx6TrmwFQ((&(*self).components), ((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_12), T1_);
	nimln_(39, "ecs.nim");
	result = component;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_PlayercolonObjectType__XT8bNNou1LsCIl1jlU5CFQ*, add_Y2BcS9bs2yNvoezF0p8dOiw)(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self, tyObject_PlayercolonObjectType__XT8bNNou1LsCIl1jlU5CFQ* component) {
	tyObject_PlayercolonObjectType__XT8bNNou1LsCIl1jlU5CFQ* result;
	tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ* T1_;
	nimfr_("add", "ecs.nim");
{	result = (tyObject_PlayercolonObjectType__XT8bNNou1LsCIl1jlU5CFQ*)0;
	nimln_(37, "ecs.nim");
	echoBinSafe(TM_rwLMXCJFajv59bjeX5ComAQ_21, 1);
	nimln_(38, "ecs.nim");
	T1_ = (tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ*)0;
	T1_ = &component->Sup;
	add_1KIoUGUuMSRz6fx6TrmwFQ((&(*self).components), ((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_22), T1_);
	nimln_(39, "ecs.nim");
	result = component;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_EnemycolonObjectType__6wQJK6c5zRekZO1fQWX9cZw*, add_XMbohePhB3gxYaKFu9assOw)(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self, tyObject_EnemycolonObjectType__6wQJK6c5zRekZO1fQWX9cZw* component) {
	tyObject_EnemycolonObjectType__6wQJK6c5zRekZO1fQWX9cZw* result;
	tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ* T1_;
	nimfr_("add", "ecs.nim");
{	result = (tyObject_EnemycolonObjectType__6wQJK6c5zRekZO1fQWX9cZw*)0;
	nimln_(37, "ecs.nim");
	echoBinSafe(TM_rwLMXCJFajv59bjeX5ComAQ_23, 1);
	nimln_(38, "ecs.nim");
	T1_ = (tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ*)0;
	T1_ = &component->Sup;
	add_1KIoUGUuMSRz6fx6TrmwFQ((&(*self).components), ((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_16), T1_);
	nimln_(39, "ecs.nim");
	result = component;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ItemcolonObjectType__WUdDRZlHK9bEhTn4Z7eJDew*, add_OP7bie4nLHiuMM9btFj67EQ)(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self, tyObject_ItemcolonObjectType__WUdDRZlHK9bEhTn4Z7eJDew* component) {
	tyObject_ItemcolonObjectType__WUdDRZlHK9bEhTn4Z7eJDew* result;
	tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ* T1_;
	nimfr_("add", "ecs.nim");
{	result = (tyObject_ItemcolonObjectType__WUdDRZlHK9bEhTn4Z7eJDew*)0;
	nimln_(37, "ecs.nim");
	echoBinSafe(TM_rwLMXCJFajv59bjeX5ComAQ_24, 1);
	nimln_(38, "ecs.nim");
	T1_ = (tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ*)0;
	T1_ = &component->Sup;
	add_1KIoUGUuMSRz6fx6TrmwFQ((&(*self).components), ((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_17), T1_);
	nimln_(39, "ecs.nim");
	result = component;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, matches_ER9a2KSlFoSqFO9beQDIzLww)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e) {
	NIM_BOOL result;
	nimfr_("matches", "ecs.nim");
{	result = (NIM_BOOL)0;
	{
		NimStringDesc* m;
		tySequence_sM4lkSb7zS6F7OVMvW9cffQ* colontmp_;
		NI i;
		NI L;
		NI T2_;
		m = (NimStringDesc*)0;
		colontmp_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
		nimln_(75, "ecs.nim");
		colontmp_ = (*s).matchList;
		nimln_(3815, "system.nim");
		i = ((NI) 0);
		nimln_(3816, "system.nim");
		T2_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T2_;
		{
			nimln_(3817, "system.nim");
			while (1) {
				NI TM_rwLMXCJFajv59bjeX5ComAQ_28;
				if (!(i < L)) goto LA4;
				nimln_(3818, "system.nim");
				if (!colontmp_ || (NU)(i) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
				m = colontmp_->data[i];
				nimln_(76, "ecs.nim");
				{
					NIM_BOOL T7_;
					T7_ = (NIM_BOOL)0;
					T7_ = has_MH6jbGt8vn0ZkYXOzl88sQ(e, m);
					if (!!(T7_)) goto LA8_;
					result = NIM_FALSE;
					goto BeforeRet_;
				}
				LA8_: ;
				nimln_(3819, "system.nim");
				TM_rwLMXCJFajv59bjeX5ComAQ_28 = addInt(i, ((NI) 1));
				i = (NI)(TM_rwLMXCJFajv59bjeX5ComAQ_28);
				nimln_(3820, "system.nim");
				{
					NI T12_;
					T12_ = (colontmp_ ? colontmp_->Sup.len : 0);
					if (!!((T12_ == L))) goto LA13_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_9));
				}
				LA13_: ;
			} LA4: ;
		}
	}
	nimln_(77, "ecs.nim");
	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, update_HCF3eSTSl7W9cCZ9bYy0mdBw)(tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg* world) {
	NI num;
	NI T10_;
	nimfr_("update", "ecs.nim");
	{
		tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* system_1;
		tySequence_siX5xEDqFuO4i5rOs7ZBlg* colontmp_;
		NI i;
		NI L;
		NI T2_;
		system_1 = (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw*)0;
		colontmp_ = (tySequence_siX5xEDqFuO4i5rOs7ZBlg*)0;
		nimln_(98, "ecs.nim");
		colontmp_ = (*world).systems;
		nimln_(3815, "system.nim");
		i = ((NI) 0);
		nimln_(3816, "system.nim");
		T2_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T2_;
		{
			nimln_(3817, "system.nim");
			while (1) {
				NI TM_rwLMXCJFajv59bjeX5ComAQ_26;
				if (!(i < L)) goto LA4;
				nimln_(3818, "system.nim");
				if (!colontmp_ || (NU)(i) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
				system_1 = colontmp_->data[i];
				nimln_(99, "ecs.nim");
				(*system_1).preUpdate.ClE_0? (*system_1).preUpdate.ClP_0(system_1, (*system_1).preUpdate.ClE_0):((TM_rwLMXCJFajv59bjeX5ComAQ_25)((*system_1).preUpdate.ClP_0))(system_1);
				nimln_(3819, "system.nim");
				TM_rwLMXCJFajv59bjeX5ComAQ_26 = addInt(i, ((NI) 1));
				i = (NI)(TM_rwLMXCJFajv59bjeX5ComAQ_26);
				nimln_(3820, "system.nim");
				{
					NI T7_;
					T7_ = (colontmp_ ? colontmp_->Sup.len : 0);
					if (!!((T7_ == L))) goto LA8_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_9));
				}
				LA8_: ;
			} LA4: ;
		}
	}
	nimln_(101, "ecs.nim");
	T10_ = ((*world).entities ? (*world).entities->Sup.len : 0);
	num = T10_;
	{
		NI i_2;
		NI colontmp__2;
		NI TM_rwLMXCJFajv59bjeX5ComAQ_27;
		NI res;
		i_2 = (NI)0;
		colontmp__2 = (NI)0;
		nimln_(102, "ecs.nim");
		TM_rwLMXCJFajv59bjeX5ComAQ_27 = subInt(num, ((NI) 1));
		colontmp__2 = (NI)(TM_rwLMXCJFajv59bjeX5ComAQ_27);
		nimln_(2027, "system.nim");
		res = colontmp__2;
		{
			nimln_(2028, "system.nim");
			while (1) {
				tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* entity;
				NI TM_rwLMXCJFajv59bjeX5ComAQ_34;
				nimln_(102, "ecs.nim");
				if (!(((NI) 0) <= res)) goto LA13;
				nimln_(2029, "system.nim");
				i_2 = res;
				nimln_(103, "ecs.nim");
				if (!(*world).entities || (NU)(i_2) >= (NU)((*world).entities->Sup.len)) raiseIndexError();
				entity = (*world).entities->data[i_2];
				{
					tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* system_2;
					tySequence_siX5xEDqFuO4i5rOs7ZBlg* colontmp__3;
					NI i_3;
					NI L_2;
					NI T15_;
					system_2 = (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw*)0;
					colontmp__3 = (tySequence_siX5xEDqFuO4i5rOs7ZBlg*)0;
					nimln_(105, "ecs.nim");
					colontmp__3 = (*world).systems;
					nimln_(3815, "system.nim");
					i_3 = ((NI) 0);
					nimln_(3816, "system.nim");
					T15_ = (colontmp__3 ? colontmp__3->Sup.len : 0);
					L_2 = T15_;
					{
						nimln_(3817, "system.nim");
						while (1) {
							NI TM_rwLMXCJFajv59bjeX5ComAQ_31;
							if (!(i_3 < L_2)) goto LA17;
							nimln_(3818, "system.nim");
							if (!colontmp__3 || (NU)(i_3) >= (NU)(colontmp__3->Sup.len)) raiseIndexError();
							system_2 = colontmp__3->data[i_3];
							nimln_(106, "ecs.nim");
							{
								NIM_BOOL T20_;
								T20_ = (NIM_BOOL)0;
								T20_ = matches_ER9a2KSlFoSqFO9beQDIzLww(system_2, entity);
								if (!T20_) goto LA21_;
								nimln_(107, "ecs.nim");
								{
									if (!!((*entity).loaded)) goto LA25_;
									nimln_(108, "ecs.nim");
									(*system_2).load.ClE_0? (*system_2).load.ClP_0(system_2, entity, (*system_2).load.ClE_0):((TM_rwLMXCJFajv59bjeX5ComAQ_29)((*system_2).load.ClP_0))(system_2, entity);
								}
								LA25_: ;
								nimln_(110, "ecs.nim");
								(*system_2).update.ClE_0? (*system_2).update.ClP_0(system_2, entity, (*system_2).update.ClE_0):((TM_rwLMXCJFajv59bjeX5ComAQ_30)((*system_2).update.ClP_0))(system_2, entity);
							}
							LA21_: ;
							nimln_(3819, "system.nim");
							TM_rwLMXCJFajv59bjeX5ComAQ_31 = addInt(i_3, ((NI) 1));
							i_3 = (NI)(TM_rwLMXCJFajv59bjeX5ComAQ_31);
							nimln_(3820, "system.nim");
							{
								NI T29_;
								T29_ = (colontmp__3 ? colontmp__3->Sup.len : 0);
								if (!!((T29_ == L_2))) goto LA30_;
								failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_9));
							}
							LA30_: ;
						} LA17: ;
					}
				}
				nimln_(112, "ecs.nim");
				(*entity).loaded = NIM_TRUE;
				nimln_(113, "ecs.nim");
				{
					if (!(*entity).remove) goto LA34_;
					{
						tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* system_3;
						tySequence_siX5xEDqFuO4i5rOs7ZBlg* colontmp__4;
						NI i_4;
						NI L_3;
						NI T37_;
						system_3 = (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw*)0;
						colontmp__4 = (tySequence_siX5xEDqFuO4i5rOs7ZBlg*)0;
						nimln_(114, "ecs.nim");
						colontmp__4 = (*world).systems;
						nimln_(3815, "system.nim");
						i_4 = ((NI) 0);
						nimln_(3816, "system.nim");
						T37_ = (colontmp__4 ? colontmp__4->Sup.len : 0);
						L_3 = T37_;
						{
							nimln_(3817, "system.nim");
							while (1) {
								NI TM_rwLMXCJFajv59bjeX5ComAQ_33;
								if (!(i_4 < L_3)) goto LA39;
								nimln_(3818, "system.nim");
								if (!colontmp__4 || (NU)(i_4) >= (NU)(colontmp__4->Sup.len)) raiseIndexError();
								system_3 = colontmp__4->data[i_4];
								nimln_(115, "ecs.nim");
								{
									NIM_BOOL T42_;
									T42_ = (NIM_BOOL)0;
									T42_ = matches_ER9a2KSlFoSqFO9beQDIzLww(system_3, entity);
									if (!T42_) goto LA43_;
									nimln_(116, "ecs.nim");
									(*system_3).destroy.ClE_0? (*system_3).destroy.ClP_0(system_3, entity, (*system_3).destroy.ClE_0):((TM_rwLMXCJFajv59bjeX5ComAQ_32)((*system_3).destroy.ClP_0))(system_3, entity);
								}
								LA43_: ;
								nimln_(3819, "system.nim");
								TM_rwLMXCJFajv59bjeX5ComAQ_33 = addInt(i_4, ((NI) 1));
								i_4 = (NI)(TM_rwLMXCJFajv59bjeX5ComAQ_33);
								nimln_(3820, "system.nim");
								{
									NI T47_;
									T47_ = (colontmp__4 ? colontmp__4->Sup.len : 0);
									if (!!((T47_ == L_3))) goto LA48_;
									failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_9));
								}
								LA48_: ;
							} LA39: ;
						}
					}
					nimln_(117, "ecs.nim");
					delete_D0PxZV2t1EUFTG9aHc25IfQ((&(*world).entities), ((NI)chckRange(i_2, ((NI) 0), ((NI) IL64(9223372036854775807)))));
				}
				LA34_: ;
				nimln_(2030, "system.nim");
				TM_rwLMXCJFajv59bjeX5ComAQ_34 = subInt(res, ((NI) 1));
				res = (NI)(TM_rwLMXCJFajv59bjeX5ComAQ_34);
			} LA13: ;
		}
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, draw_HCF3eSTSl7W9cCZ9bYy0mdBw_2)(tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg* world) {
	nimfr_("draw", "ecs.nim");
	{
		tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* system_1;
		tySequence_siX5xEDqFuO4i5rOs7ZBlg* colontmp_;
		NI i;
		NI L;
		NI T2_;
		system_1 = (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw*)0;
		colontmp_ = (tySequence_siX5xEDqFuO4i5rOs7ZBlg*)0;
		nimln_(120, "ecs.nim");
		colontmp_ = (*world).systems;
		nimln_(3815, "system.nim");
		i = ((NI) 0);
		nimln_(3816, "system.nim");
		T2_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T2_;
		{
			nimln_(3817, "system.nim");
			while (1) {
				NI TM_rwLMXCJFajv59bjeX5ComAQ_36;
				if (!(i < L)) goto LA4;
				nimln_(3818, "system.nim");
				if (!colontmp_ || (NU)(i) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
				system_1 = colontmp_->data[i];
				nimln_(121, "ecs.nim");
				(*system_1).preDraw.ClE_0? (*system_1).preDraw.ClP_0(system_1, (*system_1).preDraw.ClE_0):((TM_rwLMXCJFajv59bjeX5ComAQ_35)((*system_1).preDraw.ClP_0))(system_1);
				nimln_(3819, "system.nim");
				TM_rwLMXCJFajv59bjeX5ComAQ_36 = addInt(i, ((NI) 1));
				i = (NI)(TM_rwLMXCJFajv59bjeX5ComAQ_36);
				nimln_(3820, "system.nim");
				{
					NI T7_;
					T7_ = (colontmp_ ? colontmp_->Sup.len : 0);
					if (!!((T7_ == L))) goto LA8_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_9));
				}
				LA8_: ;
			} LA4: ;
		}
	}
	{
		tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* entity;
		tySequence_sxV7BWZ9cww0pVdm9bqsswoA* colontmp__2;
		NI i_2;
		NI L_2;
		NI T11_;
		entity = (tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g*)0;
		colontmp__2 = (tySequence_sxV7BWZ9cww0pVdm9bqsswoA*)0;
		nimln_(123, "ecs.nim");
		colontmp__2 = (*world).entities;
		nimln_(3815, "system.nim");
		i_2 = ((NI) 0);
		nimln_(3816, "system.nim");
		T11_ = (colontmp__2 ? colontmp__2->Sup.len : 0);
		L_2 = T11_;
		{
			nimln_(3817, "system.nim");
			while (1) {
				NI TM_rwLMXCJFajv59bjeX5ComAQ_39;
				if (!(i_2 < L_2)) goto LA13;
				nimln_(3818, "system.nim");
				if (!colontmp__2 || (NU)(i_2) >= (NU)(colontmp__2->Sup.len)) raiseIndexError();
				entity = colontmp__2->data[i_2];
				{
					tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* system_2;
					tySequence_siX5xEDqFuO4i5rOs7ZBlg* colontmp__3;
					NI i_3;
					NI L_3;
					NI T15_;
					system_2 = (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw*)0;
					colontmp__3 = (tySequence_siX5xEDqFuO4i5rOs7ZBlg*)0;
					nimln_(124, "ecs.nim");
					colontmp__3 = (*world).systems;
					nimln_(3815, "system.nim");
					i_3 = ((NI) 0);
					nimln_(3816, "system.nim");
					T15_ = (colontmp__3 ? colontmp__3->Sup.len : 0);
					L_3 = T15_;
					{
						nimln_(3817, "system.nim");
						while (1) {
							NI TM_rwLMXCJFajv59bjeX5ComAQ_38;
							if (!(i_3 < L_3)) goto LA17;
							nimln_(3818, "system.nim");
							if (!colontmp__3 || (NU)(i_3) >= (NU)(colontmp__3->Sup.len)) raiseIndexError();
							system_2 = colontmp__3->data[i_3];
							nimln_(125, "ecs.nim");
							{
								NIM_BOOL T20_;
								T20_ = (NIM_BOOL)0;
								T20_ = matches_ER9a2KSlFoSqFO9beQDIzLww(system_2, entity);
								if (!T20_) goto LA21_;
								nimln_(126, "ecs.nim");
								(*system_2).draw.ClE_0? (*system_2).draw.ClP_0(system_2, entity, (*system_2).draw.ClE_0):((TM_rwLMXCJFajv59bjeX5ComAQ_37)((*system_2).draw.ClP_0))(system_2, entity);
							}
							LA21_: ;
							nimln_(3819, "system.nim");
							TM_rwLMXCJFajv59bjeX5ComAQ_38 = addInt(i_3, ((NI) 1));
							i_3 = (NI)(TM_rwLMXCJFajv59bjeX5ComAQ_38);
							nimln_(3820, "system.nim");
							{
								NI T25_;
								T25_ = (colontmp__3 ? colontmp__3->Sup.len : 0);
								if (!!((T25_ == L_3))) goto LA26_;
								failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_9));
							}
							LA26_: ;
						} LA17: ;
					}
				}
				nimln_(3819, "system.nim");
				TM_rwLMXCJFajv59bjeX5ComAQ_39 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_rwLMXCJFajv59bjeX5ComAQ_39);
				nimln_(3820, "system.nim");
				{
					NI T30_;
					T30_ = (colontmp__2 ? colontmp__2->Sup.len : 0);
					if (!!((T30_ == L_2))) goto LA31_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_rwLMXCJFajv59bjeX5ComAQ_9));
				}
				LA31_: ;
			} LA13: ;
		}
	}
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, VectorGuy_ecsInit000)(void) {
	nimfr_("ecs", "ecs.nim");
nimRegisterGlobalMarker(TM_rwLMXCJFajv59bjeX5ComAQ_7);
	nimln_(85, "ecs.nim");
	asgnRef((void**) (&world_M14QSo1egm66WmikxMh52g), newWorld_c0qJWgzks2BMeljz9c19cp3Q());
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, VectorGuy_ecsDatInit000)(void) {
static TNimNode* TM_rwLMXCJFajv59bjeX5ComAQ_2[2];
static TNimNode* TM_rwLMXCJFajv59bjeX5ComAQ_3[3];
static TNimNode* TM_rwLMXCJFajv59bjeX5ComAQ_4[8];
static TNimNode* TM_rwLMXCJFajv59bjeX5ComAQ_5[2];
static TNimNode* TM_rwLMXCJFajv59bjeX5ComAQ_6[2];
static TNimNode TM_rwLMXCJFajv59bjeX5ComAQ_0[24];
NTI_KccFVpsYw1e2AJ3Xnk9cAfg_.size = sizeof(tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg);
NTI_KccFVpsYw1e2AJ3Xnk9cAfg_.kind = 18;
NTI_KccFVpsYw1e2AJ3Xnk9cAfg_.base = 0;
TM_rwLMXCJFajv59bjeX5ComAQ_2[0] = &TM_rwLMXCJFajv59bjeX5ComAQ_0[1];
NTI_9bwdc6iyZGiId8gvyONht0g_.size = sizeof(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g);
NTI_9bwdc6iyZGiId8gvyONht0g_.kind = 18;
NTI_9bwdc6iyZGiId8gvyONht0g_.base = 0;
TM_rwLMXCJFajv59bjeX5ComAQ_3[0] = &TM_rwLMXCJFajv59bjeX5ComAQ_0[3];
TM_rwLMXCJFajv59bjeX5ComAQ_0[3].kind = 1;
TM_rwLMXCJFajv59bjeX5ComAQ_0[3].offset = offsetof(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g, loaded);
TM_rwLMXCJFajv59bjeX5ComAQ_0[3].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_rwLMXCJFajv59bjeX5ComAQ_0[3].name = "loaded";
TM_rwLMXCJFajv59bjeX5ComAQ_3[1] = &TM_rwLMXCJFajv59bjeX5ComAQ_0[4];
TM_rwLMXCJFajv59bjeX5ComAQ_0[4].kind = 1;
TM_rwLMXCJFajv59bjeX5ComAQ_0[4].offset = offsetof(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g, remove);
TM_rwLMXCJFajv59bjeX5ComAQ_0[4].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_rwLMXCJFajv59bjeX5ComAQ_0[4].name = "remove";
TM_rwLMXCJFajv59bjeX5ComAQ_3[2] = &TM_rwLMXCJFajv59bjeX5ComAQ_0[5];
NTI_X8aacFQVnMMG3eJMkbZvPQ_.size = sizeof(tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ);
NTI_X8aacFQVnMMG3eJMkbZvPQ_.kind = 17;
NTI_X8aacFQVnMMG3eJMkbZvPQ_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_X8aacFQVnMMG3eJMkbZvPQ_.flags = 1;
TM_rwLMXCJFajv59bjeX5ComAQ_0[6].len = 0; TM_rwLMXCJFajv59bjeX5ComAQ_0[6].kind = 2;
NTI_X8aacFQVnMMG3eJMkbZvPQ_.node = &TM_rwLMXCJFajv59bjeX5ComAQ_0[6];
NTI_uy40IH3avHBB9chAP6wAq9bg_.size = sizeof(tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ*);
NTI_uy40IH3avHBB9chAP6wAq9bg_.kind = 22;
NTI_uy40IH3avHBB9chAP6wAq9bg_.base = (&NTI_X8aacFQVnMMG3eJMkbZvPQ_);
NTI_uy40IH3avHBB9chAP6wAq9bg_.marker = Marker_tyRef_uy40IH3avHBB9chAP6wAq9bg;
TM_rwLMXCJFajv59bjeX5ComAQ_0[5].kind = 1;
TM_rwLMXCJFajv59bjeX5ComAQ_0[5].offset = offsetof(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g, components);
TM_rwLMXCJFajv59bjeX5ComAQ_0[5].typ = (&NTI_9ab5RwcLehRlj0xrxSya29cQ_);
TM_rwLMXCJFajv59bjeX5ComAQ_0[5].name = "components";
TM_rwLMXCJFajv59bjeX5ComAQ_0[2].len = 3; TM_rwLMXCJFajv59bjeX5ComAQ_0[2].kind = 2; TM_rwLMXCJFajv59bjeX5ComAQ_0[2].sons = &TM_rwLMXCJFajv59bjeX5ComAQ_3[0];
NTI_9bwdc6iyZGiId8gvyONht0g_.node = &TM_rwLMXCJFajv59bjeX5ComAQ_0[2];
NTI_R9b3hfapA2py1I4YfWk0zBA_.size = sizeof(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g*);
NTI_R9b3hfapA2py1I4YfWk0zBA_.kind = 22;
NTI_R9b3hfapA2py1I4YfWk0zBA_.base = (&NTI_9bwdc6iyZGiId8gvyONht0g_);
NTI_R9b3hfapA2py1I4YfWk0zBA_.marker = Marker_tyRef_R9b3hfapA2py1I4YfWk0zBA;
NTI_sxV7BWZ9cww0pVdm9bqsswoA_.size = sizeof(tySequence_sxV7BWZ9cww0pVdm9bqsswoA*);
NTI_sxV7BWZ9cww0pVdm9bqsswoA_.kind = 24;
NTI_sxV7BWZ9cww0pVdm9bqsswoA_.base = (&NTI_R9b3hfapA2py1I4YfWk0zBA_);
NTI_sxV7BWZ9cww0pVdm9bqsswoA_.marker = Marker_tySequence_sxV7BWZ9cww0pVdm9bqsswoA;
TM_rwLMXCJFajv59bjeX5ComAQ_0[1].kind = 1;
TM_rwLMXCJFajv59bjeX5ComAQ_0[1].offset = offsetof(tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg, entities);
TM_rwLMXCJFajv59bjeX5ComAQ_0[1].typ = (&NTI_sxV7BWZ9cww0pVdm9bqsswoA_);
TM_rwLMXCJFajv59bjeX5ComAQ_0[1].name = "entities";
TM_rwLMXCJFajv59bjeX5ComAQ_2[1] = &TM_rwLMXCJFajv59bjeX5ComAQ_0[7];
NTI_bUxkNAwYdPyt85kuMYOTKw_.size = sizeof(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw);
NTI_bUxkNAwYdPyt85kuMYOTKw_.kind = 18;
NTI_bUxkNAwYdPyt85kuMYOTKw_.base = 0;
TM_rwLMXCJFajv59bjeX5ComAQ_4[0] = &TM_rwLMXCJFajv59bjeX5ComAQ_0[9];
TM_rwLMXCJFajv59bjeX5ComAQ_0[9].kind = 1;
TM_rwLMXCJFajv59bjeX5ComAQ_0[9].offset = offsetof(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw, worldRef);
TM_rwLMXCJFajv59bjeX5ComAQ_0[9].typ = (&NTI_kFs8aoCoWWyGs19aEbPaOUg_);
TM_rwLMXCJFajv59bjeX5ComAQ_0[9].name = "worldRef";
TM_rwLMXCJFajv59bjeX5ComAQ_4[1] = &TM_rwLMXCJFajv59bjeX5ComAQ_0[10];
NTI_sM4lkSb7zS6F7OVMvW9cffQ_.size = sizeof(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*);
NTI_sM4lkSb7zS6F7OVMvW9cffQ_.kind = 24;
NTI_sM4lkSb7zS6F7OVMvW9cffQ_.base = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
NTI_sM4lkSb7zS6F7OVMvW9cffQ_.flags = 2;
NTI_sM4lkSb7zS6F7OVMvW9cffQ_.marker = Marker_tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
TM_rwLMXCJFajv59bjeX5ComAQ_0[10].kind = 1;
TM_rwLMXCJFajv59bjeX5ComAQ_0[10].offset = offsetof(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw, matchList);
TM_rwLMXCJFajv59bjeX5ComAQ_0[10].typ = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_);
TM_rwLMXCJFajv59bjeX5ComAQ_0[10].name = "matchList";
TM_rwLMXCJFajv59bjeX5ComAQ_4[2] = &TM_rwLMXCJFajv59bjeX5ComAQ_0[11];
NTI_Ulk9cd4UOHLw9aKiI8pa0uaQ_.size = sizeof(tyTuple_2uzTbg8jwom7zHhmM2RgHg);
NTI_Ulk9cd4UOHLw9aKiI8pa0uaQ_.kind = 18;
NTI_Ulk9cd4UOHLw9aKiI8pa0uaQ_.base = 0;
TM_rwLMXCJFajv59bjeX5ComAQ_5[0] = &TM_rwLMXCJFajv59bjeX5ComAQ_0[13];
TM_rwLMXCJFajv59bjeX5ComAQ_0[13].kind = 1;
TM_rwLMXCJFajv59bjeX5ComAQ_0[13].offset = offsetof(tyTuple_2uzTbg8jwom7zHhmM2RgHg, Field0);
TM_rwLMXCJFajv59bjeX5ComAQ_0[13].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_rwLMXCJFajv59bjeX5ComAQ_0[13].name = "Field0";
TM_rwLMXCJFajv59bjeX5ComAQ_5[1] = &TM_rwLMXCJFajv59bjeX5ComAQ_0[14];
NTI_sO5O0Qy9bzKs0atwA6HUBAw_.size = sizeof(tyObject_Env_ecsdotnim__sO5O0Qy9bzKs0atwA6HUBAw);
NTI_sO5O0Qy9bzKs0atwA6HUBAw_.kind = 17;
NTI_sO5O0Qy9bzKs0atwA6HUBAw_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_sO5O0Qy9bzKs0atwA6HUBAw_.flags = 1;
TM_rwLMXCJFajv59bjeX5ComAQ_0[15].len = 0; TM_rwLMXCJFajv59bjeX5ComAQ_0[15].kind = 2;
NTI_sO5O0Qy9bzKs0atwA6HUBAw_.node = &TM_rwLMXCJFajv59bjeX5ComAQ_0[15];
NTI_58EFneeS9at7cA541QCoGAw_.size = sizeof(tyObject_Env_ecsdotnim__sO5O0Qy9bzKs0atwA6HUBAw*);
NTI_58EFneeS9at7cA541QCoGAw_.kind = 22;
NTI_58EFneeS9at7cA541QCoGAw_.base = (&NTI_sO5O0Qy9bzKs0atwA6HUBAw_);
NTI_58EFneeS9at7cA541QCoGAw_.marker = Marker_tyRef_58EFneeS9at7cA541QCoGAw;
TM_rwLMXCJFajv59bjeX5ComAQ_0[14].kind = 1;
TM_rwLMXCJFajv59bjeX5ComAQ_0[14].offset = offsetof(tyTuple_2uzTbg8jwom7zHhmM2RgHg, Field1);
TM_rwLMXCJFajv59bjeX5ComAQ_0[14].typ = (&NTI_58EFneeS9at7cA541QCoGAw_);
TM_rwLMXCJFajv59bjeX5ComAQ_0[14].name = "Field1";
TM_rwLMXCJFajv59bjeX5ComAQ_0[12].len = 2; TM_rwLMXCJFajv59bjeX5ComAQ_0[12].kind = 2; TM_rwLMXCJFajv59bjeX5ComAQ_0[12].sons = &TM_rwLMXCJFajv59bjeX5ComAQ_5[0];
NTI_Ulk9cd4UOHLw9aKiI8pa0uaQ_.node = &TM_rwLMXCJFajv59bjeX5ComAQ_0[12];
TM_rwLMXCJFajv59bjeX5ComAQ_0[11].kind = 1;
TM_rwLMXCJFajv59bjeX5ComAQ_0[11].offset = offsetof(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw, preUpdate);
TM_rwLMXCJFajv59bjeX5ComAQ_0[11].typ = (&NTI_Ulk9cd4UOHLw9aKiI8pa0uaQ_);
TM_rwLMXCJFajv59bjeX5ComAQ_0[11].name = "preUpdate";
TM_rwLMXCJFajv59bjeX5ComAQ_4[3] = &TM_rwLMXCJFajv59bjeX5ComAQ_0[16];
NTI_LTibXkW8wgZIS6uZJDSRwg_.size = sizeof(tyTuple_2uzTbg8jwom7zHhmM2RgHg);
NTI_LTibXkW8wgZIS6uZJDSRwg_.kind = 18;
NTI_LTibXkW8wgZIS6uZJDSRwg_.base = 0;
TM_rwLMXCJFajv59bjeX5ComAQ_6[0] = &TM_rwLMXCJFajv59bjeX5ComAQ_0[18];
TM_rwLMXCJFajv59bjeX5ComAQ_0[18].kind = 1;
TM_rwLMXCJFajv59bjeX5ComAQ_0[18].offset = offsetof(tyTuple_2uzTbg8jwom7zHhmM2RgHg, Field0);
TM_rwLMXCJFajv59bjeX5ComAQ_0[18].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_rwLMXCJFajv59bjeX5ComAQ_0[18].name = "Field0";
TM_rwLMXCJFajv59bjeX5ComAQ_6[1] = &TM_rwLMXCJFajv59bjeX5ComAQ_0[19];
TM_rwLMXCJFajv59bjeX5ComAQ_0[19].kind = 1;
TM_rwLMXCJFajv59bjeX5ComAQ_0[19].offset = offsetof(tyTuple_2uzTbg8jwom7zHhmM2RgHg, Field1);
TM_rwLMXCJFajv59bjeX5ComAQ_0[19].typ = (&NTI_58EFneeS9at7cA541QCoGAw_);
TM_rwLMXCJFajv59bjeX5ComAQ_0[19].name = "Field1";
TM_rwLMXCJFajv59bjeX5ComAQ_0[17].len = 2; TM_rwLMXCJFajv59bjeX5ComAQ_0[17].kind = 2; TM_rwLMXCJFajv59bjeX5ComAQ_0[17].sons = &TM_rwLMXCJFajv59bjeX5ComAQ_6[0];
NTI_LTibXkW8wgZIS6uZJDSRwg_.node = &TM_rwLMXCJFajv59bjeX5ComAQ_0[17];
TM_rwLMXCJFajv59bjeX5ComAQ_0[16].kind = 1;
TM_rwLMXCJFajv59bjeX5ComAQ_0[16].offset = offsetof(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw, load);
TM_rwLMXCJFajv59bjeX5ComAQ_0[16].typ = (&NTI_LTibXkW8wgZIS6uZJDSRwg_);
TM_rwLMXCJFajv59bjeX5ComAQ_0[16].name = "load";
TM_rwLMXCJFajv59bjeX5ComAQ_4[4] = &TM_rwLMXCJFajv59bjeX5ComAQ_0[20];
TM_rwLMXCJFajv59bjeX5ComAQ_0[20].kind = 1;
TM_rwLMXCJFajv59bjeX5ComAQ_0[20].offset = offsetof(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw, update);
TM_rwLMXCJFajv59bjeX5ComAQ_0[20].typ = (&NTI_LTibXkW8wgZIS6uZJDSRwg_);
TM_rwLMXCJFajv59bjeX5ComAQ_0[20].name = "update";
TM_rwLMXCJFajv59bjeX5ComAQ_4[5] = &TM_rwLMXCJFajv59bjeX5ComAQ_0[21];
TM_rwLMXCJFajv59bjeX5ComAQ_0[21].kind = 1;
TM_rwLMXCJFajv59bjeX5ComAQ_0[21].offset = offsetof(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw, draw);
TM_rwLMXCJFajv59bjeX5ComAQ_0[21].typ = (&NTI_LTibXkW8wgZIS6uZJDSRwg_);
TM_rwLMXCJFajv59bjeX5ComAQ_0[21].name = "draw";
TM_rwLMXCJFajv59bjeX5ComAQ_4[6] = &TM_rwLMXCJFajv59bjeX5ComAQ_0[22];
TM_rwLMXCJFajv59bjeX5ComAQ_0[22].kind = 1;
TM_rwLMXCJFajv59bjeX5ComAQ_0[22].offset = offsetof(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw, destroy);
TM_rwLMXCJFajv59bjeX5ComAQ_0[22].typ = (&NTI_LTibXkW8wgZIS6uZJDSRwg_);
TM_rwLMXCJFajv59bjeX5ComAQ_0[22].name = "destroy";
TM_rwLMXCJFajv59bjeX5ComAQ_4[7] = &TM_rwLMXCJFajv59bjeX5ComAQ_0[23];
TM_rwLMXCJFajv59bjeX5ComAQ_0[23].kind = 1;
TM_rwLMXCJFajv59bjeX5ComAQ_0[23].offset = offsetof(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw, preDraw);
TM_rwLMXCJFajv59bjeX5ComAQ_0[23].typ = (&NTI_Ulk9cd4UOHLw9aKiI8pa0uaQ_);
TM_rwLMXCJFajv59bjeX5ComAQ_0[23].name = "preDraw";
TM_rwLMXCJFajv59bjeX5ComAQ_0[8].len = 8; TM_rwLMXCJFajv59bjeX5ComAQ_0[8].kind = 2; TM_rwLMXCJFajv59bjeX5ComAQ_0[8].sons = &TM_rwLMXCJFajv59bjeX5ComAQ_4[0];
NTI_bUxkNAwYdPyt85kuMYOTKw_.node = &TM_rwLMXCJFajv59bjeX5ComAQ_0[8];
NTI_kqRkyKwWUGhRwkJfLvzABw_.size = sizeof(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw*);
NTI_kqRkyKwWUGhRwkJfLvzABw_.kind = 22;
NTI_kqRkyKwWUGhRwkJfLvzABw_.base = (&NTI_bUxkNAwYdPyt85kuMYOTKw_);
NTI_kqRkyKwWUGhRwkJfLvzABw_.marker = Marker_tyRef_kqRkyKwWUGhRwkJfLvzABw;
NTI_siX5xEDqFuO4i5rOs7ZBlg_.size = sizeof(tySequence_siX5xEDqFuO4i5rOs7ZBlg*);
NTI_siX5xEDqFuO4i5rOs7ZBlg_.kind = 24;
NTI_siX5xEDqFuO4i5rOs7ZBlg_.base = (&NTI_kqRkyKwWUGhRwkJfLvzABw_);
NTI_siX5xEDqFuO4i5rOs7ZBlg_.marker = Marker_tySequence_siX5xEDqFuO4i5rOs7ZBlg;
TM_rwLMXCJFajv59bjeX5ComAQ_0[7].kind = 1;
TM_rwLMXCJFajv59bjeX5ComAQ_0[7].offset = offsetof(tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg, systems);
TM_rwLMXCJFajv59bjeX5ComAQ_0[7].typ = (&NTI_siX5xEDqFuO4i5rOs7ZBlg_);
TM_rwLMXCJFajv59bjeX5ComAQ_0[7].name = "systems";
TM_rwLMXCJFajv59bjeX5ComAQ_0[0].len = 2; TM_rwLMXCJFajv59bjeX5ComAQ_0[0].kind = 2; TM_rwLMXCJFajv59bjeX5ComAQ_0[0].sons = &TM_rwLMXCJFajv59bjeX5ComAQ_2[0];
NTI_KccFVpsYw1e2AJ3Xnk9cAfg_.node = &TM_rwLMXCJFajv59bjeX5ComAQ_0[0];
NTI_kFs8aoCoWWyGs19aEbPaOUg_.size = sizeof(tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg*);
NTI_kFs8aoCoWWyGs19aEbPaOUg_.kind = 22;
NTI_kFs8aoCoWWyGs19aEbPaOUg_.base = (&NTI_KccFVpsYw1e2AJ3Xnk9cAfg_);
NTI_kFs8aoCoWWyGs19aEbPaOUg_.marker = Marker_tyRef_kFs8aoCoWWyGs19aEbPaOUg;
}

