/* Generated by Nim Compiler v0.18.1 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/dustin/Documents/Nim/lib -o /home/dustin/Documents/Nim_Projects/VectorGuy/src/nimcache/VectorGuy_renderable.o /home/dustin/Documents/Nim_Projects/VectorGuy/src/nimcache/VectorGuy_renderable.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g;
typedef struct tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ;
typedef struct tyObject_RectangleComponentcolonObjectType__Td9aXtPuWzNdKHrUL9cPq5lQ tyObject_RectangleComponentcolonObjectType__Td9aXtPuWzNdKHrUL9cPq5lQ;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A;
typedef struct tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ;
typedef struct tyObject_DrawablecolonObjectType__2ltTHdgBChx9cgtqnSkskXA tyObject_DrawablecolonObjectType__2ltTHdgBChx9cgtqnSkskXA;
typedef struct tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ;
typedef struct RootObj RootObj;
typedef struct tyTuple_0vYzovSm9aKYybyF8MRuBJQ tyTuple_0vYzovSm9aKYybyF8MRuBJQ;
typedef struct tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e, void* ClE_0);
void* ClE_0;
} tyProc_LTibXkW8wgZIS6uZJDSRwg;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, void* ClE_0);
void* ClE_0;
} tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ;
typedef N_CLOSURE_PTR(void, TM_7pfbsA4Z15mK79cUgzyqfaA_7) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e, void* ClE_0);
typedef N_CLOSURE_PTR(void, TM_7pfbsA4Z15mK79cUgzyqfaA_8) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, void* ClE_0);
typedef N_CLOSURE_PTR(void, TM_7pfbsA4Z15mK79cUgzyqfaA_9) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e, void* ClE_0);
typedef N_CLOSURE_PTR(void, TM_7pfbsA4Z15mK79cUgzyqfaA_10) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e, void* ClE_0);
typedef N_CLOSURE_PTR(void, TM_7pfbsA4Z15mK79cUgzyqfaA_11) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e, void* ClE_0);
typedef N_CLOSURE_PTR(void, TM_7pfbsA4Z15mK79cUgzyqfaA_12) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, void* ClE_0);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef N_CLOSURE_PTR(void, TM_7pfbsA4Z15mK79cUgzyqfaA_17) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e, void* ClE_0);
typedef N_CLOSURE_PTR(void, TM_7pfbsA4Z15mK79cUgzyqfaA_18) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, void* ClE_0);
typedef N_CLOSURE_PTR(void, TM_7pfbsA4Z15mK79cUgzyqfaA_19) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e, void* ClE_0);
struct RootObj {
TNimType* m_type;
};
struct tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ {
  RootObj Sup;
};
struct tyTuple_0vYzovSm9aKYybyF8MRuBJQ {
NF Field0;
NF Field1;
NF Field2;
NF Field3;
};
struct tyObject_DrawablecolonObjectType__2ltTHdgBChx9cgtqnSkskXA {
  tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ Sup;
tyTuple_0vYzovSm9aKYybyF8MRuBJQ color;
};
struct tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A {
  tyObject_DrawablecolonObjectType__2ltTHdgBChx9cgtqnSkskXA Sup;
tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ* image;
tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ* region;
NIM_BOOL flip;
};
typedef N_CLOSURE_PTR(void, TM_7pfbsA4Z15mK79cUgzyqfaA_20) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e, void* ClE_0);
typedef N_CLOSURE_PTR(void, TM_7pfbsA4Z15mK79cUgzyqfaA_21) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e, void* ClE_0);
typedef N_CLOSURE_PTR(void, TM_7pfbsA4Z15mK79cUgzyqfaA_22) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, void* ClE_0);
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_7pfbsA4Z15mK79cUgzyqfaA_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_LIB_PRIVATE N_NIMCALL(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw*, createSystem_ZIEE3eqxo9anA1Qzcbrx5Vg)(tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg* world, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* matchlist, tyProc_LTibXkW8wgZIS6uZJDSRwg load, tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ preUpdate, tyProc_LTibXkW8wgZIS6uZJDSRwg update, tyProc_LTibXkW8wgZIS6uZJDSRwg draw, tyProc_LTibXkW8wgZIS6uZJDSRwg destroy, tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ preDraw);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous__yNzqln4x6YPLtQIe7kol7A)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* sys, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, default_preUpdate_bubQNMeUwRg1mVj2B77VVg)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s);
N_LIB_PRIVATE N_NIMCALL(void, default_update_yWuOcLIgmhG0YcAceats8w_3)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous__OswlItB0dagvKT5BPtRAvQ)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e);
N_LIB_PRIVATE N_NIMCALL(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ*, get_UpICIghUTrvN3fZF3drLBQ)(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self);
N_LIB_PRIVATE N_NIMCALL(tyObject_RectangleComponentcolonObjectType__Td9aXtPuWzNdKHrUL9cPq5lQ*, get_2dD9bkJZHXCId7ayQ4FqPRQ)(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self);
N_LIB_PRIVATE N_NIMCALL(void, rect_KBJ7sNgV4lSRrRq4ulkq6w_2)(void* renderer, NF x, NF y, NF w, NF h, NF rot);
N_LIB_PRIVATE N_NIMCALL(NF, x_GjB2bcom6jNDdYSzGflP3w)(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* b);
N_LIB_PRIVATE N_NIMCALL(NF, y_GjB2bcom6jNDdYSzGflP3w_2)(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* b);
N_LIB_PRIVATE N_NIMCALL(NF, width_GjB2bcom6jNDdYSzGflP3w_3)(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* b);
N_LIB_PRIVATE N_NIMCALL(NF, height_GjB2bcom6jNDdYSzGflP3w_4)(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* b);
N_LIB_PRIVATE N_NIMCALL(void, default_destroy_yWuOcLIgmhG0YcAceats8w_2)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e);
N_LIB_PRIVATE N_NIMCALL(void, default_preDraw_bubQNMeUwRg1mVj2B77VVg_2)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_NIMCALL(void, TM_7pfbsA4Z15mK79cUgzyqfaA_13)(void);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous__yNzqln4x6YPLtQIe7kol7A_2)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* sys, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous__OswlItB0dagvKT5BPtRAvQ_2)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e);
N_LIB_PRIVATE N_NIMCALL(tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A*, get_RSEbINeSUjOPFVLfePsoHQ)(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, draw_FIJoyt7S8QvQbuv4xQGSGQ)(void* renderer, tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ* obj, tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ* reg, NF x, NF y, NF rot, NIM_BOOL flip, NI ox, NI oy);
static N_NIMCALL(void, Marker_tyRef_nBvHJ1Rw03MS6yxDbJRrvQ)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* RectRendererSystem_slzycyN4rjTVsn8blgm9avQ;
extern TNimType NTI_kqRkyKwWUGhRwkJfLvzABw_;
extern tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg* world_M14QSo1egm66WmikxMh52g;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern void* renderer_Ll7o3xAsk26H2TKOmIioZg;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* SpriteRendererSystem_VbKBktB615AEkOITJ6hBUw;
extern TNimType NTI_X8aacFQVnMMG3eJMkbZvPQ_;
TNimType NTI_2ltTHdgBChx9cgtqnSkskXA_;
TNimType NTI_0vYzovSm9aKYybyF8MRuBJQ_;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
TNimType NTI_N79boNLVsc9bx7gvK8hUee8A_;
extern TNimType NTI_0kDVS9b1UyEqr8DfAGXwn9cQ_;
extern TNimType NTI_u6eWcr48DqP0Ue9cUPPUypg_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
TNimType NTI_nBvHJ1Rw03MS6yxDbJRrvQ_;
STRING_LITERAL(TM_7pfbsA4Z15mK79cUgzyqfaA_4, "Body", 4);
STRING_LITERAL(TM_7pfbsA4Z15mK79cUgzyqfaA_5, "RectangleComponent", 18);
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[2];
} TM_7pfbsA4Z15mK79cUgzyqfaA_6 = {{2, 2}, {((NimStringDesc*) &TM_7pfbsA4Z15mK79cUgzyqfaA_4),
((NimStringDesc*) &TM_7pfbsA4Z15mK79cUgzyqfaA_5)}};
NIM_CONST tySequence_sM4lkSb7zS6F7OVMvW9cffQ* TM_7pfbsA4Z15mK79cUgzyqfaA_3 = ((tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)&TM_7pfbsA4Z15mK79cUgzyqfaA_6);
STRING_LITERAL(TM_7pfbsA4Z15mK79cUgzyqfaA_15, "Sprite", 6);
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[2];
} TM_7pfbsA4Z15mK79cUgzyqfaA_16 = {{2, 2}, {((NimStringDesc*) &TM_7pfbsA4Z15mK79cUgzyqfaA_4),
((NimStringDesc*) &TM_7pfbsA4Z15mK79cUgzyqfaA_15)}};
NIM_CONST tySequence_sM4lkSb7zS6F7OVMvW9cffQ* TM_7pfbsA4Z15mK79cUgzyqfaA_14 = ((tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)&TM_7pfbsA4Z15mK79cUgzyqfaA_16);
static N_NIMCALL(void, TM_7pfbsA4Z15mK79cUgzyqfaA_2)(void) {
	nimGCvisit((void*)RectRendererSystem_slzycyN4rjTVsn8blgm9avQ, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(void, colonanonymous__yNzqln4x6YPLtQIe7kol7A)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* sys, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self) {
	nimfr_(":anonymous", "renderable.nim");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, colonanonymous__OswlItB0dagvKT5BPtRAvQ)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e) {
	tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* body;
	tyObject_RectangleComponentcolonObjectType__Td9aXtPuWzNdKHrUL9cPq5lQ* rect;
	NF T1_;
	NF T2_;
	NF T3_;
	NF T4_;
	nimfr_(":anonymous", "renderable.nim");
	nimln_(38, "renderable.nim");
	body = get_UpICIghUTrvN3fZF3drLBQ(e);
	nimln_(39, "renderable.nim");
	rect = get_2dD9bkJZHXCId7ayQ4FqPRQ(e);
	nimln_(41, "renderable.nim");
	T1_ = (NF)0;
	T1_ = x_GjB2bcom6jNDdYSzGflP3w(body);
	T2_ = (NF)0;
	T2_ = y_GjB2bcom6jNDdYSzGflP3w_2(body);
	T3_ = (NF)0;
	T3_ = width_GjB2bcom6jNDdYSzGflP3w_3(body);
	T4_ = (NF)0;
	T4_ = height_GjB2bcom6jNDdYSzGflP3w_4(body);
	rect_KBJ7sNgV4lSRrRq4ulkq6w_2(renderer_Ll7o3xAsk26H2TKOmIioZg, T1_, T2_, T3_, T4_, 0.0);
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(400, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(400, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}
static N_NIMCALL(void, TM_7pfbsA4Z15mK79cUgzyqfaA_13)(void) {
	nimGCvisit((void*)SpriteRendererSystem_VbKBktB615AEkOITJ6hBUw, 0);
}

N_LIB_PRIVATE N_NIMCALL(void, colonanonymous__yNzqln4x6YPLtQIe7kol7A_2)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* sys, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self) {
	nimfr_(":anonymous", "renderable.nim");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, colonanonymous__OswlItB0dagvKT5BPtRAvQ_2)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e) {
	tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* body;
	tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A* sprite;
	tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ* img;
	tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ* reg;
	NF T1_;
	NF T2_;
	NIM_BOOL T3_;
	nimfr_(":anonymous", "renderable.nim");
	nimln_(52, "renderable.nim");
	body = get_UpICIghUTrvN3fZF3drLBQ(e);
	nimln_(53, "renderable.nim");
	sprite = get_RSEbINeSUjOPFVLfePsoHQ(e);
	nimln_(55, "renderable.nim");
	img = (*sprite).image;
	nimln_(56, "renderable.nim");
	reg = (*sprite).region;
	nimln_(58, "renderable.nim");
	T1_ = (NF)0;
	T1_ = x_GjB2bcom6jNDdYSzGflP3w(body);
	T2_ = (NF)0;
	T2_ = y_GjB2bcom6jNDdYSzGflP3w_2(body);
	T3_ = (NIM_BOOL)0;
	T3_ = draw_FIJoyt7S8QvQbuv4xQGSGQ(renderer_Ll7o3xAsk26H2TKOmIioZg, img, reg, T1_, T2_, 0.0, (*sprite).flip, ((NI) -1), ((NI) -1));
	popFrame();
}
static N_NIMCALL(void, Marker_tyRef_nBvHJ1Rw03MS6yxDbJRrvQ)(void* p, NI op) {
	tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A* a;
	a = (tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A*)p;
	nimGCvisit((void*)(*a).image, op);
	nimGCvisit((void*)(*a).region, op);
}

N_LIB_PRIVATE N_NIMCALL(tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A*, newSprite_k2AkJjuAquo5x16c1eP9aBA)(tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ* img, tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ* reg) {
	tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A* result;
	tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A* T1_;
	nimfr_("newSprite", "renderable.nim");
	result = (tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A*)0;
	nimln_(25, "renderable.nim");
	T1_ = (tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A*)0;
	T1_ = (tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A*) newObj((&NTI_nBvHJ1Rw03MS6yxDbJRrvQ_), sizeof(tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A));
	(*T1_).Sup.Sup.Sup.m_type = (&NTI_N79boNLVsc9bx7gvK8hUee8A_);
	asgnRef((void**) (&(*T1_).image), img);
	asgnRef((void**) (&(*T1_).region), reg);
	(*T1_).flip = NIM_FALSE;
	result = T1_;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, VectorGuy_renderableInit000)(void) {
	tyProc_LTibXkW8wgZIS6uZJDSRwg T1_;
	tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ T2_;
	tyProc_LTibXkW8wgZIS6uZJDSRwg T3_;
	tyProc_LTibXkW8wgZIS6uZJDSRwg T4_;
	tyProc_LTibXkW8wgZIS6uZJDSRwg T5_;
	tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ T6_;
	tyProc_LTibXkW8wgZIS6uZJDSRwg T7_;
	tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ T8_;
	tyProc_LTibXkW8wgZIS6uZJDSRwg T9_;
	tyProc_LTibXkW8wgZIS6uZJDSRwg T10_;
	tyProc_LTibXkW8wgZIS6uZJDSRwg T11_;
	tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ T12_;
	nimfr_("renderable", "renderable.nim");
nimRegisterGlobalMarker(TM_7pfbsA4Z15mK79cUgzyqfaA_2);
nimRegisterGlobalMarker(TM_7pfbsA4Z15mK79cUgzyqfaA_13);
	nimln_(32, "renderable.nim");
	memset((void*)(&T1_), 0, sizeof(tyProc_LTibXkW8wgZIS6uZJDSRwg));
	T1_.ClP_0 = ((TM_7pfbsA4Z15mK79cUgzyqfaA_7) (colonanonymous__yNzqln4x6YPLtQIe7kol7A)); T1_.ClE_0 = NIM_NIL;
	memset((void*)(&T2_), 0, sizeof(tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ));
	T2_.ClP_0 = ((TM_7pfbsA4Z15mK79cUgzyqfaA_8) (default_preUpdate_bubQNMeUwRg1mVj2B77VVg)); T2_.ClE_0 = NIM_NIL;
	memset((void*)(&T3_), 0, sizeof(tyProc_LTibXkW8wgZIS6uZJDSRwg));
	T3_.ClP_0 = ((TM_7pfbsA4Z15mK79cUgzyqfaA_9) (default_update_yWuOcLIgmhG0YcAceats8w_3)); T3_.ClE_0 = NIM_NIL;
	memset((void*)(&T4_), 0, sizeof(tyProc_LTibXkW8wgZIS6uZJDSRwg));
	T4_.ClP_0 = ((TM_7pfbsA4Z15mK79cUgzyqfaA_10) (colonanonymous__OswlItB0dagvKT5BPtRAvQ)); T4_.ClE_0 = NIM_NIL;
	memset((void*)(&T5_), 0, sizeof(tyProc_LTibXkW8wgZIS6uZJDSRwg));
	T5_.ClP_0 = ((TM_7pfbsA4Z15mK79cUgzyqfaA_11) (default_destroy_yWuOcLIgmhG0YcAceats8w_2)); T5_.ClE_0 = NIM_NIL;
	memset((void*)(&T6_), 0, sizeof(tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ));
	T6_.ClP_0 = ((TM_7pfbsA4Z15mK79cUgzyqfaA_12) (default_preDraw_bubQNMeUwRg1mVj2B77VVg_2)); T6_.ClE_0 = NIM_NIL;
	asgnRef((void**) (&RectRendererSystem_slzycyN4rjTVsn8blgm9avQ), createSystem_ZIEE3eqxo9anA1Qzcbrx5Vg(world_M14QSo1egm66WmikxMh52g, TM_7pfbsA4Z15mK79cUgzyqfaA_3, T1_, T2_, T3_, T4_, T5_, T6_));
	nimln_(44, "renderable.nim");
	memset((void*)(&T7_), 0, sizeof(tyProc_LTibXkW8wgZIS6uZJDSRwg));
	T7_.ClP_0 = ((TM_7pfbsA4Z15mK79cUgzyqfaA_17) (colonanonymous__yNzqln4x6YPLtQIe7kol7A_2)); T7_.ClE_0 = NIM_NIL;
	memset((void*)(&T8_), 0, sizeof(tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ));
	T8_.ClP_0 = ((TM_7pfbsA4Z15mK79cUgzyqfaA_18) (default_preUpdate_bubQNMeUwRg1mVj2B77VVg)); T8_.ClE_0 = NIM_NIL;
	memset((void*)(&T9_), 0, sizeof(tyProc_LTibXkW8wgZIS6uZJDSRwg));
	T9_.ClP_0 = ((TM_7pfbsA4Z15mK79cUgzyqfaA_19) (default_update_yWuOcLIgmhG0YcAceats8w_3)); T9_.ClE_0 = NIM_NIL;
	memset((void*)(&T10_), 0, sizeof(tyProc_LTibXkW8wgZIS6uZJDSRwg));
	T10_.ClP_0 = ((TM_7pfbsA4Z15mK79cUgzyqfaA_20) (colonanonymous__OswlItB0dagvKT5BPtRAvQ_2)); T10_.ClE_0 = NIM_NIL;
	memset((void*)(&T11_), 0, sizeof(tyProc_LTibXkW8wgZIS6uZJDSRwg));
	T11_.ClP_0 = ((TM_7pfbsA4Z15mK79cUgzyqfaA_21) (default_destroy_yWuOcLIgmhG0YcAceats8w_2)); T11_.ClE_0 = NIM_NIL;
	memset((void*)(&T12_), 0, sizeof(tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ));
	T12_.ClP_0 = ((TM_7pfbsA4Z15mK79cUgzyqfaA_22) (default_preDraw_bubQNMeUwRg1mVj2B77VVg_2)); T12_.ClE_0 = NIM_NIL;
	asgnRef((void**) (&SpriteRendererSystem_VbKBktB615AEkOITJ6hBUw), createSystem_ZIEE3eqxo9anA1Qzcbrx5Vg(world_M14QSo1egm66WmikxMh52g, TM_7pfbsA4Z15mK79cUgzyqfaA_14, T7_, T8_, T9_, T10_, T11_, T12_));
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, VectorGuy_renderableDatInit000)(void) {
static TNimNode* TM_7pfbsA4Z15mK79cUgzyqfaA_23[4];
static TNimNode* TM_7pfbsA4Z15mK79cUgzyqfaA_24[3];
static TNimNode TM_7pfbsA4Z15mK79cUgzyqfaA_0[10];
NTI_2ltTHdgBChx9cgtqnSkskXA_.size = sizeof(tyObject_DrawablecolonObjectType__2ltTHdgBChx9cgtqnSkskXA);
NTI_2ltTHdgBChx9cgtqnSkskXA_.kind = 17;
NTI_2ltTHdgBChx9cgtqnSkskXA_.base = (&NTI_X8aacFQVnMMG3eJMkbZvPQ_);
NTI_2ltTHdgBChx9cgtqnSkskXA_.flags = 1;
NTI_0vYzovSm9aKYybyF8MRuBJQ_.size = sizeof(tyTuple_0vYzovSm9aKYybyF8MRuBJQ);
NTI_0vYzovSm9aKYybyF8MRuBJQ_.kind = 18;
NTI_0vYzovSm9aKYybyF8MRuBJQ_.base = 0;
NTI_0vYzovSm9aKYybyF8MRuBJQ_.flags = 3;
TM_7pfbsA4Z15mK79cUgzyqfaA_23[0] = &TM_7pfbsA4Z15mK79cUgzyqfaA_0[2];
TM_7pfbsA4Z15mK79cUgzyqfaA_0[2].kind = 1;
TM_7pfbsA4Z15mK79cUgzyqfaA_0[2].offset = offsetof(tyTuple_0vYzovSm9aKYybyF8MRuBJQ, Field0);
TM_7pfbsA4Z15mK79cUgzyqfaA_0[2].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_7pfbsA4Z15mK79cUgzyqfaA_0[2].name = "Field0";
TM_7pfbsA4Z15mK79cUgzyqfaA_23[1] = &TM_7pfbsA4Z15mK79cUgzyqfaA_0[3];
TM_7pfbsA4Z15mK79cUgzyqfaA_0[3].kind = 1;
TM_7pfbsA4Z15mK79cUgzyqfaA_0[3].offset = offsetof(tyTuple_0vYzovSm9aKYybyF8MRuBJQ, Field1);
TM_7pfbsA4Z15mK79cUgzyqfaA_0[3].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_7pfbsA4Z15mK79cUgzyqfaA_0[3].name = "Field1";
TM_7pfbsA4Z15mK79cUgzyqfaA_23[2] = &TM_7pfbsA4Z15mK79cUgzyqfaA_0[4];
TM_7pfbsA4Z15mK79cUgzyqfaA_0[4].kind = 1;
TM_7pfbsA4Z15mK79cUgzyqfaA_0[4].offset = offsetof(tyTuple_0vYzovSm9aKYybyF8MRuBJQ, Field2);
TM_7pfbsA4Z15mK79cUgzyqfaA_0[4].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_7pfbsA4Z15mK79cUgzyqfaA_0[4].name = "Field2";
TM_7pfbsA4Z15mK79cUgzyqfaA_23[3] = &TM_7pfbsA4Z15mK79cUgzyqfaA_0[5];
TM_7pfbsA4Z15mK79cUgzyqfaA_0[5].kind = 1;
TM_7pfbsA4Z15mK79cUgzyqfaA_0[5].offset = offsetof(tyTuple_0vYzovSm9aKYybyF8MRuBJQ, Field3);
TM_7pfbsA4Z15mK79cUgzyqfaA_0[5].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_7pfbsA4Z15mK79cUgzyqfaA_0[5].name = "Field3";
TM_7pfbsA4Z15mK79cUgzyqfaA_0[1].len = 4; TM_7pfbsA4Z15mK79cUgzyqfaA_0[1].kind = 2; TM_7pfbsA4Z15mK79cUgzyqfaA_0[1].sons = &TM_7pfbsA4Z15mK79cUgzyqfaA_23[0];
NTI_0vYzovSm9aKYybyF8MRuBJQ_.node = &TM_7pfbsA4Z15mK79cUgzyqfaA_0[1];
TM_7pfbsA4Z15mK79cUgzyqfaA_0[0].kind = 1;
TM_7pfbsA4Z15mK79cUgzyqfaA_0[0].offset = offsetof(tyObject_DrawablecolonObjectType__2ltTHdgBChx9cgtqnSkskXA, color);
TM_7pfbsA4Z15mK79cUgzyqfaA_0[0].typ = (&NTI_0vYzovSm9aKYybyF8MRuBJQ_);
TM_7pfbsA4Z15mK79cUgzyqfaA_0[0].name = "color";
NTI_2ltTHdgBChx9cgtqnSkskXA_.node = &TM_7pfbsA4Z15mK79cUgzyqfaA_0[0];
NTI_N79boNLVsc9bx7gvK8hUee8A_.size = sizeof(tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A);
NTI_N79boNLVsc9bx7gvK8hUee8A_.kind = 17;
NTI_N79boNLVsc9bx7gvK8hUee8A_.base = (&NTI_2ltTHdgBChx9cgtqnSkskXA_);
TM_7pfbsA4Z15mK79cUgzyqfaA_24[0] = &TM_7pfbsA4Z15mK79cUgzyqfaA_0[7];
TM_7pfbsA4Z15mK79cUgzyqfaA_0[7].kind = 1;
TM_7pfbsA4Z15mK79cUgzyqfaA_0[7].offset = offsetof(tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A, image);
TM_7pfbsA4Z15mK79cUgzyqfaA_0[7].typ = (&NTI_0kDVS9b1UyEqr8DfAGXwn9cQ_);
TM_7pfbsA4Z15mK79cUgzyqfaA_0[7].name = "image";
TM_7pfbsA4Z15mK79cUgzyqfaA_24[1] = &TM_7pfbsA4Z15mK79cUgzyqfaA_0[8];
TM_7pfbsA4Z15mK79cUgzyqfaA_0[8].kind = 1;
TM_7pfbsA4Z15mK79cUgzyqfaA_0[8].offset = offsetof(tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A, region);
TM_7pfbsA4Z15mK79cUgzyqfaA_0[8].typ = (&NTI_u6eWcr48DqP0Ue9cUPPUypg_);
TM_7pfbsA4Z15mK79cUgzyqfaA_0[8].name = "region";
TM_7pfbsA4Z15mK79cUgzyqfaA_24[2] = &TM_7pfbsA4Z15mK79cUgzyqfaA_0[9];
TM_7pfbsA4Z15mK79cUgzyqfaA_0[9].kind = 1;
TM_7pfbsA4Z15mK79cUgzyqfaA_0[9].offset = offsetof(tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A, flip);
TM_7pfbsA4Z15mK79cUgzyqfaA_0[9].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_7pfbsA4Z15mK79cUgzyqfaA_0[9].name = "flip";
TM_7pfbsA4Z15mK79cUgzyqfaA_0[6].len = 3; TM_7pfbsA4Z15mK79cUgzyqfaA_0[6].kind = 2; TM_7pfbsA4Z15mK79cUgzyqfaA_0[6].sons = &TM_7pfbsA4Z15mK79cUgzyqfaA_24[0];
NTI_N79boNLVsc9bx7gvK8hUee8A_.node = &TM_7pfbsA4Z15mK79cUgzyqfaA_0[6];
NTI_nBvHJ1Rw03MS6yxDbJRrvQ_.size = sizeof(tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A*);
NTI_nBvHJ1Rw03MS6yxDbJRrvQ_.kind = 22;
NTI_nBvHJ1Rw03MS6yxDbJRrvQ_.base = (&NTI_N79boNLVsc9bx7gvK8hUee8A_);
NTI_nBvHJ1Rw03MS6yxDbJRrvQ_.marker = Marker_tyRef_nBvHJ1Rw03MS6yxDbJRrvQ;
}

