/* Generated by Nim Compiler v0.18.1 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/dustin/Documents/Nim/lib -o /home/dustin/Documents/Nim_Projects/VectorGuy/src/nimcache/VectorGuy_player.o /home/dustin/Documents/Nim_Projects/VectorGuy/src/nimcache/VectorGuy_player.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g;
typedef struct tyObject_PhysicsBodycolonObjectType__qOCpO56KLJz1SFjXu8FuZw tyObject_PhysicsBodycolonObjectType__qOCpO56KLJz1SFjXu8FuZw;
typedef struct tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ;
typedef struct RootObj RootObj;
typedef struct tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ;
typedef struct tySequence_sxV7BWZ9cww0pVdm9bqsswoA tySequence_sxV7BWZ9cww0pVdm9bqsswoA;
typedef struct tyObject_PhysicsObjectcolonObjectType__pT1SYs16c4VQPrPWuA2cJA tyObject_PhysicsObjectcolonObjectType__pT1SYs16c4VQPrPWuA2cJA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ;
typedef struct tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A;
typedef struct tyObject_ClockcolonObjectType__i9caNiZ1Ae9aC9bMNXyaOIwqA tyObject_ClockcolonObjectType__i9caNiZ1Ae9aC9bMNXyaOIwqA;
typedef struct tyObject_DrawablecolonObjectType__2ltTHdgBChx9cgtqnSkskXA tyObject_DrawablecolonObjectType__2ltTHdgBChx9cgtqnSkskXA;
typedef struct tyTuple_0vYzovSm9aKYybyF8MRuBJQ tyTuple_0vYzovSm9aKYybyF8MRuBJQ;
typedef struct tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ;
typedef struct tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ;
typedef struct tyObject_CameracolonObjectType__uk8C2BjPELBcegmVYWmD5Q tyObject_CameracolonObjectType__uk8C2BjPELBcegmVYWmD5Q;
typedef struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tyObject_PlayercolonObjectType__XT8bNNou1LsCIl1jlU5CFQ tyObject_PlayercolonObjectType__XT8bNNou1LsCIl1jlU5CFQ;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e, void* ClE_0);
void* ClE_0;
} tyProc_LTibXkW8wgZIS6uZJDSRwg;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, void* ClE_0);
void* ClE_0;
} tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ;
struct RootObj {
TNimType* m_type;
};
struct tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ {
  RootObj Sup;
};
typedef NU8 tyEnum_PhysicsType_JOO6TjZ3B9bNSHGgTMd9cP9aQ;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_PhysicsObjectcolonObjectType__pT1SYs16c4VQPrPWuA2cJA* solid, void* ClE_0);
void* ClE_0;
} tyProc_yA6KJnbz0A2EaGKKnqdODw;
struct tyObject_PhysicsBodycolonObjectType__qOCpO56KLJz1SFjXu8FuZw {
  tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ Sup;
tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ* velocity;
NF friction;
NIM_BOOL isOnGround;
NIM_BOOL isOnLadder;
NF gravity_scale;
tyEnum_PhysicsType_JOO6TjZ3B9bNSHGgTMd9cP9aQ physicsType;
tySequence_sxV7BWZ9cww0pVdm9bqsswoA* collisions;
tyProc_yA6KJnbz0A2EaGKKnqdODw solidsCollisionCallback;
};
typedef N_CLOSURE_PTR(void, TM_cvq4HyG9a2115aknPeSQIUQ_9) (tyObject_PhysicsObjectcolonObjectType__pT1SYs16c4VQPrPWuA2cJA* solid, void* ClE_0);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef N_CLOSURE_PTR(void, TM_cvq4HyG9a2115aknPeSQIUQ_10) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e, void* ClE_0);
typedef N_CLOSURE_PTR(void, TM_cvq4HyG9a2115aknPeSQIUQ_11) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, void* ClE_0);
typedef NI32 tyEnum_Key_jK5vGfOANLpC8IBluSyM9ag;
struct tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ {
NF x;
NF y;
};
struct tyObject_ClockcolonObjectType__i9caNiZ1Ae9aC9bMNXyaOIwqA {
NF dt;
NF fps;
NF timer;
NF last;
NI ticks;
};
struct tyTuple_0vYzovSm9aKYybyF8MRuBJQ {
NF Field0;
NF Field1;
NF Field2;
NF Field3;
};
struct tyObject_DrawablecolonObjectType__2ltTHdgBChx9cgtqnSkskXA {
  tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ Sup;
tyTuple_0vYzovSm9aKYybyF8MRuBJQ color;
tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ* offset;
NF rotation;
};
struct tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A {
  tyObject_DrawablecolonObjectType__2ltTHdgBChx9cgtqnSkskXA Sup;
tyObject_ImageObj_CILs0aI9a15OLIJJawRpwrQ* image;
tyObject_RegioncolonObjectType__3GkqZw84cOmRRUHsNmUZKQ* region;
NIM_BOOL flip;
};
struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
struct tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ {
  tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ Sup;
tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ* position;
tyObject_V2colonObjectType__7QktHEx9bk9c49aaJTG6xOEFQ* size;
};
struct tyObject_CameracolonObjectType__uk8C2BjPELBcegmVYWmD5Q {
  tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ Sup;
NF zoom;
NF rotation;
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
typedef N_CLOSURE_PTR(void, TM_cvq4HyG9a2115aknPeSQIUQ_16) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e, void* ClE_0);
typedef N_CLOSURE_PTR(void, TM_cvq4HyG9a2115aknPeSQIUQ_17) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e, void* ClE_0);
typedef N_CLOSURE_PTR(void, TM_cvq4HyG9a2115aknPeSQIUQ_18) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e, void* ClE_0);
typedef N_CLOSURE_PTR(void, TM_cvq4HyG9a2115aknPeSQIUQ_19) (tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, void* ClE_0);
struct tyObject_PlayercolonObjectType__XT8bNNou1LsCIl1jlU5CFQ {
  tyObject_ComponentcolonObjectType__X8aacFQVnMMG3eJMkbZvPQ Sup;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_sxV7BWZ9cww0pVdm9bqsswoA {
  TGenericSeq Sup;
  tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_cvq4HyG9a2115aknPeSQIUQ_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_LIB_PRIVATE N_NIMCALL(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw*, createSystem_ZIEE3eqxo9anA1Qzcbrx5Vg)(tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg* world, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* matchlist, tyProc_LTibXkW8wgZIS6uZJDSRwg load, tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ preUpdate, tyProc_LTibXkW8wgZIS6uZJDSRwg update, tyProc_LTibXkW8wgZIS6uZJDSRwg draw, tyProc_LTibXkW8wgZIS6uZJDSRwg destroy, tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ preDraw);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous__9aegO9ailMMNreADFORDYNNQ)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* sys, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self);
N_LIB_PRIVATE N_NIMCALL(tyObject_PhysicsBodycolonObjectType__qOCpO56KLJz1SFjXu8FuZw*, get_bz2WrLTHQuyavdukYjN8Cw)(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous__0SgUe69ctLLjGcLf9bq5K9bQg)(tyObject_PhysicsObjectcolonObjectType__pT1SYs16c4VQPrPWuA2cJA* o);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, default_preUpdate_bubQNMeUwRg1mVj2B77VVg)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous__sjK5UqBbQBqx4h9acW6gL6g)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self);
N_LIB_PRIVATE N_NIMCALL(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ*, get_UpICIghUTrvN3fZF3drLBQ)(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self);
N_LIB_PRIVATE N_NIMCALL(tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A*, get_RSEbINeSUjOPFVLfePsoHQ)(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isKeyDown_RhH8btHgNWFRXiAyNJ39c5Q)(tyEnum_Key_jK5vGfOANLpC8IBluSyM9ag key);
static N_INLINE(void, minuseq__7kHiltrvRlcg6wSYR3CxAwplayer)(NF* x, NF y);
static N_INLINE(void, pluseq__7kHiltrvRlcg6wSYR3CxAw_2physics)(NF* x, NF y);
N_LIB_PRIVATE N_NIMCALL(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, windowSize_IiXrDDZnIvC9aOPZJDd9acOw)(void);
N_LIB_PRIVATE N_NIMCALL(NF, x_GjB2bcom6jNDdYSzGflP3w)(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* b);
N_LIB_PRIVATE N_NIMCALL(NF, y_GjB2bcom6jNDdYSzGflP3w_2)(tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* b);
N_NOINLINE(void, raiseIndexError)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, has_FpBorqVgH9cRtK6hvltPKqw)(tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(void, default_render_yWuOcLIgmhG0YcAceats8w_4)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e);
N_LIB_PRIVATE N_NIMCALL(void, default_destroy_yWuOcLIgmhG0YcAceats8w_2)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* e);
N_LIB_PRIVATE N_NIMCALL(void, default_preDraw_bubQNMeUwRg1mVj2B77VVg_2)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s);
static N_NIMCALL(void, Marker_tyRef_r6M4b6P6UgVEQamv7m7bOg)(void* p, NI op);
tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* PlayerController_E9bJAzFGdleDPUYoDE9aWlrQ;
extern TNimType NTI_kqRkyKwWUGhRwkJfLvzABw_;
extern tyObject_WorldcolonObjectType__KccFVpsYw1e2AJ3Xnk9cAfg* world_M14QSo1egm66WmikxMh52g;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern tyObject_ClockcolonObjectType__i9caNiZ1Ae9aC9bMNXyaOIwqA* clock_XGJlevjwnAIKRRsiWSQCKQ;
extern tyObject_CameracolonObjectType__uk8C2BjPELBcegmVYWmD5Q* camera_gC9bhqCy0IQgaCB9bxtui42g;
extern TNimType NTI_X8aacFQVnMMG3eJMkbZvPQ_;
TNimType NTI_XT8bNNou1LsCIl1jlU5CFQ_;
TNimType NTI_r6M4b6P6UgVEQamv7m7bOg_;
STRING_LITERAL(TM_cvq4HyG9a2115aknPeSQIUQ_4, "Body", 4);
STRING_LITERAL(TM_cvq4HyG9a2115aknPeSQIUQ_5, "Player", 6);
STRING_LITERAL(TM_cvq4HyG9a2115aknPeSQIUQ_6, "PhysicsBody", 11);
STRING_LITERAL(TM_cvq4HyG9a2115aknPeSQIUQ_7, "Sprite", 6);
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[4];
} TM_cvq4HyG9a2115aknPeSQIUQ_8 = {{4, 4}, {((NimStringDesc*) &TM_cvq4HyG9a2115aknPeSQIUQ_4),
((NimStringDesc*) &TM_cvq4HyG9a2115aknPeSQIUQ_5),
((NimStringDesc*) &TM_cvq4HyG9a2115aknPeSQIUQ_6),
((NimStringDesc*) &TM_cvq4HyG9a2115aknPeSQIUQ_7)}};
NIM_CONST tySequence_sM4lkSb7zS6F7OVMvW9cffQ* TM_cvq4HyG9a2115aknPeSQIUQ_3 = ((tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)&TM_cvq4HyG9a2115aknPeSQIUQ_8);
STRING_LITERAL(TM_cvq4HyG9a2115aknPeSQIUQ_13, "item", 4);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_cvq4HyG9a2115aknPeSQIUQ_12 = {((NimStringDesc*) &TM_cvq4HyG9a2115aknPeSQIUQ_13)}
;
STRING_LITERAL(TM_cvq4HyG9a2115aknPeSQIUQ_15, "len(a) == L seq modified while iterating over it", 48);
static N_NIMCALL(void, TM_cvq4HyG9a2115aknPeSQIUQ_2)(void) {
	nimGCvisit((void*)PlayerController_E9bJAzFGdleDPUYoDE9aWlrQ, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(void, colonanonymous__0SgUe69ctLLjGcLf9bq5K9bQg)(tyObject_PhysicsObjectcolonObjectType__pT1SYs16c4VQPrPWuA2cJA* o) {
	nimfr_(":anonymous", "player.nim");
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(400, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(400, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, colonanonymous__9aegO9ailMMNreADFORDYNNQ)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* sys, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self) {
	tyObject_PhysicsBodycolonObjectType__qOCpO56KLJz1SFjXu8FuZw* phys;
	tyProc_yA6KJnbz0A2EaGKKnqdODw T1_;
	nimfr_(":anonymous", "player.nim");
	nimln_(24, "player.nim");
	phys = get_bz2WrLTHQuyavdukYjN8Cw(self);
	nimln_(26, "player.nim");
	memset((void*)(&T1_), 0, sizeof(tyProc_yA6KJnbz0A2EaGKKnqdODw));
	T1_.ClP_0 = ((TM_cvq4HyG9a2115aknPeSQIUQ_9) (colonanonymous__0SgUe69ctLLjGcLf9bq5K9bQg)); T1_.ClE_0 = NIM_NIL;
	asgnRef((void**) (&(*phys).solidsCollisionCallback.ClE_0), T1_.ClE_0);
	(*phys).solidsCollisionCallback.ClP_0 = T1_.ClP_0;
	popFrame();
}

static N_INLINE(void, minuseq__7kHiltrvRlcg6wSYR3CxAwplayer)(NF* x, NF y) {
	nimfr_("-=", "system.nim");
	nimln_(3715, "system.nim");
	(*x) = ((NF)((*x)) - (NF)(y));
	popFrame();
}

static N_INLINE(void, pluseq__7kHiltrvRlcg6wSYR3CxAw_2physics)(NF* x, NF y) {
	nimfr_("+=", "system.nim");
	nimln_(3710, "system.nim");
	(*x) = ((NF)((*x)) + (NF)(y));
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, colonanonymous__sjK5UqBbQBqx4h9acW6gL6g)(tyObject_SystemcolonObjectType__bUxkNAwYdPyt85kuMYOTKw* s, tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* self) {
	tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* body;
	tyObject_PhysicsBodycolonObjectType__qOCpO56KLJz1SFjXu8FuZw* phys;
	tyObject_SpritecolonObjectType__N79boNLVsc9bx7gvK8hUee8A* sprite;
	tyObject_CameracolonObjectType__uk8C2BjPELBcegmVYWmD5Q* camera;
	tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ T29_;
	NI ww;
	NI hh;
	NF w;
	NF h;
	NF x;
	NF T30_;
	NF y;
	NF dx;
	tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* T31_;
	NF T32_;
	NF dy;
	tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ* T33_;
	NF T34_;
	nimfr_(":anonymous", "player.nim");
	nimln_(30, "player.nim");
	body = get_UpICIghUTrvN3fZF3drLBQ(self);
	nimln_(31, "player.nim");
	phys = get_bz2WrLTHQuyavdukYjN8Cw(self);
	nimln_(32, "player.nim");
	sprite = get_RSEbINeSUjOPFVLfePsoHQ(self);
	nimln_(34, "player.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isKeyDown_RhH8btHgNWFRXiAyNJ39c5Q(((tyEnum_Key_jK5vGfOANLpC8IBluSyM9ag) 1073741904));
		if (!T3_) goto LA4_;
		nimln_(35, "player.nim");
		minuseq__7kHiltrvRlcg6wSYR3CxAwplayer((&(*(*phys).velocity).x), ((NF)(3.0000000000000000e+02) * (NF)((*clock_XGJlevjwnAIKRRsiWSQCKQ).dt)));
		nimln_(36, "player.nim");
		(*sprite).flip = NIM_TRUE;
	}
	LA4_: ;
	nimln_(38, "player.nim");
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = isKeyDown_RhH8btHgNWFRXiAyNJ39c5Q(((tyEnum_Key_jK5vGfOANLpC8IBluSyM9ag) 1073741903));
		if (!T8_) goto LA9_;
		nimln_(39, "player.nim");
		pluseq__7kHiltrvRlcg6wSYR3CxAw_2physics((&(*(*phys).velocity).x), ((NF)(3.0000000000000000e+02) * (NF)((*clock_XGJlevjwnAIKRRsiWSQCKQ).dt)));
		nimln_(40, "player.nim");
		(*sprite).flip = NIM_FALSE;
	}
	LA9_: ;
	nimln_(42, "player.nim");
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = (*phys).isOnLadder;
		if (!(T13_)) goto LA14_;
		T13_ = isKeyDown_RhH8btHgNWFRXiAyNJ39c5Q(((tyEnum_Key_jK5vGfOANLpC8IBluSyM9ag) 1073741905));
		LA14_: ;
		if (!T13_) goto LA15_;
		nimln_(43, "player.nim");
		pluseq__7kHiltrvRlcg6wSYR3CxAw_2physics((&(*(*phys).velocity).y), ((NF)(((NF)(3.0000000000000000e+02) * (NF)((*clock_XGJlevjwnAIKRRsiWSQCKQ).dt))) * (NF)(1.5000000000000000e+01)));
	}
	LA15_: ;
	nimln_(45, "player.nim");
	{
		NIM_BOOL T19_;
		T19_ = (NIM_BOOL)0;
		T19_ = (*phys).isOnLadder;
		if (!(T19_)) goto LA20_;
		T19_ = isKeyDown_RhH8btHgNWFRXiAyNJ39c5Q(((tyEnum_Key_jK5vGfOANLpC8IBluSyM9ag) 1073741906));
		LA20_: ;
		if (!T19_) goto LA21_;
		nimln_(46, "player.nim");
		minuseq__7kHiltrvRlcg6wSYR3CxAwplayer((&(*(*phys).velocity).y), ((NF)(((NF)(3.0000000000000000e+02) * (NF)((*clock_XGJlevjwnAIKRRsiWSQCKQ).dt))) * (NF)(1.5000000000000000e+01)));
	}
	LA21_: ;
	nimln_(48, "player.nim");
	{
		NIM_BOOL T25_;
		T25_ = (NIM_BOOL)0;
		T25_ = isKeyDown_RhH8btHgNWFRXiAyNJ39c5Q(((tyEnum_Key_jK5vGfOANLpC8IBluSyM9ag) 122));
		if (!(T25_)) goto LA26_;
		T25_ = (*phys).isOnGround;
		LA26_: ;
		if (!T25_) goto LA27_;
		nimln_(49, "player.nim");
		minuseq__7kHiltrvRlcg6wSYR3CxAwplayer((&(*(*phys).velocity).y), 4.0000000000000000e+02);
	}
	LA27_: ;
	nimln_(51, "player.nim");
	camera = camera_gC9bhqCy0IQgaCB9bxtui42g;
	nimln_(53, "player.nim");
	T29_ = windowSize_IiXrDDZnIvC9aOPZJDd9acOw();
	ww = T29_.Field0;
	hh = T29_.Field1;
	nimln_(54, "player.nim");
	w = ((NF)(((NF) (ww))) / (NF)((*camera).zoom));
	nimln_(55, "player.nim");
	h = ((NF)(((NF) (hh))) / (NF)((*camera).zoom));
	nimln_(57, "player.nim");
	T30_ = (NF)0;
	T30_ = x_GjB2bcom6jNDdYSzGflP3w(body);
	x = ((NF)(T30_) + (NF)(((NF)((*(*phys).velocity).x) * (NF)(5.0000000000000000e-01))));
	nimln_(58, "player.nim");
	y = y_GjB2bcom6jNDdYSzGflP3w_2(body);
	nimln_(60, "player.nim");
	T31_ = (tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ*)0;
	T31_ = &camera->Sup;
	T32_ = (NF)0;
	T32_ = x_GjB2bcom6jNDdYSzGflP3w(T31_);
	dx = ((NF)(((NF)(T32_) + (NF)(((NF)(w) * (NF)(5.0000000000000000e-01))))) - (NF)(x));
	nimln_(61, "player.nim");
	T33_ = (tyObject_BodycolonObjectType__gcAPnvgqasHnAwLl6W9cWFQ*)0;
	T33_ = &camera->Sup;
	T34_ = (NF)0;
	T34_ = y_GjB2bcom6jNDdYSzGflP3w_2(T33_);
	dy = ((NF)(((NF)(T34_) + (NF)(((NF)(h) * (NF)(5.0000000000000000e-01))))) - (NF)(y));
	nimln_(63, "player.nim");
	minuseq__7kHiltrvRlcg6wSYR3CxAwplayer((&(*(*camera).Sup.position).x), ((NF)(dx) * (NF)(1.0000000000000001e-01)));
	nimln_(64, "player.nim");
	minuseq__7kHiltrvRlcg6wSYR3CxAwplayer((&(*(*camera).Sup.position).y), ((NF)(dy) * (NF)(1.0000000000000001e-01)));
	{
		tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g* other;
		tySequence_sxV7BWZ9cww0pVdm9bqsswoA* colontmp_;
		NI i;
		NI L;
		NI T36_;
		other = (tyObject_EntitycolonObjectType__9bwdc6iyZGiId8gvyONht0g*)0;
		colontmp_ = (tySequence_sxV7BWZ9cww0pVdm9bqsswoA*)0;
		nimln_(67, "player.nim");
		colontmp_ = (*phys).collisions;
		nimln_(3815, "system.nim");
		i = ((NI) 0);
		nimln_(3816, "system.nim");
		T36_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T36_;
		{
			nimln_(3817, "system.nim");
			while (1) {
				NI TM_cvq4HyG9a2115aknPeSQIUQ_14;
				if (!(i < L)) goto LA38;
				nimln_(3818, "system.nim");
				if (!colontmp_ || (NU)(i) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
				other = colontmp_->data[i];
				nimln_(68, "player.nim");
				{
					NIM_BOOL T41_;
					T41_ = (NIM_BOOL)0;
					T41_ = has_FpBorqVgH9cRtK6hvltPKqw(other);
					if (!T41_) goto LA42_;
					nimln_(69, "player.nim");
					echoBinSafe(TM_cvq4HyG9a2115aknPeSQIUQ_12, 1);
				}
				LA42_: ;
				nimln_(3819, "system.nim");
				TM_cvq4HyG9a2115aknPeSQIUQ_14 = addInt(i, ((NI) 1));
				i = (NI)(TM_cvq4HyG9a2115aknPeSQIUQ_14);
				nimln_(3820, "system.nim");
				{
					NI T46_;
					T46_ = (colontmp_ ? colontmp_->Sup.len : 0);
					if (!!((T46_ == L))) goto LA47_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_cvq4HyG9a2115aknPeSQIUQ_15));
				}
				LA47_: ;
			} LA38: ;
		}
	}
	popFrame();
}
static N_NIMCALL(void, Marker_tyRef_r6M4b6P6UgVEQamv7m7bOg)(void* p, NI op) {
	tyObject_PlayercolonObjectType__XT8bNNou1LsCIl1jlU5CFQ* a;
	a = (tyObject_PlayercolonObjectType__XT8bNNou1LsCIl1jlU5CFQ*)p;
}
NIM_EXTERNC N_NOINLINE(void, VectorGuy_playerInit000)(void) {
	tyProc_LTibXkW8wgZIS6uZJDSRwg T1_;
	tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ T2_;
	tyProc_LTibXkW8wgZIS6uZJDSRwg T3_;
	tyProc_LTibXkW8wgZIS6uZJDSRwg T4_;
	tyProc_LTibXkW8wgZIS6uZJDSRwg T5_;
	tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ T6_;
	nimfr_("player", "player.nim");
nimRegisterGlobalMarker(TM_cvq4HyG9a2115aknPeSQIUQ_2);
	nimln_(21, "player.nim");
	memset((void*)(&T1_), 0, sizeof(tyProc_LTibXkW8wgZIS6uZJDSRwg));
	T1_.ClP_0 = ((TM_cvq4HyG9a2115aknPeSQIUQ_10) (colonanonymous__9aegO9ailMMNreADFORDYNNQ)); T1_.ClE_0 = NIM_NIL;
	memset((void*)(&T2_), 0, sizeof(tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ));
	T2_.ClP_0 = ((TM_cvq4HyG9a2115aknPeSQIUQ_11) (default_preUpdate_bubQNMeUwRg1mVj2B77VVg)); T2_.ClE_0 = NIM_NIL;
	memset((void*)(&T3_), 0, sizeof(tyProc_LTibXkW8wgZIS6uZJDSRwg));
	T3_.ClP_0 = ((TM_cvq4HyG9a2115aknPeSQIUQ_16) (colonanonymous__sjK5UqBbQBqx4h9acW6gL6g)); T3_.ClE_0 = NIM_NIL;
	memset((void*)(&T4_), 0, sizeof(tyProc_LTibXkW8wgZIS6uZJDSRwg));
	T4_.ClP_0 = ((TM_cvq4HyG9a2115aknPeSQIUQ_17) (default_render_yWuOcLIgmhG0YcAceats8w_4)); T4_.ClE_0 = NIM_NIL;
	memset((void*)(&T5_), 0, sizeof(tyProc_LTibXkW8wgZIS6uZJDSRwg));
	T5_.ClP_0 = ((TM_cvq4HyG9a2115aknPeSQIUQ_18) (default_destroy_yWuOcLIgmhG0YcAceats8w_2)); T5_.ClE_0 = NIM_NIL;
	memset((void*)(&T6_), 0, sizeof(tyProc_Ulk9cd4UOHLw9aKiI8pa0uaQ));
	T6_.ClP_0 = ((TM_cvq4HyG9a2115aknPeSQIUQ_19) (default_preDraw_bubQNMeUwRg1mVj2B77VVg_2)); T6_.ClE_0 = NIM_NIL;
	asgnRef((void**) (&PlayerController_E9bJAzFGdleDPUYoDE9aWlrQ), createSystem_ZIEE3eqxo9anA1Qzcbrx5Vg(world_M14QSo1egm66WmikxMh52g, TM_cvq4HyG9a2115aknPeSQIUQ_3, T1_, T2_, T3_, T4_, T5_, T6_));
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, VectorGuy_playerDatInit000)(void) {
static TNimNode TM_cvq4HyG9a2115aknPeSQIUQ_0[1];
NTI_XT8bNNou1LsCIl1jlU5CFQ_.size = sizeof(tyObject_PlayercolonObjectType__XT8bNNou1LsCIl1jlU5CFQ);
NTI_XT8bNNou1LsCIl1jlU5CFQ_.kind = 17;
NTI_XT8bNNou1LsCIl1jlU5CFQ_.base = (&NTI_X8aacFQVnMMG3eJMkbZvPQ_);
NTI_XT8bNNou1LsCIl1jlU5CFQ_.flags = 1;
TM_cvq4HyG9a2115aknPeSQIUQ_0[0].len = 0; TM_cvq4HyG9a2115aknPeSQIUQ_0[0].kind = 2;
NTI_XT8bNNou1LsCIl1jlU5CFQ_.node = &TM_cvq4HyG9a2115aknPeSQIUQ_0[0];
NTI_r6M4b6P6UgVEQamv7m7bOg_.size = sizeof(tyObject_PlayercolonObjectType__XT8bNNou1LsCIl1jlU5CFQ*);
NTI_r6M4b6P6UgVEQamv7m7bOg_.kind = 22;
NTI_r6M4b6P6UgVEQamv7m7bOg_.base = (&NTI_XT8bNNou1LsCIl1jlU5CFQ_);
NTI_r6M4b6P6UgVEQamv7m7bOg_.marker = Marker_tyRef_r6M4b6P6UgVEQamv7m7bOg;
}

